version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    assignees:
      - constrat
      - AnnAngela
    groups:
      github-actions:
        patterns:
          - "*"
