"module: copilot":
  - '(自动作战|自动战斗|自动编队|作业|copilot|自動戰鬥|自動戦闘|作業)'
"module: fight":
  - '(刷图|刷.{0,6}材料|战斗|作战|戰鬥|戦闘|fight|battle)'
  - '\^(\?\!.*(自动作战|自动战斗|自动编队|作业|copilot|自動戰鬥|自動戦闘|作業)).*'
  - '\^(\?\!.*(肉鸽|集成战略|rogue|肉鴿|ローグ)).*'
"module: GUI":
  # 其它模块都匹配不上的时候再尝试匹配GUI
  # 因为可能有人说“公招界面”“肉鸽崩溃”“基建闪退”等等
  - '(界面|闪退|崩溃|gui|GUI|crash|介面|画面|インターフェース)'
  - '\^(\?\!.*(自动作战|自动战斗|自动编队|作业|copilot|自動戰鬥|自動戦闘|作業)).*'
  - '\^(\?\!.*(刷图|刷.{0,6}材料|战斗|作战|戰鬥|戦闘|fight|battle)).*'
  - '\^(\?\!.*(基建|贸易站|制造站|控制中枢|会客室|infrast|base|基地)).*'
  - '\^(\?\!.*(信用|拜访|登录|开始唤醒|visit|login|startup)).*'
  - '\^(\?\!.*(公招|公开招募|recruit|公開求人)).*'
  - '\^(\?\!.*(肉鸽|集成战略|rogue|肉鴿|ローグ)).*'
"module: infrast":
  - '(基建|贸易站|制造站|控制中枢|会客室|infrast|base|基地)'
"module: others":
  - '(信用|拜访|登录|开始唤醒|visit|login|startup)'
"module: recruit":
  - '(公招|招募|recruit|公開求人)'
  - '\^(\?\!.*(肉鸽|集成战略|rogue|肉鴿|ローグ)).*'
"module: roguelike":
  - '(肉鸽|集成战略|rogue|肉鴿|ローグ)'
"release":
  - '(Release v(\d)+\.(\d)+\.(\d)+)'
"ambiguous":
  # 不符合上面任何一个的分类并且（如果是PR）不符合 commitizen
  - '\^(\?\!.*(feat|chore|perf|style|refactor|fix|doc)).*'
  - '\^(\?\!.*(自动作战|自动战斗|自动编队|作业|copilot|自動戰鬥|自動戦闘|作業)).*'
  - '\^(\?\!.*(刷图|刷.{0,6}材料|战斗|作战|戰鬥|戦闘|fight|battle)).*'
  - '\^(\?\!.*(界面|闪退|崩溃|gui|GUI|crash|介面|画面|インターフェース)).*'
  - '\^(\?\!.*(基建|贸易站|制造站|控制中枢|会客室|infrast|base|基地)).*'
  - '\^(\?\!.*(信用|拜访|登录|开始唤醒|visit|login|startup)).*'
  - '\^(\?\!.*(公招|公开招募|recruit|公開求人)).*'
  - '\^(\?\!.*(肉鸽|集成战略|rogue|肉鴿|ローグ)).*'
  - '\^(\?\!.*(Release v(\d)+\.(\d)+\.(\d)+)).*'
