# <!-- [Aa]dd `LABEL` --> 可以强制加上一个 label
# <!-- [Rr]emove `LABEL` --> 可以强制去掉一个 label
# Add 的优先级比 Remove 高
"module: copilot":
  - '(?:[Aa]dd (?:`|)(?:module: |)copilot(?:`|)|自动(作战|战斗|编队)|作业|自動(戰|戦)(鬥|闘)|作業|copilot)'
  - "(?:[Aa]dd (?:`|)(?:module: |)copilot(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)copilot(?:`|))))[\\s\\S]*$)"
"module: fight":
  - '(?:[Aa]dd (?:`|)(?:module: |)fight(?:`|)|刷图|刷.{0,6}材料|关卡选择|战斗|作战|(戰|戦)(鬥|闘)|fight|battle)'
  - "(?:[Aa]dd (?:`|)(?:module: |)fight(?:`|)|^(?![\\s\\S]*(?:\
  自动(作战|战斗|编队)|作业|自動(戰|戦)(鬥|闘)|作業|copilot|\
  肉(鸽|鴿)|集成战略|rogue|ローグ|\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)fight(?:`|))))[\\s\\S]*$)"
"module: GUI":
  # 其它模块都匹配不上的时候再尝试匹配GUI
  # 因为可能有人说“公招界面”“肉鸽崩溃”“基建闪退”等等
  - '(?:[Aa]dd (?:`|)(?:module: |)GUI(?:`|)|图形化界面|闪退|gui|GUI|インターフェース)'
  - "(?:[Aa]dd (?:`|)(?:module: |)GUI(?:`|)|^(?![\\s\\S]*(?:\
  自动编队|作业|作業|copilot|\
  刷图|刷.{0,6}材料|关卡选择|战斗|作战|(戰|戦)(鬥|闘)|fight|battle|\
  基建|贸易站|制造站|控制中枢|会客室|基地|infrast|base|\
  信用|拜访|登录|开始唤醒|visit|login|startup|\
  公招|招募|公開(募集|求人)|recruit|\
  肉(鸽|鴿)|集成战略|rogue|ローグ|\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)GUI(?:`|))))[\\s\\S]*$)"
"module: infrast":
  - '(?:[Aa]dd (?:`|)(?:module: |)infrast(?:`|)|基建|贸易站|制造站|控制中枢|会客室|基地|infrast|base)'
  - "(?:[Aa]dd (?:`|)(?:module: |)infrast(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)infrast(?:`|))))[\\s\\S]*$)"
"module: others":
  - '(?:[Aa]dd (?:`|)(?:module: |)others(?:`|)|信用|拜访|登录|开始唤醒|visit|login|startup)'
  - "(?:[Aa]dd (?:`|)(?:module: |)others(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)others(?:`|))))[\\s\\S]*$)"
"module: recruit":
  - '(?:[Aa]dd (?:`|)(?:module: |)recruit(?:`|)|公招|招募|公開(募集|求人)|recruit)'
  - "(?:[Aa]dd (?:`|)(?:module: |)recruit(?:`|)|^(?![\\s\\S]*(?:\
  肉(鸽|鴿)|集成战略|rogue|ローグ|\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)recruit(?:`|))))[\\s\\S]*$)"
"module: roguelike":
  - '(?:[Aa]dd (?:`|)(?:module: |)roguelike(?:`|)|肉(鸽|鴿)|集成战略|rogue|ローグ)'
  - "(?:[Aa]dd (?:`|)(?:module: |)roguelike(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)roguelike(?:`|))))[\\s\\S]*$)"
"release":
  - '(?:[Aa]dd (?:`|)release(?:`|)|Release v(?:\d)+\.(?:\d)+\.(?:\d)+)'
  - "(?:[Aa]dd (?:`|)release(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)release(?:`|))))[\\s\\S]*$)"
"ambiguous":
  # 不符合上面任何一个的分类并且（如果是PR）不符合 commitizen
  - '(?:[Aa]dd (?:`|)ambiguous(?:`|))'
  - "(?:[Aa]dd (?:`|)ambiguous(?:`|)|^(?![\\s\\S]*(?:\
  feat|chore|perf|style|refactor|fix|doc|\
  自动编队|作业|作業|copilot|\
  刷图|刷.{0,6}材料|关卡选择|战斗|作战|戰鬥|戦闘|fight|battle|\
  图形化界面|闪退|gui|GUI|インターフェース|\
  基建|贸易站|制造站|控制中枢|会客室|基地|infrast|base|\
  信用|拜访|登录|开始唤醒|visit|login|startup|\
  公招|招募|公開(募集|求人)|recruit|\
  肉(鸽|鴿)|集成战略|rogue|ローグ|\
  Release v(?:\\d)+\\.(?:\\d)+\\.(?:\\d)+|\
  [Rr]emove (?:[Aa]ll labels|(?:`|)ambiguous(?:`|))))[\\s\\S]*$)"
"translation required":
  # 不要使用日文发 issue
  - "(?:[Aa]dd (?:`|)translation required(?:`|)|([\\u3040-\\u30ff]|[㍿㍐]))"
  - "(?:[Aa]dd (?:`|)translation required(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)translation required(?:`|))))[\\s\\S]*$)"
"Client: JP":
  - '(?:[Aa]dd (?:`|)(?:module: |)Client: JP(?:`|)|日(文|语|本|)服|YoStarJP)'
  - "(?:[Aa]dd (?:`|)(?:module: |)Client: JP(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)Client: JP(?:`|))))[\\s\\S]*$)"
"Client: EN":
  - '(?:[Aa]dd (?:`|)(?:module: |)Client: EN(?:`|)|英(文|语|)服|国际服|美服|YoStarEN)'
  - "(?:[Aa]dd (?:`|)(?:module: |)Client: EN(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)Client: EN(?:`|))))[\\s\\S]*$)"
"Client: KR":
  - '(?:[Aa]dd (?:`|)(?:module: |)Client: KR(?:`|)|韩(文|语|国|)服|YoStarKR)'
  - "(?:[Aa]dd (?:`|)(?:module: |)Client: KR(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)Client: KR(?:`|))))[\\s\\S]*$)"
"Client: ZH_TW":
  - '(?:[Aa]dd (?:`|)(?:module: |)Client: ZH_TW(?:`|)|繁中服|台(湾|灣|)服|繁体中文服|(龙|龍)成|天下网游|txwy)'
  - "(?:[Aa]dd (?:`|)(?:module: |)Client: ZH_TW(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:module: |)Client: ZH_TW(?:`|))))[\\s\\S]*$)"
"MAA Team":
  - '(?:[Aa]dd (?:`|)(?:MAA|maa)(?: |)[Tt]eam(?:`|))'
  - "(?:[Aa]dd (?:`|)(?:MAA|maa)(?: |)[Tt]eam(?:`|)|^(?![\\s\\S]*(?:\
  [Rr]emove (?:[Aa]ll labels|(?:`|)(?:MAA|maa)(?: |)[Tt]eam(?:`|))))[\\s\\S]*$)"
