namespace MAAUnified.Application.Models;

public static class UiErrorCode
{
    public const string AchievementServiceUnavailable = "AchievementServiceUnavailable";
    public const string AnnouncementServiceUnavailable = "AnnouncementServiceUnavailable";
    public const string AppRestartExecutableMissing = "AppRestartExecutableMissing";
    public const string AppRestartFailed = "AppRestartFailed";
    public const string AppRestartUnsupported = "AppRestartUnsupported";
    public const string AutostartQueryFailed = "AutostartQueryFailed";
    public const string CoreUnknown = "CoreUnknown";
    public const string ImportFailed = "ImportFailed";
    public const string InvalidWaitTime = "InvalidWaitTime";
    public const string LanguageNotSupported = "LanguageNotSupported";
    public const string LanguageSwitchFailed = "LanguageSwitchFailed";
    public const string HotkeyRegistrationFailed = "HotkeyRegistrationFailed";
    public const string HotkeyPersistenceFailed = "HotkeyPersistenceFailed";
    public const string NotificationProviderFailed = "NotificationProviderFailed";
    public const string OperationAlreadyRunning = "OperationAlreadyRunning";
    public const string OperationAlreadyStopped = "OperationAlreadyStopped";
    public const string PlatformOperationFailed = "PlatformOperationFailed";
    public const string ProfileMissing = "ProfileMissing";
    public const string RemoteControlConnectivityFailed = "RemoteControlConnectivityFailed";
    public const string SessionStateNotAllowed = "SessionStateNotAllowed";
    public const string SettingBatchEmpty = "SettingBatchEmpty";
    public const string SettingKeyMissing = "SettingKeyMissing";
    public const string SettingsSaveFailed = "SettingsSaveFailed";
    public const string StageManagerServiceUnavailable = "StageManagerServiceUnavailable";
    public const string TaskLoadFailed = "TaskLoadFailed";
    public const string TaskMoveOutOfRange = "TaskMoveOutOfRange";
    public const string TaskNameMissing = "TaskNameMissing";
    public const string TaskNotFound = "TaskNotFound";
    public const string TaskParamsMissing = "TaskParamsMissing";
    public const string TaskParamsCorrupted = "TaskParamsCorrupted";
    public const string TaskTypeMismatch = "TaskTypeMismatch";
    public const string TaskTypeMissing = "TaskTypeMissing";
    public const string TaskParamFlushFailed = "TaskParamFlushFailed";
    public const string ToolNotSupported = "ToolNotSupported";
    public const string ToolboxInvalidParameters = "ToolboxInvalidParameters";
    public const string ToolboxExecutionTimedOut = "ToolboxExecutionTimedOut";
    public const string ToolboxExecutionCancelled = "ToolboxExecutionCancelled";
    public const string ToolboxExecutionFailed = "ToolboxExecutionFailed";
    public const string ToolboxDisclaimerNotAccepted = "ToolboxDisclaimerNotAccepted";
    public const string UiError = "UiError";
    public const string UiOperationFailed = "UiOperationFailed";
    public const string UnknownTrayCommand = "UnknownTrayCommand";
    public const string VersionUpdateServiceUnavailable = "VersionUpdateServiceUnavailable";
    public const string WebApiDisabled = "WebApiDisabled";
    public const string WebApiServiceUnavailable = "WebApiServiceUnavailable";
    public const string TaskValidationFailed = "TaskValidationFailed";
    public const string TaskFieldTypeInvalid = "TaskFieldTypeInvalid";
    public const string DelimitedInputParseFailed = "DelimitedInputParseFailed";
    public const string TaskRuntimeCallbackError = "TaskRuntimeCallbackError";
    public const string TaskQueueEditBlocked = "TaskQueueEditBlocked";
    public const string BackgroundImagePathNotFound = "BackgroundImagePathNotFound";
    public const string EmulatorWaitSecondsOutOfRange = "EmulatorWaitSecondsOutOfRange";
    public const string EmulatorPathMissing = "EmulatorPathMissing";
    public const string EmulatorPathNotFound = "EmulatorPathNotFound";
    public const string TimerSlotCountMismatch = "TimerSlotCountMismatch";
    public const string TimerSlotIndexOutOfRange = "TimerSlotIndexOutOfRange";
    public const string TimerTimeInvalid = "TimerTimeInvalid";
    public const string TimerProfileMissing = "TimerProfileMissing";
    public const string TimerProfileNotFound = "TimerProfileNotFound";

    public const string CopilotFileMissing = "CopilotFileMissing";
    public const string CopilotFileNotFound = "CopilotFileNotFound";
    public const string CopilotFileReadFailed = "CopilotFileReadFailed";
    public const string CopilotClipboardEmpty = "CopilotClipboardEmpty";
    public const string CopilotPayloadInvalidJson = "CopilotPayloadInvalidJson";
    public const string CopilotPayloadInvalidType = "CopilotPayloadInvalidType";
    public const string CopilotPayloadMissingFields = "CopilotPayloadMissingFields";
    public const string CopilotPayloadEmptyArray = "CopilotPayloadEmptyArray";
    public const string CopilotIdMissing = "CopilotIdMissing";
    public const string CopilotSelectionMissing = "CopilotSelectionMissing";
    public const string CopilotListPersistenceFailed = "CopilotListPersistenceFailed";
    public const string ConfigurationProfileAlreadyExists = "ConfigurationProfileAlreadyExists";
    public const string ConfigurationProfileNotFound = "ConfigurationProfileNotFound";
    public const string ConfigurationProfileDeleteLastForbidden = "ConfigurationProfileDeleteLastForbidden";
    public const string ConfigurationProfileDeleteCurrentForbidden = "ConfigurationProfileDeleteCurrentForbidden";
    public const string ConfigurationProfileMoveOutOfRange = "ConfigurationProfileMoveOutOfRange";
    public const string ConfigurationProfileLoadFailed = "ConfigurationProfileLoadFailed";
    public const string ConfigurationProfileServiceUnavailable = "ConfigurationProfileServiceUnavailable";
    public const string ConfigurationProfileSaveFailed = "ConfigurationProfileSaveFailed";
    public const string ConfigurationProfileInvalidName = "ConfigurationProfileInvalidName";

    public const string PostActionLoadFailed = "PostActionLoadFailed";
    public const string PostActionSaveFailed = "PostActionSaveFailed";
    public const string PostActionLegacyParseFailed = "PostActionLegacyParseFailed";
    public const string PostActionSelectionInvalid = "PostActionSelectionInvalid";
    public const string PostActionExecutionFailed = "PostActionExecutionFailed";
    public const string PostActionUnsupported = "PostActionUnsupported";

    public const string InfrastPlanParseFailed = "InfrastPlanParseFailed";
    public const string InfrastPlanOutOfRange = "InfrastPlanOutOfRange";

    public const string RemoteControlInvalidParameters = "RemoteControlInvalidParameters";
    public const string RemoteControlNetworkFailure = "RemoteControlNetworkFailure";
    public const string RemoteControlUnsupported = "RemoteControlUnsupported";

    public const string NotificationProviderInvalidParameters = "NotificationProviderInvalidParameters";
    public const string NotificationProviderNetworkFailure = "NotificationProviderNetworkFailure";
    public const string NotificationProviderUnsupported = "NotificationProviderUnsupported";

    public const string MallCreditFightDowngraded = "MallCreditFightDowngraded";
    public const string VersionUpdateInvalidParameters = "VersionUpdateInvalidParameters";
    public const string VersionUpdateSaveFailed = "VersionUpdateSaveFailed";
    public const string IssueReportBundleBuildFailed = "IssueReportBundleBuildFailed";
    public const string IssueReportImageCacheClearFailed = "IssueReportImageCacheClearFailed";
    public const string ExternalTargetMissing = "ExternalTargetMissing";
    public const string ExternalTargetOpenFailed = "ExternalTargetOpenFailed";
    public const string AnnouncementStateInvalid = "AnnouncementStateInvalid";
    public const string WebApiPortConflict = "WebApiPortConflict";
    public const string WebApiLoadFailed = "WebApiLoadFailed";
    public const string StageManagerInvalidStageCode = "StageManagerInvalidStageCode";
}
