name: Bug Report (in English)
description: >-
  Recognition errors, operation abnormalities,
  connection errors, etc.
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before raising the issue...
      options:
      - label: >-
          I understand that Issues are for feedback and problem solving,
          not trolling the comments section, and will provide as
          much information as possible to help solve the problem.
        required: true
      - label: >-
          I filled in a short, clear title
          so that developers could quickly identify the general problem
          when going through the issue list.
          Instead of "Some suggestions", "Stuck", etc.
        required: true
      - label: >-
          I have checked the latest beta update and there is no mention
          of the bug being fixed.
        required: true
      - label: >-
          I have reviewed the pinned issues and confirmed that my issue
          is not mentioned.
        required: true
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Please provide a detailed description of your issue.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: >-
        Please provide the MAA version. Can be found in MAA -> Settings -> Update. (Click to copy)
      placeholder: |
        Resource Version:
        UI Version:
        Core Version:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: >-
        **Upload the `asst.log` and `gui.log` log file in the `debug` folder and**
        **indicate the approximate point in time when the problem occurred.**

        **Please drag and drop the full file in, not your own cuttings or copies;**
        **compress it before uploading if too large.**
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        If available, add screenshots to help explain your problem,
        including but not limited to screenshots of MAA software,
        screenshots of game screens.

        If the problem is **recognition related**, please help by providing
        the **original image** taken by the emulator's own screenshot tool
        (or via adb).

        Screenshots taken with other tools may contain the frames of the window/emulator, which makes it harder for us to debug.

        The `debug` folder has some automatic screenshots of the error images,
        if you have any,
        please upload them together.

    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anthing else?
      description: >-
        Emulator used, operating system, related configuration, links,
        reference material, etc.

        Anything that will give us more insight into the problem
        you are having.
    validations:
      required: false
