name: Feature Request (in English)
description: New features, suggestions, etc.
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: |
        Please ensure that you have completed the required items before checking the boxes.
        Issues with incomplete required items or with the 'I did not read carefully' option checked will be considered voluntary acceptance of direct closure.
      options:
        - label: I'm probably sure this is a new feature/suggestion and not a bug encountered (please attach logs if you're not sure).
          required: true
        - label: I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
          required: true
        - label: I am using the latest version of the current update version, and have reviewed the [update content](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commits/dev/) released to date, [Pull Requests](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pulls) unreleased update content and there is no mention of this feature/suggestion being added.
          required: true
        - label: I have checked all the options without carefully reading the content and believe this will not affect issue resolution.
          required: false
        - label: I have reviewed the [FAQs](https://maa.plus/docs/en-us/manual/faq.html), [Announcement](/MaaAssistantArknights/MaaAssistantArknights/issues/7732), [Open Issues](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues), [Closed Issues](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aissue%20state%3Aclosed) to ensure that my feature/suggestion has not been mentioned.
          required: true
  - type: textarea
    id: describe
    attributes:
      label: The problems you have encountered?
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Any good ideas?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional
      description: Any other background, screen shots, etc.
    validations:
      required: false
