name: Others (in English)
description: Ask a question rather than a bug report or feature request.
labels: ["question"]
body:
  - type: textarea
    id: describe
    attributes:
      label: The problems you have encountered?
    validations:
      required: false
