name: バグ報告（日本語）
description: 認識エラー、操作異常、接続エラーなど
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: |
        以下の必須項目を完了してからチェックを入れてください。
        必須項目が完了していない、または「内容を注意深く読んでいない」オプションがチェックされている場合、Issue が直接クローズされる可能性があります。
      options:
        - label: Issue はフィードバックと問題解決のためのものであり、コメント欄で不満を言う場ではないことを理解しており、問題解決に役立つ情報をできる限り提供します。
          required: true
        - label: 開発者が Issue リストを確認する際に問題をすぐに把握できるよう、簡潔で明確なタイトルを記入しました。「提案」「止まった」などではありません。
          required: true
        - label: 現在の更新バージョンの最新版を使用しており、リリースされた[更新内容](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commits/dev/)、[Pull Requests](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pulls)の未リリースの更新内容を確認し、このバグが修正されたという記載がないことを確認しました。
          required: true
        - label: 内容を注意深く読まずにすべてのオプションをチェックしましたが、これが Issue の処理に影響しないと信じています。
          required: false
        - label: '[FAQ](https://docs.maa.plus/ja-jp/manual/faq.html)、[お知らせ](/MaaAssistantArknights/MaaAssistantArknights/issues/7732)、[アクティブな Issue](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues)、[クローズ済み Issue](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aissue%20state%3Aclosed)を確認し、私の問題が言及されていないことを確認しました。'
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 問題の説明
      description: 問題をできるだけ詳しく説明してください。
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        MAA のバージョンを提供してください。MAA -> 設定 -> ソフトウェア更新で確認できます。クリックでコピーできます。
        `リソースバージョン` と `MAA バージョン` をそれぞれクリックして貼り付けてください。最終的に5行のバージョン情報が必要です。
      placeholder: |
        Resource Version:
        MAA Version:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: ログと設定ファイル
      description: |
        **MAA -> 設定 -> 問題報告 の「ログ圧縮ファイル生成」ボタンをクリックして、圧縮ファイルをアップロードしてください**
        **アップロードする圧縮ファイルが 25MB を超える場合は、同じ日付フォルダ内の小さな圧縮ファイルをアップロードしてください**
        macOS をご使用の場合は、画面左上の「ファイル」をクリックし、「ログフォルダを開く」をクリックしてください。
      placeholder: |
        ファイルをアップロードする前に MAA が閉じていることを確認してください。
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: 設定情報
      description: |
        OS とバージョン、エミュレータのブランド、エミュレータの解像度、DPI、フレームレートを記載してください；
        MuMu または LDPlayer 9 をご使用の場合は、スクリーンショット強化機能が有効かどうかを記載してください；
        最後に、GPU アクセラレーション推論が有効かどうかを記載し、有効な場合は GPU モデルを提供してください。
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショットまたは録画
      description: |
        `debug` ディレクトリ内の機能別フォルダには、自動キャプチャされたエラー画像があります。
        関連するものがあれば、一緒にアップロードしてください。

        問題の説明に役立つスクリーンショットや録画をアップロードしてください。
        MAA ソフトウェアのスクリーンショット、ゲーム画面のスクリーンショットなど。

        **認識関連の問題**の場合は、エミュレータ内蔵のスクリーンショットツール
        （または adb 経由）で撮影した**オリジナル画像**を提供してください。

        他のツール（QQ/WeChat など）で撮影したスクリーンショットには
        ウィンドウの枠が含まれ、アスペクト比や解像度が一定でないため、
        デバッグが困難になります。

        ファイルサイズが大きすぎる場合は、圧縮してからアップロードしてください。
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: その他
      description: |
        あなたが遭遇している問題について、より深く理解するのに役立つ情報があれば記載してください。
    validations:
      required: false
