name: 버그 리포트 (한국어)
description: 인식 오류, 작동 이상, 연결 오류 등
labels: ["bug"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: |
        체크하기 전에 아래 필수 항목을 완료했는지 확인해 주세요.
        필수 항목이 완료되지 않았거나 '내용을 자세히 읽지 않음' 옵션이 체크된 경우 Issue가 바로 닫힐 수 있습니다.
      options:
        - label: Issue는 피드백과 문제 해결을 위한 것이며, 댓글란에서 불만을 토로하는 곳이 아님을 이해하며, 문제 해결에 도움이 되는 정보를 최대한 제공하겠습니다.
          required: true
        - label: 개발자가 Issue 목록을 확인할 때 문제를 빠르게 파악할 수 있도록 짧고 명확한 제목을 작성했습니다. "제안", "멈춤" 등이 아닙니다.
          required: true
        - label: 현재 업데이트 버전의 최신 버전을 사용하고 있으며, 릴리스된 [업데이트 내용](https://github.com/MaaAssistantArknights/MaaAssistantArknights/commits/dev/), [Pull Requests](https://github.com/MaaAssistantArknights/MaaAssistantArknights/pulls)의 미출시 업데이트 내용을 확인하여 이 버그가 수정되었다는 언급이 없음을 확인했습니다.
          required: true
        - label: 내용을 자세히 읽지 않고 모든 옵션을 체크했지만, 이것이 Issue 처리에 영향을 미치지 않을 것이라고 믿습니다.
          required: false
        - label: '[FAQ](https://docs.maa.plus/ko-kr/manual/faq.html), [공지사항](/MaaAssistantArknights/MaaAssistantArknights/issues/7732), [활성 Issue](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues), [닫힌 Issue](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aissue%20state%3Aclosed)를 확인하여 제 문제가 언급되지 않았음을 확인했습니다.'
          required: true
  - type: textarea
    id: describe
    attributes:
      label: 문제 설명
      description: 문제를 최대한 자세히 설명해 주세요.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        MAA 버전을 제공해 주세요. MAA -> 설정 -> 소프트웨어 업데이트에서 확인할 수 있습니다. 클릭하면 복사됩니다.
        `리소스 버전`과 `MAA 버전`을 각각 클릭하여 붙여넣어 주세요. 최종적으로 5줄의 버전 정보가 필요합니다.
      placeholder: |
        Resource Version:
        MAA Version:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 로그 및 설정 파일
      description: |
        **MAA -> 설정 -> 문제 보고에서 '로그 압축 파일 생성' 버튼을 클릭하고 압축 파일을 업로드해 주세요**
        **업로드할 압축 파일이 25MB를 초과하면, 같은 날짜 폴더 내의 작은 압축 파일들을 대신 업로드해 주세요**
        macOS를 사용하는 경우, 화면 왼쪽 상단의 "파일"을 클릭한 후 "로그 폴더 열기"를 클릭해 주세요.
      placeholder: |
        파일을 업로드하기 전에 MAA가 닫혀 있는지 확인해 주세요.
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: 설정 정보
      description: |
        운영 체제 및 버전, 에뮬레이터 브랜드, 에뮬레이터 해상도, DPI, 프레임 레이트를 명시해 주세요;
        MuMu 또는 LDPlayer 9을 사용하는 경우, 스크린샷 향상 기능이 활성화되어 있는지 명시해 주세요;
        마지막으로, GPU 가속 추론이 활성화되어 있는지 명시하고, 활성화된 경우 GPU 모델을 제공해 주세요.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷 또는 녹화
      description: |
        `debug` 디렉토리 내의 기능별 폴더에는 자동으로 캡처된 오류 이미지가 있습니다.
        관련된 것이 있다면 함께 업로드해 주세요.

        문제 설명에 도움이 되는 스크린샷이나 녹화를 업로드해 주세요.
        MAA 소프트웨어 스크린샷, 게임 화면 스크린샷 등을 포함합니다.

        **인식 관련 문제**의 경우, 에뮬레이터 내장 스크린샷 도구
        (또는 adb를 통해)로 촬영한 **원본 이미지**를 제공해 주세요.

        다른 도구(QQ/WeChat 등)로 촬영한 스크린샷에는
        창 테두리가 포함되어 있고 화면 비율과 해상도가 일정하지 않아
        디버깅이 어려워집니다.

        파일 크기가 너무 큰 경우, 압축 후 업로드해 주세요.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 기타
      description: |
        겪고 있는 문제에 대해 더 잘 이해하는 데 도움이 되는 정보가 있다면 기재해 주세요.
    validations:
      required: false
