using MAAUnified.App.ViewModels.Infrastructure;
using MAAUnified.Application.Services.Localization;

namespace MAAUnified.App.ViewModels.TaskQueue;

public sealed class LocalizedTextMap : ObservableObject
{
    private static readonly Dictionary<string, string> ZhCn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "基建",
        ["Infrast.Mode"] = "基建模式",
        ["Infrast.Mode.Normal"] = "默认排班",
        ["Infrast.Mode.Custom"] = "自定义排班",
        ["Infrast.Mode.Rotation"] = "轮换排班",
        ["Infrast.Drones"] = "无人机策略",
        ["Infrast.Threshold"] = "宿舍阈值(%)",
        ["Infrast.File"] = "自定义基建文件",
        ["Infrast.Plan"] = "计划索引",
        ["Infrast.Plan.Auto"] = "自动(按时间轮换)",
        ["Infrast.Plan.Refresh"] = "刷新计划",
        ["Infrast.Plan.DefaultName"] = "计划 {0}",
        ["Infrast.Plan.Display"] = "{0}（{1} 个时段）",
        ["Infrast.Facility"] = "房间顺序",
        ["Infrast.SelectAll"] = "全选",
        ["Infrast.Clear"] = "清空",
        ["Infrast.Advanced"] = "高级选项",
        ["Infrast.Trust"] = "宿舍信赖收取",
        ["Infrast.NotStationed"] = "过滤未入驻干员",
        ["Infrast.ContinueTraining"] = "保留训练进度",
        ["Infrast.Replenish"] = "搓玉补货",
        ["Infrast.ReceptionBoard"] = "会客室板子领取",
        ["Infrast.ReceptionExchange"] = "线索交换",
        ["Infrast.ReceptionSend"] = "赠送线索",
        ["Infrast.Error.CustomFileNotFound"] = "自定义文件不存在：{0}",
        ["Infrast.Error.PlanOutOfRange"] = "计划索引 {0} 超出 `{1}` 范围。",
        ["Infrast.Error.ParseFailed"] = "解析自定义基建文件失败。",
        ["Infrast.Status.LoadedPlans"] = "已加载 {0} 个计划。",
        ["Mall.Title"] = "商店",
        ["Mall.VisitFriends"] = "访问好友",
        ["Mall.VisitOnce"] = "好友访问每日一次",
        ["Mall.CreditFight"] = "信用作战",
        ["Mall.CreditFightOnce"] = "信用作战每日一次",
        ["Mall.Formation"] = "编队",
        ["Mall.Shopping"] = "信用购物",
        ["Mall.BuyFirst"] = "高优先列表(分号分隔)",
        ["Mall.Blacklist"] = "黑名单(分号分隔)",
        ["Mall.ForceShopping"] = "信用满时强制购物",
        ["Mall.OnlyDiscount"] = "仅买折扣",
        ["Mall.Reserve"] = "保留 300 信用",
        ["Award.Title"] = "奖励",
        ["Award.Award"] = "日常/周常奖励",
        ["Award.Mail"] = "邮件奖励",
        ["Award.Recruit"] = "免费单抽",
        ["Award.RecruitTip"] = "开启免费单抽前需要确认",
        ["Award.Confirm"] = "确认开启",
        ["Award.Cancel"] = "取消",
        ["Award.Orundum"] = "合成玉领取",
        ["Award.Mining"] = "矿区奖励领取",
        ["Award.Special"] = "特别授权领取",
        ["PostAction.Title"] = "后置动作",
        ["PostAction.Once"] = "一次性(本轮生效)",
        ["PostAction.BackToHome"] = "返回模拟器首页",
        ["PostAction.ExitArknights"] = "退出游戏",
        ["PostAction.ExitEmulator"] = "关闭模拟器",
        ["PostAction.ExitSelf"] = "关闭 MAA",
        ["PostAction.IfNoOther"] = "仅无其他 MAA 时执行",
        ["PostAction.Sleep"] = "睡眠",
        ["PostAction.Hibernate"] = "休眠",
        ["PostAction.Shutdown"] = "关机",
        ["PostAction.Clear"] = "清空动作",
        ["PostAction.Unsupported"] = "该动作当前平台不支持，将降级为日志记录。",
        ["PostAction.Cmd.ExitArknights"] = "退出游戏命令",
        ["PostAction.Cmd.BackToHome"] = "返回首页命令",
        ["PostAction.Cmd.ExitEmulator"] = "关闭模拟器命令",
        ["PostAction.Cmd.ExitSelf"] = "关闭 MAA 命令",
        ["PostAction.Cmd.Watermark"] = "留空则仅记录降级日志",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "“仅无其他 MAA 时执行”需要至少勾选一个系统动作（睡眠/休眠/关机）。",
        ["PostAction.Warn.UnsupportedDowngrade"] = "当前选择包含不可执行动作，将降级为日志记录。",
        ["StartUp.Title"] = "开始唤醒",
        ["StartUp.AccountName"] = "账号",
        ["StartUp.ClientType"] = "客户端",
        ["StartUp.StartGameEnabled"] = "自动启动游戏",
        ["StartUp.ConnectConfig"] = "连接预设",
        ["StartUp.ConnectAddress"] = "连接地址",
        ["StartUp.AdbPath"] = "ADB 路径",
        ["StartUp.TouchMode"] = "触控模式",
        ["StartUp.AutoDetect"] = "自动检测连接",
        ["StartUp.AttachScreencap"] = "AttachWindow-截图",
        ["StartUp.AttachMouse"] = "AttachWindow-触控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-键盘",
        ["Fight.Title"] = "战斗",
        ["Fight.Stage"] = "关卡",
        ["Fight.UseMedicine"] = "使用理智药",
        ["Fight.Medicine"] = "理智药数量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石数量",
        ["Fight.EnableTimesLimit"] = "限制次数",
        ["Fight.Times"] = "次数",
        ["Fight.Series"] = "连战",
        ["Fight.UseExpiringMedicine"] = "使用即将过期理智药",
        ["Fight.DrGrandet"] = "理智策略 DrGrandet",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目标数量",
        ["Fight.UseAlternateStage"] = "启用换图",
        ["Fight.HideUnavailableStage"] = "隐藏不可用关卡",
        ["Fight.StageResetMode"] = "换日重置模式",
        ["Fight.UseCustomAnnihilation"] = "自定义剿灭",
        ["Fight.AnnihilationStage"] = "剿灭关卡",
        ["Recruit.Title"] = "公开招募",
        ["Recruit.Times"] = "招募次数",
        ["Recruit.Refresh"] = "自动刷新",
        ["Recruit.ForceRefresh"] = "强制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.SkipRobot"] = "跳过支援机械",
        ["Recruit.ChooseLevel3"] = "选择 3 星",
        ["Recruit.ChooseLevel4"] = "选择 4 星",
        ["Recruit.ChooseLevel5"] = "选择 5 星",
        ["Recruit.SetTime"] = "设置时长",
        ["Recruit.Level3Time"] = "3 星时长",
        ["Recruit.Level4Time"] = "4 星时长",
        ["Recruit.Level5Time"] = "5 星时长",
        ["Recruit.ExtraTagsMode"] = "额外标签策略",
        ["Recruit.FirstTags"] = "优先标签",
        ["Roguelike.Title"] = "肉鸽",
        ["Roguelike.Theme"] = "主题",
        ["Roguelike.Mode"] = "模式",
        ["Roguelike.Difficulty"] = "难度",
        ["Roguelike.StartsCount"] = "开局次数",
        ["Roguelike.Squad"] = "开局分队",
        ["Roguelike.Roles"] = "开局职业",
        ["Roguelike.CoreChar"] = "核心干员",
        ["Roguelike.InvestmentEnabled"] = "启用投资",
        ["Roguelike.InvestmentWithMoreScore"] = "投资优先分数",
        ["Roguelike.InvestmentsCount"] = "投资次数上限",
        ["Roguelike.StopWhenInvestmentFull"] = "投资满时停止",
        ["Roguelike.UseSupport"] = "使用助战",
        ["Roguelike.UseNonfriendSupport"] = "使用非好友助战",
        ["Roguelike.RefreshTraderWithDice"] = "使用骰子刷新商人",
        ["Roguelike.StopAtFinalBoss"] = "终局停下",
        ["Roguelike.StopAtMaxLevel"] = "满级停下",
        ["Roguelike.CollectibleModeShopping"] = "收藏品模式购物",
        ["Roguelike.CollectibleModeSquad"] = "收藏品模式分队",
        ["Roguelike.StartWithEliteTwo"] = "开局精二",
        ["Roguelike.OnlyStartWithEliteTwo"] = "仅开局精二",
        ["Roguelike.Collectible.HotWater"] = "热水壶",
        ["Roguelike.Collectible.Shield"] = "护盾",
        ["Roguelike.Collectible.Ingot"] = "源石锭",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "随机",
        ["Roguelike.Collectible.Key"] = "钥匙",
        ["Roguelike.Collectible.Dice"] = "骰子",
        ["Roguelike.Collectible.Ideas"] = "构想",
        ["Roguelike.Collectible.Ticket"] = "票券",
        ["Roguelike.MonthlySquadAutoIterate"] = "月度小队自动迭代",
        ["Roguelike.MonthlySquadCheckComms"] = "月度小队检测通讯",
        ["Roguelike.DeepExplorationAutoIterate"] = "深度探索自动迭代",
        ["Roguelike.FindPlayTimeTarget"] = "定向游玩目标",
        ["Roguelike.FirstFloorFoldartal"] = "首层折纸",
        ["Roguelike.StartFoldartalList"] = "起始折纸列表",
        ["Roguelike.ExpectedCollapsalParadigms"] = "期望坍缩范式",
        ["Roguelike.StartWithSeed"] = "指定种子",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "主题",
        ["Reclamation.Mode"] = "模式",
        ["Reclamation.IncrementMode"] = "增量模式",
        ["Reclamation.NumCraftBatches"] = "回合合成批次",
        ["Reclamation.ToolsToCraft"] = "合成工具列表",
        ["Reclamation.ClearStore"] = "清仓",
        ["Custom.Title"] = "自定义任务",
        ["Custom.TaskNames"] = "任务名列表",
        ["Custom.TaskNamesPreview"] = "格式化预览",
        ["Common.LoadingTaskHint"] = "请先在左侧任务列表中选择对应任务。",
        ["Common.ValidationIssues"] = "校验信息",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "错误",
        ["TaskQueue.DailyStageHintDefault"] = "今日关卡信息将在资源加载后展示。",
        ["TaskQueue.OverlayDisconnected"] = "Overlay 未连接",
        ["TaskQueue.Error.SelectTaskToRemove"] = "请先选择要删除的任务。",
        ["TaskQueue.Error.SelectTaskToRename"] = "请先选择要重命名的任务。",
        ["TaskQueue.Error.SelectTaskToMove"] = "请先选择要移动的任务。",
        ["TaskQueue.Error.EditBlockedWhileRunning"] = "运行中禁止编辑任务队列。",
        ["TaskQueue.Validation.Clean"] = "校验通过。",
        ["TaskQueue.Validation.WarningCount"] = "存在 {0} 条预警。",
        ["TaskQueue.Validation.BlockingCount"] = "存在 {0} 条阻断错误。",
        ["TaskQueue.Validation.LoadFailed"] = "读取校验报告失败。",
        ["TaskQueue.Error.BlockingValidation"] = "任务 `{0}` 存在阻断校验项：{1}",
        ["Issue.ClientTypeMissing"] = "客户端类型不能为空。",
        ["Issue.FightStageMissing"] = "战斗关卡不能为空。",
        ["Issue.FightSeriesOutOfRange"] = "连战范围应在 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "战斗次数不能小于 0。",
        ["Issue.FightDropMissing"] = "指定掉落时必须填写掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "当前次数与连战设置可能无法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次数不能小于 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募时长需在 60..540 且步长为 10。",
        ["Issue.TaskFieldMissing"] = "配置缺少必填字段。",
        ["Issue.TaskFieldTypeInvalid"] = "字段类型不正确，无法解析。",
        ["Issue.DelimitedInputParseFailed"] = "输入看起来像结构化数据，请改用逗号/分号/换行分隔的纯文本。",
        ["Issue.RoguelikeModeInvalid"] = "肉鸽模式不受支持。",
        ["Issue.RoguelikeThemeUnknown"] = "未知主题，已降级为 JieGarden。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "难度不能小于 0，已自动修正。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "开局次数不能小于 0，已自动修正。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投资次数不能小于 0，已自动修正。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "仅 Mizuki 主题支持骰子刷新商人，已自动关闭。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime 仅支持 JieGarden 主题，已自动降级。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目标范围应为 1..3，已自动修正。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "当前模式/主题/分队不支持开局精二，已自动关闭。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "仅开局精二依赖开局精二开关，已自动关闭。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "助战与开局精二冲突，已自动关闭开局精二。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "种子格式非法，应为 `<字母数字>,rogue_<id>,<step>`。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "起始折纸列表超过 3 项，已截断。",
        ["Issue.ReclamationThemeUnknown"] = "生息主题未知，已降级为 Tales。",
        ["Issue.ReclamationModeInvalid"] = "生息模式不受支持。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "增量模式仅支持 0/1，已自动修正。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "单次组装轮数应在 1..99999，已自动修正。",
        ["Issue.ReclamationToolNameInvalid"] = "工具列表包含无法解析的结构化内容。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "无存档模式会忽略工具列表，已清空。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存档模式会忽略清仓，已关闭。",
        ["Issue.CustomTaskNamesEmpty"] = "自定义任务名列表为空。",
        ["Issue.CustomTaskNameInvalid"] = "自定义任务名包含无法解析的结构化内容。",
        ["Issue.CustomTaskNameUnknown"] = "自定义任务名未识别，请确认拼写。",
        ["Issue.CustomTaskNamesNormalized"] = "自定义任务名已完成标准化和去重。",
    };

    private static readonly Dictionary<string, string> EnUs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "Infrast",
        ["Infrast.Mode"] = "Mode",
        ["Infrast.Mode.Normal"] = "Default",
        ["Infrast.Mode.Custom"] = "Custom",
        ["Infrast.Mode.Rotation"] = "Rotation",
        ["Infrast.Drones"] = "Drones",
        ["Infrast.Threshold"] = "Dorm Threshold(%)",
        ["Infrast.File"] = "Custom Infrast File",
        ["Infrast.Plan"] = "Plan Index",
        ["Infrast.Plan.Auto"] = "Auto by time",
        ["Infrast.Plan.Refresh"] = "Reload Plans",
        ["Infrast.Plan.DefaultName"] = "Plan {0}",
        ["Infrast.Plan.Display"] = "{0} ({1} period)",
        ["Infrast.Facility"] = "Facility Order",
        ["Infrast.SelectAll"] = "Select All",
        ["Infrast.Clear"] = "Clear",
        ["Infrast.Advanced"] = "Advanced",
        ["Infrast.Trust"] = "Dorm trust",
        ["Infrast.NotStationed"] = "Filter stationed operators",
        ["Infrast.ContinueTraining"] = "Continue training",
        ["Infrast.Replenish"] = "Originium replenish",
        ["Infrast.ReceptionBoard"] = "Reception board",
        ["Infrast.ReceptionExchange"] = "Clue exchange",
        ["Infrast.ReceptionSend"] = "Send clue",
        ["Infrast.Error.CustomFileNotFound"] = "Custom file not found: {0}",
        ["Infrast.Error.PlanOutOfRange"] = "Plan index {0} is out of range for `{1}`.",
        ["Infrast.Error.ParseFailed"] = "Failed to parse custom infrast file.",
        ["Infrast.Status.LoadedPlans"] = "Loaded {0} plans.",
        ["Mall.Title"] = "Mall",
        ["Mall.VisitFriends"] = "Visit friends",
        ["Mall.VisitOnce"] = "Visit friends once a day",
        ["Mall.CreditFight"] = "Credit fight",
        ["Mall.CreditFightOnce"] = "Credit fight once a day",
        ["Mall.Formation"] = "Formation",
        ["Mall.Shopping"] = "Credit shopping",
        ["Mall.BuyFirst"] = "Buy-first list (semicolon separated)",
        ["Mall.Blacklist"] = "Blacklist (semicolon separated)",
        ["Mall.ForceShopping"] = "Force shopping when full",
        ["Mall.OnlyDiscount"] = "Discount only",
        ["Mall.Reserve"] = "Reserve 300 credits",
        ["Award.Title"] = "Award",
        ["Award.Award"] = "Daily/weekly rewards",
        ["Award.Mail"] = "Mail rewards",
        ["Award.Recruit"] = "Free gacha",
        ["Award.RecruitTip"] = "Confirmation required before enabling free gacha",
        ["Award.Confirm"] = "Confirm",
        ["Award.Cancel"] = "Cancel",
        ["Award.Orundum"] = "Orundum",
        ["Award.Mining"] = "Mining rewards",
        ["Award.Special"] = "Special access",
        ["PostAction.Title"] = "Post Action",
        ["PostAction.Once"] = "Once for current run",
        ["PostAction.BackToHome"] = "Back to emulator home",
        ["PostAction.ExitArknights"] = "Exit Arknights",
        ["PostAction.ExitEmulator"] = "Exit emulator",
        ["PostAction.ExitSelf"] = "Exit MAA",
        ["PostAction.IfNoOther"] = "Only if no other MAA",
        ["PostAction.Sleep"] = "Sleep",
        ["PostAction.Hibernate"] = "Hibernate",
        ["PostAction.Shutdown"] = "Shutdown",
        ["PostAction.Clear"] = "Clear",
        ["PostAction.Unsupported"] = "This action is unsupported on current platform and will be downgraded to logging.",
        ["PostAction.Cmd.ExitArknights"] = "Exit Arknights command",
        ["PostAction.Cmd.BackToHome"] = "Back to home command",
        ["PostAction.Cmd.ExitEmulator"] = "Exit emulator command",
        ["PostAction.Cmd.ExitSelf"] = "Exit MAA command",
        ["PostAction.Cmd.Watermark"] = "Leave empty to downgrade to logging only",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "`IfNoOtherMaa` requires at least one system action (Sleep/Hibernate/Shutdown).",
        ["PostAction.Warn.UnsupportedDowngrade"] = "Some selected post actions are not executable and will be downgraded to logging.",
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "Account",
        ["StartUp.ClientType"] = "Client Type",
        ["StartUp.StartGameEnabled"] = "Start game automatically",
        ["StartUp.ConnectConfig"] = "Connect preset",
        ["StartUp.ConnectAddress"] = "Connect address",
        ["StartUp.AdbPath"] = "ADB path",
        ["StartUp.TouchMode"] = "Touch mode",
        ["StartUp.AutoDetect"] = "Auto detect",
        ["StartUp.AttachScreencap"] = "AttachWindow - Screenshot",
        ["StartUp.AttachMouse"] = "AttachWindow - Touch",
        ["StartUp.AttachKeyboard"] = "AttachWindow - Keyboard",
        ["Fight.Title"] = "Fight",
        ["Fight.Stage"] = "Stage",
        ["Fight.UseMedicine"] = "Use medicine",
        ["Fight.Medicine"] = "Medicine",
        ["Fight.UseStone"] = "Use stone",
        ["Fight.Stone"] = "Stone",
        ["Fight.EnableTimesLimit"] = "Enable times limit",
        ["Fight.Times"] = "Times",
        ["Fight.Series"] = "Series",
        ["Fight.UseExpiringMedicine"] = "Use expiring medicine",
        ["Fight.DrGrandet"] = "DrGrandet mode",
        ["Fight.EnableTargetDrop"] = "Target drop",
        ["Fight.DropId"] = "Drop ID",
        ["Fight.DropCount"] = "Drop count",
        ["Fight.UseAlternateStage"] = "Use alternate stage",
        ["Fight.HideUnavailableStage"] = "Hide unavailable stages",
        ["Fight.StageResetMode"] = "Stage reset mode",
        ["Fight.UseCustomAnnihilation"] = "Custom annihilation",
        ["Fight.AnnihilationStage"] = "Annihilation stage",
        ["Recruit.Title"] = "Recruit",
        ["Recruit.Times"] = "Times",
        ["Recruit.Refresh"] = "Refresh",
        ["Recruit.ForceRefresh"] = "Force refresh",
        ["Recruit.UseExpedited"] = "Use expedited",
        ["Recruit.SkipRobot"] = "Skip robot",
        ["Recruit.ChooseLevel3"] = "Choose 3-star",
        ["Recruit.ChooseLevel4"] = "Choose 4-star",
        ["Recruit.ChooseLevel5"] = "Choose 5-star",
        ["Recruit.SetTime"] = "Set time",
        ["Recruit.Level3Time"] = "3-star time",
        ["Recruit.Level4Time"] = "4-star time",
        ["Recruit.Level5Time"] = "5-star time",
        ["Recruit.ExtraTagsMode"] = "Extra tags mode",
        ["Recruit.FirstTags"] = "First tags",
        ["Roguelike.Title"] = "Roguelike",
        ["Roguelike.Theme"] = "Theme",
        ["Roguelike.Mode"] = "Mode",
        ["Roguelike.Difficulty"] = "Difficulty",
        ["Roguelike.StartsCount"] = "Starts count",
        ["Roguelike.Squad"] = "Squad",
        ["Roguelike.Roles"] = "Roles",
        ["Roguelike.CoreChar"] = "Core operator",
        ["Roguelike.InvestmentEnabled"] = "Enable investment",
        ["Roguelike.InvestmentWithMoreScore"] = "Investment for score",
        ["Roguelike.InvestmentsCount"] = "Investment count",
        ["Roguelike.StopWhenInvestmentFull"] = "Stop on investment full",
        ["Roguelike.UseSupport"] = "Use support",
        ["Roguelike.UseNonfriendSupport"] = "Use non-friend support",
        ["Roguelike.RefreshTraderWithDice"] = "Refresh trader with dice",
        ["Roguelike.StopAtFinalBoss"] = "Stop at final boss",
        ["Roguelike.StopAtMaxLevel"] = "Stop at max level",
        ["Roguelike.CollectibleModeShopping"] = "Collectible shopping",
        ["Roguelike.CollectibleModeSquad"] = "Collectible squad",
        ["Roguelike.StartWithEliteTwo"] = "Start with E2",
        ["Roguelike.OnlyStartWithEliteTwo"] = "Only start with E2",
        ["Roguelike.Collectible.HotWater"] = "Hot water",
        ["Roguelike.Collectible.Shield"] = "Shield",
        ["Roguelike.Collectible.Ingot"] = "Ingot",
        ["Roguelike.Collectible.Hope"] = "Hope",
        ["Roguelike.Collectible.Random"] = "Random",
        ["Roguelike.Collectible.Key"] = "Key",
        ["Roguelike.Collectible.Dice"] = "Dice",
        ["Roguelike.Collectible.Ideas"] = "Ideas",
        ["Roguelike.Collectible.Ticket"] = "Ticket",
        ["Roguelike.MonthlySquadAutoIterate"] = "Monthly squad iterate",
        ["Roguelike.MonthlySquadCheckComms"] = "Monthly squad check comms",
        ["Roguelike.DeepExplorationAutoIterate"] = "Deep exploration iterate",
        ["Roguelike.FindPlayTimeTarget"] = "Find play time target",
        ["Roguelike.FirstFloorFoldartal"] = "First floor foldartal",
        ["Roguelike.StartFoldartalList"] = "Start foldartal list",
        ["Roguelike.ExpectedCollapsalParadigms"] = "Expected collapsal paradigms",
        ["Roguelike.StartWithSeed"] = "Start with seed",
        ["Reclamation.Title"] = "Reclamation",
        ["Reclamation.Theme"] = "Theme",
        ["Reclamation.Mode"] = "Mode",
        ["Reclamation.IncrementMode"] = "Increment mode",
        ["Reclamation.NumCraftBatches"] = "Craft batches",
        ["Reclamation.ToolsToCraft"] = "Tools to craft",
        ["Reclamation.ClearStore"] = "Clear store",
        ["Custom.Title"] = "Custom",
        ["Custom.TaskNames"] = "Task names",
        ["Custom.TaskNamesPreview"] = "Preview",
        ["Common.LoadingTaskHint"] = "Select a task from the left list first.",
        ["Common.ValidationIssues"] = "Validation Issues",
        ["Common.WarningPrefix"] = "Warning",
        ["Common.ErrorPrefix"] = "Error",
        ["TaskQueue.DailyStageHintDefault"] = "Daily stage hints will be shown after resources are loaded.",
        ["TaskQueue.OverlayDisconnected"] = "Overlay disconnected",
        ["TaskQueue.Error.SelectTaskToRemove"] = "Select a task to remove first.",
        ["TaskQueue.Error.SelectTaskToRename"] = "Select a task to rename first.",
        ["TaskQueue.Error.SelectTaskToMove"] = "Select a task to move first.",
        ["TaskQueue.Error.EditBlockedWhileRunning"] = "Task queue editing is blocked while running.",
        ["TaskQueue.Validation.Clean"] = "Validation passed.",
        ["TaskQueue.Validation.WarningCount"] = "{0} warning issue(s).",
        ["TaskQueue.Validation.BlockingCount"] = "{0} blocking issue(s).",
        ["TaskQueue.Validation.LoadFailed"] = "Failed to load validation report.",
        ["TaskQueue.Error.BlockingValidation"] = "Task `{0}` blocked by validation: {1}",
        ["Issue.ClientTypeMissing"] = "Client type cannot be empty.",
        ["Issue.FightStageMissing"] = "Fight stage cannot be empty.",
        ["Issue.FightSeriesOutOfRange"] = "Fight series must be between -1 and 6.",
        ["Issue.FightTimesOutOfRange"] = "Fight times must be greater than or equal to zero.",
        ["Issue.FightDropMissing"] = "Drop id is required when target drop is enabled.",
        ["Issue.FightTimesMayNotExhausted"] = "Times may not be fully exhausted under current series.",
        ["Issue.RecruitTimesOutOfRange"] = "Recruit times must be greater than or equal to zero.",
        ["Issue.RecruitTimeOutOfRange"] = "Recruit time must be 60..540 with 10-minute steps.",
        ["Issue.TaskFieldMissing"] = "Required field is missing in config.",
        ["Issue.TaskFieldTypeInvalid"] = "Field type is invalid and cannot be parsed.",
        ["Issue.DelimitedInputParseFailed"] = "Input looks structured. Use plain delimiter-separated text.",
        ["Issue.RoguelikeModeInvalid"] = "Roguelike mode is not supported.",
        ["Issue.RoguelikeThemeUnknown"] = "Unknown roguelike theme, fallback to JieGarden.",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "Difficulty must be >= 0 and was normalized.",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "Starts count must be >= 0 and was normalized.",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "Investments count must be >= 0 and was normalized.",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "Refresh trader with dice only works on Mizuki; auto-disabled.",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime requires JieGarden; fallback applied.",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime target must be in 1..3 and was normalized.",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "StartWithEliteTwo is invalid for current mode/theme/squad and was disabled.",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "OnlyStartWithEliteTwo requires StartWithEliteTwo; auto-disabled.",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "UseSupport conflicts with StartWithEliteTwo; elite-two start was disabled.",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "Seed format is invalid. Expected `<alnum>,rogue_<id>,<step>`.",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "Start foldartal list exceeded 3 items and was trimmed.",
        ["Issue.ReclamationThemeUnknown"] = "Unknown reclamation theme, fallback to Tales.",
        ["Issue.ReclamationModeInvalid"] = "Reclamation mode is not supported.",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "Increment mode must be 0 or 1 and was normalized.",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "NumCraftBatches must be in 1..99999 and was normalized.",
        ["Issue.ReclamationToolNameInvalid"] = "ToolsToCraft contains unparseable structured tokens.",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "ToolsToCraft is ignored in no-archive mode and was cleared.",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "ClearStore is ignored in archive mode and was disabled.",
        ["Issue.CustomTaskNamesEmpty"] = "Custom task names list is empty.",
        ["Issue.CustomTaskNameInvalid"] = "Custom task name contains unparseable structured tokens.",
        ["Issue.CustomTaskNameUnknown"] = "Custom task name is not recognized.",
        ["Issue.CustomTaskNamesNormalized"] = "Custom task names were normalized and deduplicated.",
    };

    private static readonly Dictionary<string, string> JaJp = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "アカウント",
        ["StartUp.ClientType"] = "クライアント",
        ["StartUp.StartGameEnabled"] = "ゲームを自動起動",
        ["StartUp.ConnectConfig"] = "接続プリセット",
        ["StartUp.ConnectAddress"] = "接続アドレス",
        ["StartUp.AdbPath"] = "ADB パス",
        ["StartUp.TouchMode"] = "タッチモード",
        ["StartUp.AutoDetect"] = "自動検出",
        ["StartUp.AttachScreencap"] = "AttachWindow-スクショ",
        ["StartUp.AttachMouse"] = "AttachWindow-タッチ",
        ["StartUp.AttachKeyboard"] = "AttachWindow-キーボード",
        ["Fight.Title"] = "戦闘",
        ["Fight.Stage"] = "ステージ",
        ["Fight.UseMedicine"] = "理性剤を使う",
        ["Fight.Medicine"] = "理性剤数",
        ["Fight.UseStone"] = "源石を使う",
        ["Fight.Stone"] = "源石数",
        ["Fight.EnableTimesLimit"] = "回数制限",
        ["Fight.Times"] = "回数",
        ["Fight.Series"] = "連戦",
        ["Fight.UseExpiringMedicine"] = "期限切れ間近理性剤",
        ["Fight.DrGrandet"] = "DrGrandet モード",
        ["Fight.EnableTargetDrop"] = "目標ドロップ",
        ["Fight.DropId"] = "ドロップ ID",
        ["Fight.DropCount"] = "目標数",
        ["Fight.UseAlternateStage"] = "代替ステージ",
        ["Fight.HideUnavailableStage"] = "未開放ステージを非表示",
        ["Fight.StageResetMode"] = "日替わりリセット",
        ["Fight.UseCustomAnnihilation"] = "殲滅カスタム",
        ["Fight.AnnihilationStage"] = "殲滅ステージ",
        ["Recruit.Title"] = "公開求人",
        ["Recruit.Times"] = "回数",
        ["Recruit.Refresh"] = "自動更新",
        ["Recruit.ForceRefresh"] = "強制更新",
        ["Recruit.UseExpedited"] = "即時完了を使用",
        ["Recruit.SkipRobot"] = "ロボタグをスキップ",
        ["Recruit.ChooseLevel3"] = "3★を選択",
        ["Recruit.ChooseLevel4"] = "4★を選択",
        ["Recruit.ChooseLevel5"] = "5★を選択",
        ["Recruit.SetTime"] = "時間を設定",
        ["Recruit.Level3Time"] = "3★時間",
        ["Recruit.Level4Time"] = "4★時間",
        ["Recruit.Level5Time"] = "5★時間",
        ["Recruit.ExtraTagsMode"] = "追加タグモード",
        ["Recruit.FirstTags"] = "優先タグ",
        ["Roguelike.Title"] = "ローグライク",
        ["Roguelike.Theme"] = "テーマ",
        ["Roguelike.Mode"] = "モード",
        ["Roguelike.Difficulty"] = "難易度",
        ["Roguelike.StartsCount"] = "開始回数",
        ["Roguelike.Squad"] = "分隊",
        ["Roguelike.Roles"] = "職分",
        ["Roguelike.CoreChar"] = "中核オペ",
        ["Roguelike.InvestmentEnabled"] = "投資を有効化",
        ["Roguelike.InvestmentWithMoreScore"] = "投資で得点優先",
        ["Roguelike.InvestmentsCount"] = "投資回数",
        ["Roguelike.StopWhenInvestmentFull"] = "投資満了で停止",
        ["Roguelike.UseSupport"] = "サポート使用",
        ["Roguelike.UseNonfriendSupport"] = "非フレサポート使用",
        ["Roguelike.RefreshTraderWithDice"] = "サイコロで商人更新",
        ["Roguelike.StopAtFinalBoss"] = "最終ボスで停止",
        ["Roguelike.StopAtMaxLevel"] = "最大レベルで停止",
        ["Roguelike.CollectibleModeShopping"] = "収集品モード買い物",
        ["Roguelike.CollectibleModeSquad"] = "収集品モード分隊",
        ["Roguelike.StartWithEliteTwo"] = "初手昇進2",
        ["Roguelike.OnlyStartWithEliteTwo"] = "初手昇進2のみ",
        ["Roguelike.Collectible.HotWater"] = "お湯",
        ["Roguelike.Collectible.Shield"] = "シールド",
        ["Roguelike.Collectible.Ingot"] = "インゴット",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "ランダム",
        ["Roguelike.Collectible.Key"] = "鍵",
        ["Roguelike.Collectible.Dice"] = "サイコロ",
        ["Roguelike.Collectible.Ideas"] = "発想",
        ["Roguelike.Collectible.Ticket"] = "チケット",
        ["Roguelike.MonthlySquadAutoIterate"] = "月次分隊を自動反復",
        ["Roguelike.MonthlySquadCheckComms"] = "月次分隊の通信確認",
        ["Roguelike.DeepExplorationAutoIterate"] = "深層探索を自動反復",
        ["Roguelike.FindPlayTimeTarget"] = "目標プレイ時間",
        ["Roguelike.FirstFloorFoldartal"] = "1層目フォルダータル",
        ["Roguelike.StartFoldartalList"] = "開始フォルダータル一覧",
        ["Roguelike.ExpectedCollapsalParadigms"] = "期待する崩壊パラダイム",
        ["Roguelike.StartWithSeed"] = "シード指定",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "テーマ",
        ["Reclamation.Mode"] = "モード",
        ["Reclamation.IncrementMode"] = "増分モード",
        ["Reclamation.NumCraftBatches"] = "クラフト回数",
        ["Reclamation.ToolsToCraft"] = "クラフト対象",
        ["Reclamation.ClearStore"] = "倉庫整理",
        ["Custom.Title"] = "カスタム",
        ["Custom.TaskNames"] = "タスク名リスト",
        ["Custom.TaskNamesPreview"] = "プレビュー",
        ["Common.LoadingTaskHint"] = "左側のタスクリストから対象タスクを選択してください。",
        ["Common.ValidationIssues"] = "検証メッセージ",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "エラー",
        ["TaskQueue.Validation.Clean"] = "検証に合格しました。",
        ["TaskQueue.Validation.WarningCount"] = "警告が {0} 件あります。",
        ["TaskQueue.Validation.BlockingCount"] = "ブロッキングエラーが {0} 件あります。",
        ["TaskQueue.Validation.LoadFailed"] = "検証レポートの読み込みに失敗しました。",
        ["TaskQueue.Error.BlockingValidation"] = "タスク `{0}` は検証でブロックされました: {1}",
        ["Issue.ClientTypeMissing"] = "クライアント種別は必須です。",
        ["Issue.FightStageMissing"] = "戦闘ステージは必須です。",
        ["Issue.FightSeriesOutOfRange"] = "連戦は -1 から 6 の範囲で指定してください。",
        ["Issue.FightTimesOutOfRange"] = "戦闘回数は 0 以上である必要があります。",
        ["Issue.FightDropMissing"] = "目標ドロップを有効にした場合はドロップ ID が必要です。",
        ["Issue.FightTimesMayNotExhausted"] = "現在の回数と連戦設定では回数を使い切れない可能性があります。",
        ["Issue.RecruitTimesOutOfRange"] = "公開求人回数は 0 以上である必要があります。",
        ["Issue.RecruitTimeOutOfRange"] = "公開求人時間は 60..540 かつ 10 分刻みで指定してください。",
        ["Issue.TaskFieldMissing"] = "設定に必須フィールドが不足しています。",
        ["Issue.TaskFieldTypeInvalid"] = "フィールド型が不正で解析できません。",
        ["Issue.DelimitedInputParseFailed"] = "構造化データ風の入力です。区切り文字付きテキストで入力してください。",
        ["Issue.RoguelikeModeInvalid"] = "ローグライクモードが未対応です。",
        ["Issue.RoguelikeThemeUnknown"] = "テーマが不明のため JieGarden にフォールバックしました。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "難易度は 0 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "開始回数は 0 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投資回数は 0 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "サイコロ更新は Mizuki のみ対応のため無効化しました。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime は JieGarden 必須のためフォールバックしました。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目標は 1..3 の範囲で自動補正されました。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "現在のモード/テーマ/分隊では初手昇進2を無効化しました。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "初手昇進2のみは初手昇進2有効時のみ有効です。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "サポート使用と初手昇進2が競合したため昇進2を無効化しました。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "シード形式が不正です。`<英数字>,rogue_<id>,<step>` を使用してください。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "開始フォルダータルは 3 件までのため切り詰めました。",
        ["Issue.ReclamationThemeUnknown"] = "生息演算テーマが不明のため Tales にフォールバックしました。",
        ["Issue.ReclamationModeInvalid"] = "生息演算モードが未対応です。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "増分モードは 0/1 のみ対応で自動補正されました。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "クラフト回数は 1..99999 に自動補正されました。",
        ["Issue.ReclamationToolNameInvalid"] = "クラフト対象に解析不能な構造化トークンが含まれています。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "無存档モードではクラフト対象を無視するため削除しました。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存档モードでは清倉が無効のためオフにしました。",
        ["Issue.CustomTaskNamesEmpty"] = "カスタムタスク名リストが空です。",
        ["Issue.CustomTaskNameInvalid"] = "カスタムタスク名に解析不能な構造化トークンがあります。",
        ["Issue.CustomTaskNameUnknown"] = "カスタムタスク名が未認識です。",
        ["Issue.CustomTaskNamesNormalized"] = "カスタムタスク名を正規化・重複排除しました。",
    };

    private static readonly Dictionary<string, string> KoKr = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "계정",
        ["StartUp.ClientType"] = "클라이언트",
        ["StartUp.StartGameEnabled"] = "게임 자동 시작",
        ["StartUp.ConnectConfig"] = "연결 프리셋",
        ["StartUp.ConnectAddress"] = "연결 주소",
        ["StartUp.AdbPath"] = "ADB 경로",
        ["StartUp.TouchMode"] = "터치 모드",
        ["StartUp.AutoDetect"] = "자동 감지",
        ["StartUp.AttachScreencap"] = "AttachWindow-스크린샷",
        ["StartUp.AttachMouse"] = "AttachWindow-터치",
        ["StartUp.AttachKeyboard"] = "AttachWindow-키보드",
        ["Fight.Title"] = "전투",
        ["Fight.Stage"] = "스테이지",
        ["Fight.UseMedicine"] = "이성약 사용",
        ["Fight.Medicine"] = "이성약 수",
        ["Fight.UseStone"] = "원석 사용",
        ["Fight.Stone"] = "원석 수",
        ["Fight.EnableTimesLimit"] = "횟수 제한",
        ["Fight.Times"] = "횟수",
        ["Fight.Series"] = "연전",
        ["Fight.UseExpiringMedicine"] = "만료 임박 이성약 사용",
        ["Fight.DrGrandet"] = "DrGrandet 모드",
        ["Fight.EnableTargetDrop"] = "목표 드랍",
        ["Fight.DropId"] = "드랍 ID",
        ["Fight.DropCount"] = "목표 수량",
        ["Fight.UseAlternateStage"] = "대체 스테이지",
        ["Fight.HideUnavailableStage"] = "미해금 스테이지 숨김",
        ["Fight.StageResetMode"] = "초기화 모드",
        ["Fight.UseCustomAnnihilation"] = "섬멸 커스텀",
        ["Fight.AnnihilationStage"] = "섬멸 스테이지",
        ["Recruit.Title"] = "공개채용",
        ["Recruit.Times"] = "횟수",
        ["Recruit.Refresh"] = "자동 새로고침",
        ["Recruit.ForceRefresh"] = "강제 새로고침",
        ["Recruit.UseExpedited"] = "가속권 사용",
        ["Recruit.SkipRobot"] = "로봇 태그 건너뛰기",
        ["Recruit.ChooseLevel3"] = "3성 선택",
        ["Recruit.ChooseLevel4"] = "4성 선택",
        ["Recruit.ChooseLevel5"] = "5성 선택",
        ["Recruit.SetTime"] = "시간 설정",
        ["Recruit.Level3Time"] = "3성 시간",
        ["Recruit.Level4Time"] = "4성 시간",
        ["Recruit.Level5Time"] = "5성 시간",
        ["Recruit.ExtraTagsMode"] = "추가 태그 모드",
        ["Recruit.FirstTags"] = "우선 태그",
        ["Roguelike.Title"] = "로그라이크",
        ["Roguelike.Theme"] = "테마",
        ["Roguelike.Mode"] = "모드",
        ["Roguelike.Difficulty"] = "난이도",
        ["Roguelike.StartsCount"] = "시작 횟수",
        ["Roguelike.Squad"] = "분대",
        ["Roguelike.Roles"] = "직군",
        ["Roguelike.CoreChar"] = "핵심 오퍼레이터",
        ["Roguelike.InvestmentEnabled"] = "투자 사용",
        ["Roguelike.InvestmentWithMoreScore"] = "점수 우선 투자",
        ["Roguelike.InvestmentsCount"] = "투자 횟수",
        ["Roguelike.StopWhenInvestmentFull"] = "투자 가득 차면 중지",
        ["Roguelike.UseSupport"] = "지원 오퍼 사용",
        ["Roguelike.UseNonfriendSupport"] = "비친구 지원 사용",
        ["Roguelike.RefreshTraderWithDice"] = "주사위로 상인 갱신",
        ["Roguelike.StopAtFinalBoss"] = "최종 보스에서 중지",
        ["Roguelike.StopAtMaxLevel"] = "최대 레벨에서 중지",
        ["Roguelike.CollectibleModeShopping"] = "수집 모드 쇼핑",
        ["Roguelike.CollectibleModeSquad"] = "수집 모드 분대",
        ["Roguelike.StartWithEliteTwo"] = "엘리트2 시작",
        ["Roguelike.OnlyStartWithEliteTwo"] = "엘리트2만 시작",
        ["Roguelike.Collectible.HotWater"] = "뜨거운 물",
        ["Roguelike.Collectible.Shield"] = "방패",
        ["Roguelike.Collectible.Ingot"] = "주괴",
        ["Roguelike.Collectible.Hope"] = "희망",
        ["Roguelike.Collectible.Random"] = "랜덤",
        ["Roguelike.Collectible.Key"] = "열쇠",
        ["Roguelike.Collectible.Dice"] = "주사위",
        ["Roguelike.Collectible.Ideas"] = "아이디어",
        ["Roguelike.Collectible.Ticket"] = "티켓",
        ["Roguelike.MonthlySquadAutoIterate"] = "월간 분대 자동 반복",
        ["Roguelike.MonthlySquadCheckComms"] = "월간 분대 통신 확인",
        ["Roguelike.DeepExplorationAutoIterate"] = "심층 탐색 자동 반복",
        ["Roguelike.FindPlayTimeTarget"] = "목표 플레이 시간",
        ["Roguelike.FirstFloorFoldartal"] = "1층 폴더탈",
        ["Roguelike.StartFoldartalList"] = "시작 폴더탈 목록",
        ["Roguelike.ExpectedCollapsalParadigms"] = "예상 붕괴 패러다임",
        ["Roguelike.StartWithSeed"] = "시드 지정",
        ["Reclamation.Title"] = "생식연산",
        ["Reclamation.Theme"] = "테마",
        ["Reclamation.Mode"] = "모드",
        ["Reclamation.IncrementMode"] = "증분 모드",
        ["Reclamation.NumCraftBatches"] = "제작 배치 수",
        ["Reclamation.ToolsToCraft"] = "제작 도구 목록",
        ["Reclamation.ClearStore"] = "창고 비우기",
        ["Custom.Title"] = "커스텀",
        ["Custom.TaskNames"] = "작업 이름 목록",
        ["Custom.TaskNamesPreview"] = "미리보기",
        ["Common.LoadingTaskHint"] = "왼쪽 작업 목록에서 작업을 먼저 선택하세요.",
        ["Common.ValidationIssues"] = "검증 메시지",
        ["Common.WarningPrefix"] = "경고",
        ["Common.ErrorPrefix"] = "오류",
        ["TaskQueue.Validation.Clean"] = "검증을 통과했습니다.",
        ["TaskQueue.Validation.WarningCount"] = "경고 항목 {0}개가 있습니다.",
        ["TaskQueue.Validation.BlockingCount"] = "차단 오류 {0}개가 있습니다.",
        ["TaskQueue.Validation.LoadFailed"] = "검증 보고서를 불러오지 못했습니다.",
        ["TaskQueue.Error.BlockingValidation"] = "작업 `{0}` 이(가) 검증에 의해 차단되었습니다: {1}",
        ["Issue.ClientTypeMissing"] = "클라이언트 유형은 비워둘 수 없습니다.",
        ["Issue.FightStageMissing"] = "전투 스테이지는 비워둘 수 없습니다.",
        ["Issue.FightSeriesOutOfRange"] = "연전 값은 -1 에서 6 사이여야 합니다.",
        ["Issue.FightTimesOutOfRange"] = "전투 횟수는 0 이상이어야 합니다.",
        ["Issue.FightDropMissing"] = "목표 드랍 사용 시 드랍 ID가 필요합니다.",
        ["Issue.FightTimesMayNotExhausted"] = "현재 연전 설정에서 횟수가 남을 수 있습니다.",
        ["Issue.RecruitTimesOutOfRange"] = "공개채용 횟수는 0 이상이어야 합니다.",
        ["Issue.RecruitTimeOutOfRange"] = "공개채용 시간은 60..540 범위의 10분 단위여야 합니다.",
        ["Issue.TaskFieldMissing"] = "설정에 필수 필드가 누락되었습니다.",
        ["Issue.TaskFieldTypeInvalid"] = "필드 형식이 잘못되어 파싱할 수 없습니다.",
        ["Issue.DelimitedInputParseFailed"] = "구조화된 입력으로 보입니다. 구분자 기반 평문으로 입력하세요.",
        ["Issue.RoguelikeModeInvalid"] = "로그라이크 모드가 지원되지 않습니다.",
        ["Issue.RoguelikeThemeUnknown"] = "알 수 없는 테마로 인해 JieGarden으로 대체되었습니다.",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "난이도는 0 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "시작 횟수는 0 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "투자 횟수는 0 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "상인 주사위 갱신은 Mizuki에서만 지원되어 비활성화되었습니다.",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime은 JieGarden이 필요하여 자동 대체되었습니다.",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 대상은 1..3 범위로 자동 보정되었습니다.",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "현재 모드/테마/분대에서는 엘리트2 시작이 비활성화되었습니다.",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "엘리트2만 시작은 엘리트2 시작이 필요합니다.",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "지원 사용과 엘리트2 시작이 충돌하여 엘리트2 시작을 비활성화했습니다.",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "시드 형식이 잘못되었습니다. `<영숫자>,rogue_<id>,<step>` 형식을 사용하세요.",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "시작 폴더탈 목록은 3개로 잘렸습니다.",
        ["Issue.ReclamationThemeUnknown"] = "생식연산 테마가 알 수 없어 Tales로 대체되었습니다.",
        ["Issue.ReclamationModeInvalid"] = "생식연산 모드가 지원되지 않습니다.",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "증분 모드는 0/1만 지원되어 자동 보정되었습니다.",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "제작 배치 수는 1..99999 범위로 자동 보정되었습니다.",
        ["Issue.ReclamationToolNameInvalid"] = "제작 도구 목록에 파싱할 수 없는 구조화 토큰이 있습니다.",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "무저장 모드에서는 제작 도구 목록이 무시되어 비워졌습니다.",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "저장 모드에서는 창고 비우기가 무시되어 비활성화되었습니다.",
        ["Issue.CustomTaskNamesEmpty"] = "커스텀 작업 이름 목록이 비어 있습니다.",
        ["Issue.CustomTaskNameInvalid"] = "커스텀 작업 이름에 파싱할 수 없는 구조화 토큰이 있습니다.",
        ["Issue.CustomTaskNameUnknown"] = "커스텀 작업 이름을 인식할 수 없습니다.",
        ["Issue.CustomTaskNamesNormalized"] = "커스텀 작업 이름이 정규화 및 중복 제거되었습니다.",
    };

    private static readonly Dictionary<string, string> ZhTw = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "開始喚醒",
        ["StartUp.AccountName"] = "帳號",
        ["StartUp.ClientType"] = "客戶端",
        ["StartUp.StartGameEnabled"] = "自動啟動遊戲",
        ["StartUp.ConnectConfig"] = "連線預設",
        ["StartUp.ConnectAddress"] = "連線位址",
        ["StartUp.AdbPath"] = "ADB 路徑",
        ["StartUp.TouchMode"] = "觸控模式",
        ["StartUp.AutoDetect"] = "自動偵測連線",
        ["StartUp.AttachScreencap"] = "AttachWindow-截圖",
        ["StartUp.AttachMouse"] = "AttachWindow-觸控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-鍵盤",
        ["Fight.Title"] = "戰鬥",
        ["Fight.Stage"] = "關卡",
        ["Fight.UseMedicine"] = "使用理智藥",
        ["Fight.Medicine"] = "理智藥數量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石數量",
        ["Fight.EnableTimesLimit"] = "限制次數",
        ["Fight.Times"] = "次數",
        ["Fight.Series"] = "連戰",
        ["Fight.UseExpiringMedicine"] = "使用即將過期理智藥",
        ["Fight.DrGrandet"] = "理智策略 DrGrandet",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目標數量",
        ["Fight.UseAlternateStage"] = "啟用換圖",
        ["Fight.HideUnavailableStage"] = "隱藏不可用關卡",
        ["Fight.StageResetMode"] = "重置模式",
        ["Fight.UseCustomAnnihilation"] = "自訂剿滅",
        ["Fight.AnnihilationStage"] = "剿滅關卡",
        ["Recruit.Title"] = "公開招募",
        ["Recruit.Times"] = "招募次數",
        ["Recruit.Refresh"] = "自動刷新",
        ["Recruit.ForceRefresh"] = "強制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.SkipRobot"] = "跳過支援機械",
        ["Recruit.ChooseLevel3"] = "選擇 3 星",
        ["Recruit.ChooseLevel4"] = "選擇 4 星",
        ["Recruit.ChooseLevel5"] = "選擇 5 星",
        ["Recruit.SetTime"] = "設定時長",
        ["Recruit.Level3Time"] = "3 星時長",
        ["Recruit.Level4Time"] = "4 星時長",
        ["Recruit.Level5Time"] = "5 星時長",
        ["Recruit.ExtraTagsMode"] = "額外標籤策略",
        ["Recruit.FirstTags"] = "優先標籤",
        ["Roguelike.Title"] = "肉鴿",
        ["Roguelike.Theme"] = "主題",
        ["Roguelike.Mode"] = "模式",
        ["Roguelike.Difficulty"] = "難度",
        ["Roguelike.StartsCount"] = "開局次數",
        ["Roguelike.Squad"] = "開局分隊",
        ["Roguelike.Roles"] = "開局職業",
        ["Roguelike.CoreChar"] = "核心幹員",
        ["Roguelike.InvestmentEnabled"] = "啟用投資",
        ["Roguelike.InvestmentWithMoreScore"] = "投資優先分數",
        ["Roguelike.InvestmentsCount"] = "投資次數上限",
        ["Roguelike.StopWhenInvestmentFull"] = "投資滿時停止",
        ["Roguelike.UseSupport"] = "使用助戰",
        ["Roguelike.UseNonfriendSupport"] = "使用非好友助戰",
        ["Roguelike.RefreshTraderWithDice"] = "使用骰子刷新商人",
        ["Roguelike.StopAtFinalBoss"] = "終局停下",
        ["Roguelike.StopAtMaxLevel"] = "滿級停下",
        ["Roguelike.CollectibleModeShopping"] = "收藏品模式購物",
        ["Roguelike.CollectibleModeSquad"] = "收藏品模式分隊",
        ["Roguelike.StartWithEliteTwo"] = "開局精二",
        ["Roguelike.OnlyStartWithEliteTwo"] = "僅開局精二",
        ["Roguelike.Collectible.HotWater"] = "熱水壺",
        ["Roguelike.Collectible.Shield"] = "護盾",
        ["Roguelike.Collectible.Ingot"] = "源石錠",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "隨機",
        ["Roguelike.Collectible.Key"] = "鑰匙",
        ["Roguelike.Collectible.Dice"] = "骰子",
        ["Roguelike.Collectible.Ideas"] = "構想",
        ["Roguelike.Collectible.Ticket"] = "票券",
        ["Roguelike.MonthlySquadAutoIterate"] = "月度小隊自動迭代",
        ["Roguelike.MonthlySquadCheckComms"] = "月度小隊檢查通訊",
        ["Roguelike.DeepExplorationAutoIterate"] = "深度探索自動迭代",
        ["Roguelike.FindPlayTimeTarget"] = "定向遊玩目標",
        ["Roguelike.FirstFloorFoldartal"] = "首層折紙",
        ["Roguelike.StartFoldartalList"] = "起始折紙列表",
        ["Roguelike.ExpectedCollapsalParadigms"] = "期望坍縮範式",
        ["Roguelike.StartWithSeed"] = "指定種子",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "主題",
        ["Reclamation.Mode"] = "模式",
        ["Reclamation.IncrementMode"] = "增量模式",
        ["Reclamation.NumCraftBatches"] = "回合合成批次",
        ["Reclamation.ToolsToCraft"] = "合成工具列表",
        ["Reclamation.ClearStore"] = "清倉",
        ["Custom.Title"] = "自訂任務",
        ["Custom.TaskNames"] = "任務名列表",
        ["Custom.TaskNamesPreview"] = "格式化預覽",
        ["Common.LoadingTaskHint"] = "請先在左側任務列表中選擇對應任務。",
        ["Common.ValidationIssues"] = "校驗資訊",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "錯誤",
        ["TaskQueue.Validation.Clean"] = "校驗通過。",
        ["TaskQueue.Validation.WarningCount"] = "存在 {0} 條預警。",
        ["TaskQueue.Validation.BlockingCount"] = "存在 {0} 條阻斷錯誤。",
        ["TaskQueue.Validation.LoadFailed"] = "讀取校驗報告失敗。",
        ["TaskQueue.Error.BlockingValidation"] = "任務 `{0}` 存在阻斷校驗項：{1}",
        ["Issue.ClientTypeMissing"] = "客戶端類型不能為空。",
        ["Issue.FightStageMissing"] = "戰鬥關卡不能為空。",
        ["Issue.FightSeriesOutOfRange"] = "連戰範圍需在 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "戰鬥次數不能小於 0。",
        ["Issue.FightDropMissing"] = "指定掉落時必須填寫掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "當前次數與連戰設定可能無法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次數不能小於 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募時長需在 60..540 且步長為 10。",
        ["Issue.TaskFieldMissing"] = "配置缺少必填欄位。",
        ["Issue.TaskFieldTypeInvalid"] = "欄位型別不正確，無法解析。",
        ["Issue.DelimitedInputParseFailed"] = "輸入看起來像結構化資料，請改用分隔字元純文字。",
        ["Issue.RoguelikeModeInvalid"] = "肉鴿模式不受支援。",
        ["Issue.RoguelikeThemeUnknown"] = "主題未知，已降級為 JieGarden。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "難度不能小於 0，已自動修正。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "開局次數不能小於 0，已自動修正。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投資次數不能小於 0，已自動修正。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "僅 Mizuki 主題支援骰子刷新商人，已自動關閉。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime 僅支援 JieGarden 主題，已自動降級。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目標應在 1..3，已自動修正。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "目前模式/主題/分隊不支援開局精二，已自動關閉。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "僅開局精二依賴開局精二開關，已自動關閉。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "助戰與開局精二衝突，已自動關閉開局精二。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "種子格式不合法，應為 `<英數字>,rogue_<id>,<step>`。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "起始折紙列表超過 3 項，已截斷。",
        ["Issue.ReclamationThemeUnknown"] = "生息主題未知，已降級為 Tales。",
        ["Issue.ReclamationModeInvalid"] = "生息模式不受支援。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "增量模式僅支援 0/1，已自動修正。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "單次組裝輪數應在 1..99999，已自動修正。",
        ["Issue.ReclamationToolNameInvalid"] = "工具列表包含無法解析的結構化內容。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "無存檔模式會忽略工具列表，已清空。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存檔模式會忽略清倉，已關閉。",
        ["Issue.CustomTaskNamesEmpty"] = "自訂任務名稱列表為空。",
        ["Issue.CustomTaskNameInvalid"] = "自訂任務名稱包含無法解析的結構化內容。",
        ["Issue.CustomTaskNameUnknown"] = "自訂任務名稱未識別。",
        ["Issue.CustomTaskNamesNormalized"] = "自訂任務名稱已標準化並去重。",
    };

    private static readonly Dictionary<string, string> Pallas = new(EnUs, StringComparer.OrdinalIgnoreCase);

    private string _language = UiLanguageCatalog.DefaultLanguage;

    public event Action<LocalizationFallbackInfo>? FallbackReported;

    public string Language
    {
        get => _language;
        set
        {
            var normalized = UiLanguageCatalog.Normalize(value);
            if (!SetProperty(ref _language, normalized))
            {
                return;
            }

            OnPropertyChanged("Item[]");
        }
    }

    public string this[string key]
    {
        get
        {
            var normalizedLanguage = UiLanguageCatalog.Normalize(Language);
            var source = ResolveSource(normalizedLanguage);
            if (source.TryGetValue(key, out var value))
            {
                return value;
            }

            if (EnUs.TryGetValue(key, out value))
            {
                ReportFallback(normalizedLanguage, key, UiLanguageCatalog.FallbackLanguage);
                return value;
            }

            if (ZhCn.TryGetValue(key, out value))
            {
                ReportFallback(normalizedLanguage, key, UiLanguageCatalog.DefaultLanguage);
                return value;
            }

            ReportFallback(normalizedLanguage, key, "key");
            return key;
        }
    }

    public string GetOrDefault(string key, string fallback)
    {
        var value = this[key];
        return string.Equals(value, key, StringComparison.Ordinal) ? fallback : value;
    }

    private static Dictionary<string, string> ResolveSource(string language)
    {
        if (string.Equals(language, "en-us", StringComparison.OrdinalIgnoreCase))
        {
            return EnUs;
        }

        if (string.Equals(language, "ja-jp", StringComparison.OrdinalIgnoreCase))
        {
            return JaJp;
        }

        if (string.Equals(language, "ko-kr", StringComparison.OrdinalIgnoreCase))
        {
            return KoKr;
        }

        if (string.Equals(language, "zh-tw", StringComparison.OrdinalIgnoreCase))
        {
            return ZhTw;
        }

        if (string.Equals(language, "pallas", StringComparison.OrdinalIgnoreCase))
        {
            return Pallas;
        }

        return ZhCn;
    }

    private void ReportFallback(string language, string key, string fallbackSource)
    {
        FallbackReported?.Invoke(
            new LocalizationFallbackInfo(
                Scope: "TaskQueue.Localization",
                Language: language,
                Key: key,
                FallbackSource: fallbackSource));
    }
}
