using MAAUnified.App.ViewModels.Infrastructure;

namespace MAAUnified.App.ViewModels.TaskQueue;

public sealed class LocalizedTextMap : ObservableObject
{
    private static readonly Dictionary<string, string> ZhCn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "基建",
        ["Infrast.Mode"] = "基建模式",
        ["Infrast.Mode.Normal"] = "默认排班",
        ["Infrast.Mode.Custom"] = "自定义排班",
        ["Infrast.Mode.Rotation"] = "轮换排班",
        ["Infrast.Drones"] = "无人机策略",
        ["Infrast.Threshold"] = "宿舍阈值(%)",
        ["Infrast.File"] = "自定义基建文件",
        ["Infrast.Plan"] = "计划索引",
        ["Infrast.Plan.Auto"] = "自动(按时间轮换)",
        ["Infrast.Plan.Refresh"] = "刷新计划",
        ["Infrast.Plan.DefaultName"] = "计划 {0}",
        ["Infrast.Plan.Display"] = "{0}（{1} 个时段）",
        ["Infrast.Facility"] = "房间顺序",
        ["Infrast.SelectAll"] = "全选",
        ["Infrast.Clear"] = "清空",
        ["Infrast.Advanced"] = "高级选项",
        ["Infrast.Trust"] = "宿舍信赖收取",
        ["Infrast.NotStationed"] = "过滤未入驻干员",
        ["Infrast.ContinueTraining"] = "保留训练进度",
        ["Infrast.Replenish"] = "搓玉补货",
        ["Infrast.ReceptionBoard"] = "会客室板子领取",
        ["Infrast.ReceptionExchange"] = "线索交换",
        ["Infrast.ReceptionSend"] = "赠送线索",
        ["Infrast.Error.CustomFileNotFound"] = "自定义文件不存在：{0}",
        ["Infrast.Error.PlanOutOfRange"] = "计划索引 {0} 超出 `{1}` 范围。",
        ["Infrast.Error.ParseFailed"] = "解析自定义基建文件失败。",
        ["Infrast.Status.LoadedPlans"] = "已加载 {0} 个计划。",
        ["Mall.Title"] = "商店",
        ["Mall.VisitFriends"] = "访问好友",
        ["Mall.VisitOnce"] = "好友访问每日一次",
        ["Mall.CreditFight"] = "信用作战",
        ["Mall.CreditFightOnce"] = "信用作战每日一次",
        ["Mall.Formation"] = "编队",
        ["Mall.Shopping"] = "信用购物",
        ["Mall.BuyFirst"] = "高优先列表(分号分隔)",
        ["Mall.Blacklist"] = "黑名单(分号分隔)",
        ["Mall.ForceShopping"] = "信用满时强制购物",
        ["Mall.OnlyDiscount"] = "仅买折扣",
        ["Mall.Reserve"] = "保留 300 信用",
        ["Award.Title"] = "奖励",
        ["Award.Award"] = "日常/周常奖励",
        ["Award.Mail"] = "邮件奖励",
        ["Award.Recruit"] = "免费单抽",
        ["Award.RecruitTip"] = "开启免费单抽前需要确认",
        ["Award.Confirm"] = "确认开启",
        ["Award.Cancel"] = "取消",
        ["Award.Orundum"] = "合成玉领取",
        ["Award.Mining"] = "矿区奖励领取",
        ["Award.Special"] = "特别授权领取",
        ["PostAction.Title"] = "后置动作",
        ["PostAction.Once"] = "一次性(本轮生效)",
        ["PostAction.BackToHome"] = "返回模拟器首页",
        ["PostAction.ExitArknights"] = "退出游戏",
        ["PostAction.ExitEmulator"] = "关闭模拟器",
        ["PostAction.ExitSelf"] = "关闭 MAA",
        ["PostAction.IfNoOther"] = "仅无其他 MAA 时执行",
        ["PostAction.Sleep"] = "睡眠",
        ["PostAction.Hibernate"] = "休眠",
        ["PostAction.Shutdown"] = "关机",
        ["PostAction.Clear"] = "清空动作",
        ["PostAction.Unsupported"] = "该动作当前平台不支持，将降级为日志记录。",
        ["PostAction.Cmd.ExitArknights"] = "退出游戏命令",
        ["PostAction.Cmd.BackToHome"] = "返回首页命令",
        ["PostAction.Cmd.ExitEmulator"] = "关闭模拟器命令",
        ["PostAction.Cmd.ExitSelf"] = "关闭 MAA 命令",
        ["PostAction.Cmd.Watermark"] = "留空则仅记录降级日志",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "“仅无其他 MAA 时执行”需要至少勾选一个系统动作（睡眠/休眠/关机）。",
        ["PostAction.Warn.UnsupportedDowngrade"] = "当前选择包含不可执行动作，将降级为日志记录。",
        ["StartUp.Title"] = "开始唤醒",
        ["StartUp.AccountName"] = "账号",
        ["StartUp.ClientType"] = "客户端",
        ["StartUp.StartGameEnabled"] = "自动启动游戏",
        ["StartUp.ConnectConfig"] = "连接预设",
        ["StartUp.ConnectAddress"] = "连接地址",
        ["StartUp.AdbPath"] = "ADB 路径",
        ["StartUp.TouchMode"] = "触控模式",
        ["StartUp.AutoDetect"] = "自动检测连接",
        ["StartUp.AttachScreencap"] = "AttachWindow-截图",
        ["StartUp.AttachMouse"] = "AttachWindow-触控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-键盘",
        ["Fight.Title"] = "战斗",
        ["Fight.Stage"] = "关卡",
        ["Fight.UseMedicine"] = "使用理智药",
        ["Fight.Medicine"] = "理智药数量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石数量",
        ["Fight.EnableTimesLimit"] = "限制次数",
        ["Fight.Times"] = "次数",
        ["Fight.Series"] = "连战",
        ["Fight.UseExpiringMedicine"] = "使用即将过期理智药",
        ["Fight.DrGrandet"] = "理智策略 DrGrandet",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目标数量",
        ["Fight.UseAlternateStage"] = "启用换图",
        ["Fight.HideUnavailableStage"] = "隐藏不可用关卡",
        ["Fight.StageResetMode"] = "换日重置模式",
        ["Fight.UseCustomAnnihilation"] = "自定义剿灭",
        ["Fight.AnnihilationStage"] = "剿灭关卡",
        ["Recruit.Title"] = "公开招募",
        ["Recruit.Times"] = "招募次数",
        ["Recruit.Refresh"] = "自动刷新",
        ["Recruit.ForceRefresh"] = "强制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.SkipRobot"] = "跳过支援机械",
        ["Recruit.ChooseLevel3"] = "选择 3 星",
        ["Recruit.ChooseLevel4"] = "选择 4 星",
        ["Recruit.ChooseLevel5"] = "选择 5 星",
        ["Recruit.SetTime"] = "设置时长",
        ["Recruit.Level3Time"] = "3 星时长",
        ["Recruit.Level4Time"] = "4 星时长",
        ["Recruit.Level5Time"] = "5 星时长",
        ["Recruit.ExtraTagsMode"] = "额外标签策略",
        ["Recruit.FirstTags"] = "优先标签",
        ["Common.LoadingTaskHint"] = "请先在左侧任务列表中选择对应任务。",
        ["Common.ValidationIssues"] = "校验信息",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "错误",
        ["TaskQueue.DailyStageHintDefault"] = "今日关卡信息将在资源加载后展示。",
        ["TaskQueue.OverlayDisconnected"] = "Overlay 未连接",
        ["TaskQueue.Error.SelectTaskToRemove"] = "请先选择要删除的任务。",
        ["TaskQueue.Error.SelectTaskToRename"] = "请先选择要重命名的任务。",
        ["TaskQueue.Error.SelectTaskToMove"] = "请先选择要移动的任务。",
        ["Issue.ClientTypeMissing"] = "客户端类型不能为空。",
        ["Issue.FightStageMissing"] = "战斗关卡不能为空。",
        ["Issue.FightSeriesOutOfRange"] = "连战范围应在 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "战斗次数不能小于 0。",
        ["Issue.FightDropMissing"] = "指定掉落时必须填写掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "当前次数与连战设置可能无法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次数不能小于 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募时长需在 60..540 且步长为 10。",
        ["Issue.TaskFieldMissing"] = "配置缺少必填字段。",
    };

    private static readonly Dictionary<string, string> EnUs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "Infrast",
        ["Infrast.Mode"] = "Mode",
        ["Infrast.Mode.Normal"] = "Default",
        ["Infrast.Mode.Custom"] = "Custom",
        ["Infrast.Mode.Rotation"] = "Rotation",
        ["Infrast.Drones"] = "Drones",
        ["Infrast.Threshold"] = "Dorm Threshold(%)",
        ["Infrast.File"] = "Custom Infrast File",
        ["Infrast.Plan"] = "Plan Index",
        ["Infrast.Plan.Auto"] = "Auto by time",
        ["Infrast.Plan.Refresh"] = "Reload Plans",
        ["Infrast.Plan.DefaultName"] = "Plan {0}",
        ["Infrast.Plan.Display"] = "{0} ({1} period)",
        ["Infrast.Facility"] = "Facility Order",
        ["Infrast.SelectAll"] = "Select All",
        ["Infrast.Clear"] = "Clear",
        ["Infrast.Advanced"] = "Advanced",
        ["Infrast.Trust"] = "Dorm trust",
        ["Infrast.NotStationed"] = "Filter stationed operators",
        ["Infrast.ContinueTraining"] = "Continue training",
        ["Infrast.Replenish"] = "Originium replenish",
        ["Infrast.ReceptionBoard"] = "Reception board",
        ["Infrast.ReceptionExchange"] = "Clue exchange",
        ["Infrast.ReceptionSend"] = "Send clue",
        ["Infrast.Error.CustomFileNotFound"] = "Custom file not found: {0}",
        ["Infrast.Error.PlanOutOfRange"] = "Plan index {0} is out of range for `{1}`.",
        ["Infrast.Error.ParseFailed"] = "Failed to parse custom infrast file.",
        ["Infrast.Status.LoadedPlans"] = "Loaded {0} plans.",
        ["Mall.Title"] = "Mall",
        ["Mall.VisitFriends"] = "Visit friends",
        ["Mall.VisitOnce"] = "Visit friends once a day",
        ["Mall.CreditFight"] = "Credit fight",
        ["Mall.CreditFightOnce"] = "Credit fight once a day",
        ["Mall.Formation"] = "Formation",
        ["Mall.Shopping"] = "Credit shopping",
        ["Mall.BuyFirst"] = "Buy-first list (semicolon separated)",
        ["Mall.Blacklist"] = "Blacklist (semicolon separated)",
        ["Mall.ForceShopping"] = "Force shopping when full",
        ["Mall.OnlyDiscount"] = "Discount only",
        ["Mall.Reserve"] = "Reserve 300 credits",
        ["Award.Title"] = "Award",
        ["Award.Award"] = "Daily/weekly rewards",
        ["Award.Mail"] = "Mail rewards",
        ["Award.Recruit"] = "Free gacha",
        ["Award.RecruitTip"] = "Confirmation required before enabling free gacha",
        ["Award.Confirm"] = "Confirm",
        ["Award.Cancel"] = "Cancel",
        ["Award.Orundum"] = "Orundum",
        ["Award.Mining"] = "Mining rewards",
        ["Award.Special"] = "Special access",
        ["PostAction.Title"] = "Post Action",
        ["PostAction.Once"] = "Once for current run",
        ["PostAction.BackToHome"] = "Back to emulator home",
        ["PostAction.ExitArknights"] = "Exit Arknights",
        ["PostAction.ExitEmulator"] = "Exit emulator",
        ["PostAction.ExitSelf"] = "Exit MAA",
        ["PostAction.IfNoOther"] = "Only if no other MAA",
        ["PostAction.Sleep"] = "Sleep",
        ["PostAction.Hibernate"] = "Hibernate",
        ["PostAction.Shutdown"] = "Shutdown",
        ["PostAction.Clear"] = "Clear",
        ["PostAction.Unsupported"] = "This action is unsupported on current platform and will be downgraded to logging.",
        ["PostAction.Cmd.ExitArknights"] = "Exit Arknights command",
        ["PostAction.Cmd.BackToHome"] = "Back to home command",
        ["PostAction.Cmd.ExitEmulator"] = "Exit emulator command",
        ["PostAction.Cmd.ExitSelf"] = "Exit MAA command",
        ["PostAction.Cmd.Watermark"] = "Leave empty to downgrade to logging only",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "`IfNoOtherMaa` requires at least one system action (Sleep/Hibernate/Shutdown).",
        ["PostAction.Warn.UnsupportedDowngrade"] = "Some selected post actions are not executable and will be downgraded to logging.",
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "Account",
        ["StartUp.ClientType"] = "Client Type",
        ["StartUp.StartGameEnabled"] = "Start game automatically",
        ["StartUp.ConnectConfig"] = "Connect preset",
        ["StartUp.ConnectAddress"] = "Connect address",
        ["StartUp.AdbPath"] = "ADB path",
        ["StartUp.TouchMode"] = "Touch mode",
        ["StartUp.AutoDetect"] = "Auto detect",
        ["StartUp.AttachScreencap"] = "AttachWindow - Screenshot",
        ["StartUp.AttachMouse"] = "AttachWindow - Touch",
        ["StartUp.AttachKeyboard"] = "AttachWindow - Keyboard",
        ["Fight.Title"] = "Fight",
        ["Fight.Stage"] = "Stage",
        ["Fight.UseMedicine"] = "Use medicine",
        ["Fight.Medicine"] = "Medicine",
        ["Fight.UseStone"] = "Use stone",
        ["Fight.Stone"] = "Stone",
        ["Fight.EnableTimesLimit"] = "Enable times limit",
        ["Fight.Times"] = "Times",
        ["Fight.Series"] = "Series",
        ["Fight.UseExpiringMedicine"] = "Use expiring medicine",
        ["Fight.DrGrandet"] = "DrGrandet mode",
        ["Fight.EnableTargetDrop"] = "Target drop",
        ["Fight.DropId"] = "Drop ID",
        ["Fight.DropCount"] = "Drop count",
        ["Fight.UseAlternateStage"] = "Use alternate stage",
        ["Fight.HideUnavailableStage"] = "Hide unavailable stages",
        ["Fight.StageResetMode"] = "Stage reset mode",
        ["Fight.UseCustomAnnihilation"] = "Custom annihilation",
        ["Fight.AnnihilationStage"] = "Annihilation stage",
        ["Recruit.Title"] = "Recruit",
        ["Recruit.Times"] = "Times",
        ["Recruit.Refresh"] = "Refresh",
        ["Recruit.ForceRefresh"] = "Force refresh",
        ["Recruit.UseExpedited"] = "Use expedited",
        ["Recruit.SkipRobot"] = "Skip robot",
        ["Recruit.ChooseLevel3"] = "Choose 3-star",
        ["Recruit.ChooseLevel4"] = "Choose 4-star",
        ["Recruit.ChooseLevel5"] = "Choose 5-star",
        ["Recruit.SetTime"] = "Set time",
        ["Recruit.Level3Time"] = "3-star time",
        ["Recruit.Level4Time"] = "4-star time",
        ["Recruit.Level5Time"] = "5-star time",
        ["Recruit.ExtraTagsMode"] = "Extra tags mode",
        ["Recruit.FirstTags"] = "First tags",
        ["Common.LoadingTaskHint"] = "Select a task from the left list first.",
        ["Common.ValidationIssues"] = "Validation Issues",
        ["Common.WarningPrefix"] = "Warning",
        ["Common.ErrorPrefix"] = "Error",
        ["TaskQueue.DailyStageHintDefault"] = "Daily stage hints will be shown after resources are loaded.",
        ["TaskQueue.OverlayDisconnected"] = "Overlay disconnected",
        ["TaskQueue.Error.SelectTaskToRemove"] = "Select a task to remove first.",
        ["TaskQueue.Error.SelectTaskToRename"] = "Select a task to rename first.",
        ["TaskQueue.Error.SelectTaskToMove"] = "Select a task to move first.",
        ["Issue.ClientTypeMissing"] = "Client type cannot be empty.",
        ["Issue.FightStageMissing"] = "Fight stage cannot be empty.",
        ["Issue.FightSeriesOutOfRange"] = "Fight series must be between -1 and 6.",
        ["Issue.FightTimesOutOfRange"] = "Fight times must be greater than or equal to zero.",
        ["Issue.FightDropMissing"] = "Drop id is required when target drop is enabled.",
        ["Issue.FightTimesMayNotExhausted"] = "Times may not be fully exhausted under current series.",
        ["Issue.RecruitTimesOutOfRange"] = "Recruit times must be greater than or equal to zero.",
        ["Issue.RecruitTimeOutOfRange"] = "Recruit time must be 60..540 with 10-minute steps.",
        ["Issue.TaskFieldMissing"] = "Required field is missing in config.",
    };

    private static readonly Dictionary<string, string> JaJp = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "アカウント",
        ["StartUp.ClientType"] = "クライアント",
        ["StartUp.StartGameEnabled"] = "ゲームを自動起動",
        ["StartUp.ConnectConfig"] = "接続プリセット",
        ["StartUp.ConnectAddress"] = "接続アドレス",
        ["StartUp.AdbPath"] = "ADB パス",
        ["StartUp.TouchMode"] = "タッチモード",
        ["StartUp.AutoDetect"] = "自動検出",
        ["StartUp.AttachScreencap"] = "AttachWindow-スクショ",
        ["StartUp.AttachMouse"] = "AttachWindow-タッチ",
        ["StartUp.AttachKeyboard"] = "AttachWindow-キーボード",
        ["Fight.Title"] = "戦闘",
        ["Fight.Stage"] = "ステージ",
        ["Fight.UseMedicine"] = "理性剤を使う",
        ["Fight.Medicine"] = "理性剤数",
        ["Fight.UseStone"] = "源石を使う",
        ["Fight.Stone"] = "源石数",
        ["Fight.EnableTimesLimit"] = "回数制限",
        ["Fight.Times"] = "回数",
        ["Fight.Series"] = "連戦",
        ["Fight.UseExpiringMedicine"] = "期限切れ間近理性剤",
        ["Fight.DrGrandet"] = "DrGrandet モード",
        ["Fight.EnableTargetDrop"] = "目標ドロップ",
        ["Fight.DropId"] = "ドロップ ID",
        ["Fight.DropCount"] = "目標数",
        ["Fight.UseAlternateStage"] = "代替ステージ",
        ["Fight.HideUnavailableStage"] = "未開放ステージを非表示",
        ["Fight.StageResetMode"] = "日替わりリセット",
        ["Fight.UseCustomAnnihilation"] = "殲滅カスタム",
        ["Fight.AnnihilationStage"] = "殲滅ステージ",
        ["Recruit.Title"] = "公開求人",
        ["Recruit.Times"] = "回数",
        ["Recruit.Refresh"] = "自動更新",
        ["Recruit.ForceRefresh"] = "強制更新",
        ["Recruit.UseExpedited"] = "即時完了を使用",
        ["Recruit.SkipRobot"] = "ロボタグをスキップ",
        ["Recruit.ChooseLevel3"] = "3★を選択",
        ["Recruit.ChooseLevel4"] = "4★を選択",
        ["Recruit.ChooseLevel5"] = "5★を選択",
        ["Recruit.SetTime"] = "時間を設定",
        ["Recruit.Level3Time"] = "3★時間",
        ["Recruit.Level4Time"] = "4★時間",
        ["Recruit.Level5Time"] = "5★時間",
        ["Recruit.ExtraTagsMode"] = "追加タグモード",
        ["Recruit.FirstTags"] = "優先タグ",
        ["Common.LoadingTaskHint"] = "左側のタスクリストから対象タスクを選択してください。",
        ["Common.ValidationIssues"] = "検証メッセージ",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "エラー",
        ["Issue.ClientTypeMissing"] = "クライアント種別は必須です。",
        ["Issue.FightStageMissing"] = "戦闘ステージは必須です。",
        ["Issue.FightSeriesOutOfRange"] = "連戦は -1 から 6 の範囲で指定してください。",
        ["Issue.FightTimesOutOfRange"] = "戦闘回数は 0 以上である必要があります。",
        ["Issue.FightDropMissing"] = "目標ドロップを有効にした場合はドロップ ID が必要です。",
        ["Issue.FightTimesMayNotExhausted"] = "現在の回数と連戦設定では回数を使い切れない可能性があります。",
        ["Issue.RecruitTimesOutOfRange"] = "公開求人回数は 0 以上である必要があります。",
        ["Issue.RecruitTimeOutOfRange"] = "公開求人時間は 60..540 かつ 10 分刻みで指定してください。",
        ["Issue.TaskFieldMissing"] = "設定に必須フィールドが不足しています。",
    };

    private static readonly Dictionary<string, string> KoKr = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "계정",
        ["StartUp.ClientType"] = "클라이언트",
        ["StartUp.StartGameEnabled"] = "게임 자동 시작",
        ["StartUp.ConnectConfig"] = "연결 프리셋",
        ["StartUp.ConnectAddress"] = "연결 주소",
        ["StartUp.AdbPath"] = "ADB 경로",
        ["StartUp.TouchMode"] = "터치 모드",
        ["StartUp.AutoDetect"] = "자동 감지",
        ["StartUp.AttachScreencap"] = "AttachWindow-스크린샷",
        ["StartUp.AttachMouse"] = "AttachWindow-터치",
        ["StartUp.AttachKeyboard"] = "AttachWindow-키보드",
        ["Fight.Title"] = "전투",
        ["Fight.Stage"] = "스테이지",
        ["Fight.UseMedicine"] = "이성약 사용",
        ["Fight.Medicine"] = "이성약 수",
        ["Fight.UseStone"] = "원석 사용",
        ["Fight.Stone"] = "원석 수",
        ["Fight.EnableTimesLimit"] = "횟수 제한",
        ["Fight.Times"] = "횟수",
        ["Fight.Series"] = "연전",
        ["Fight.UseExpiringMedicine"] = "만료 임박 이성약 사용",
        ["Fight.DrGrandet"] = "DrGrandet 모드",
        ["Fight.EnableTargetDrop"] = "목표 드랍",
        ["Fight.DropId"] = "드랍 ID",
        ["Fight.DropCount"] = "목표 수량",
        ["Fight.UseAlternateStage"] = "대체 스테이지",
        ["Fight.HideUnavailableStage"] = "미해금 스테이지 숨김",
        ["Fight.StageResetMode"] = "초기화 모드",
        ["Fight.UseCustomAnnihilation"] = "섬멸 커스텀",
        ["Fight.AnnihilationStage"] = "섬멸 스테이지",
        ["Recruit.Title"] = "공개채용",
        ["Recruit.Times"] = "횟수",
        ["Recruit.Refresh"] = "자동 새로고침",
        ["Recruit.ForceRefresh"] = "강제 새로고침",
        ["Recruit.UseExpedited"] = "가속권 사용",
        ["Recruit.SkipRobot"] = "로봇 태그 건너뛰기",
        ["Recruit.ChooseLevel3"] = "3성 선택",
        ["Recruit.ChooseLevel4"] = "4성 선택",
        ["Recruit.ChooseLevel5"] = "5성 선택",
        ["Recruit.SetTime"] = "시간 설정",
        ["Recruit.Level3Time"] = "3성 시간",
        ["Recruit.Level4Time"] = "4성 시간",
        ["Recruit.Level5Time"] = "5성 시간",
        ["Recruit.ExtraTagsMode"] = "추가 태그 모드",
        ["Recruit.FirstTags"] = "우선 태그",
        ["Common.LoadingTaskHint"] = "왼쪽 작업 목록에서 작업을 먼저 선택하세요.",
        ["Common.ValidationIssues"] = "검증 메시지",
        ["Common.WarningPrefix"] = "경고",
        ["Common.ErrorPrefix"] = "오류",
        ["Issue.ClientTypeMissing"] = "클라이언트 유형은 비워둘 수 없습니다.",
        ["Issue.FightStageMissing"] = "전투 스테이지는 비워둘 수 없습니다.",
        ["Issue.FightSeriesOutOfRange"] = "연전 값은 -1 에서 6 사이여야 합니다.",
        ["Issue.FightTimesOutOfRange"] = "전투 횟수는 0 이상이어야 합니다.",
        ["Issue.FightDropMissing"] = "목표 드랍 사용 시 드랍 ID가 필요합니다.",
        ["Issue.FightTimesMayNotExhausted"] = "현재 연전 설정에서 횟수가 남을 수 있습니다.",
        ["Issue.RecruitTimesOutOfRange"] = "공개채용 횟수는 0 이상이어야 합니다.",
        ["Issue.RecruitTimeOutOfRange"] = "공개채용 시간은 60..540 범위의 10분 단위여야 합니다.",
        ["Issue.TaskFieldMissing"] = "설정에 필수 필드가 누락되었습니다.",
    };

    private static readonly Dictionary<string, string> ZhTw = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "開始喚醒",
        ["StartUp.AccountName"] = "帳號",
        ["StartUp.ClientType"] = "客戶端",
        ["StartUp.StartGameEnabled"] = "自動啟動遊戲",
        ["StartUp.ConnectConfig"] = "連線預設",
        ["StartUp.ConnectAddress"] = "連線位址",
        ["StartUp.AdbPath"] = "ADB 路徑",
        ["StartUp.TouchMode"] = "觸控模式",
        ["StartUp.AutoDetect"] = "自動偵測連線",
        ["StartUp.AttachScreencap"] = "AttachWindow-截圖",
        ["StartUp.AttachMouse"] = "AttachWindow-觸控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-鍵盤",
        ["Fight.Title"] = "戰鬥",
        ["Fight.Stage"] = "關卡",
        ["Fight.UseMedicine"] = "使用理智藥",
        ["Fight.Medicine"] = "理智藥數量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石數量",
        ["Fight.EnableTimesLimit"] = "限制次數",
        ["Fight.Times"] = "次數",
        ["Fight.Series"] = "連戰",
        ["Fight.UseExpiringMedicine"] = "使用即將過期理智藥",
        ["Fight.DrGrandet"] = "理智策略 DrGrandet",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目標數量",
        ["Fight.UseAlternateStage"] = "啟用換圖",
        ["Fight.HideUnavailableStage"] = "隱藏不可用關卡",
        ["Fight.StageResetMode"] = "重置模式",
        ["Fight.UseCustomAnnihilation"] = "自訂剿滅",
        ["Fight.AnnihilationStage"] = "剿滅關卡",
        ["Recruit.Title"] = "公開招募",
        ["Recruit.Times"] = "招募次數",
        ["Recruit.Refresh"] = "自動刷新",
        ["Recruit.ForceRefresh"] = "強制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.SkipRobot"] = "跳過支援機械",
        ["Recruit.ChooseLevel3"] = "選擇 3 星",
        ["Recruit.ChooseLevel4"] = "選擇 4 星",
        ["Recruit.ChooseLevel5"] = "選擇 5 星",
        ["Recruit.SetTime"] = "設定時長",
        ["Recruit.Level3Time"] = "3 星時長",
        ["Recruit.Level4Time"] = "4 星時長",
        ["Recruit.Level5Time"] = "5 星時長",
        ["Recruit.ExtraTagsMode"] = "額外標籤策略",
        ["Recruit.FirstTags"] = "優先標籤",
        ["Common.LoadingTaskHint"] = "請先在左側任務列表中選擇對應任務。",
        ["Common.ValidationIssues"] = "校驗資訊",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "錯誤",
        ["Issue.ClientTypeMissing"] = "客戶端類型不能為空。",
        ["Issue.FightStageMissing"] = "戰鬥關卡不能為空。",
        ["Issue.FightSeriesOutOfRange"] = "連戰範圍需在 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "戰鬥次數不能小於 0。",
        ["Issue.FightDropMissing"] = "指定掉落時必須填寫掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "當前次數與連戰設定可能無法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次數不能小於 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募時長需在 60..540 且步長為 10。",
        ["Issue.TaskFieldMissing"] = "配置缺少必填欄位。",
    };

    private string _language = "zh-cn";

    public string Language
    {
        get => _language;
        set
        {
            if (!SetProperty(ref _language, value))
            {
                return;
            }

            OnPropertyChanged("Item[]");
        }
    }

    public string this[string key]
    {
        get
        {
            var source = ResolveSource(Language);
            if (source.TryGetValue(key, out var value))
            {
                return value;
            }

            if (EnUs.TryGetValue(key, out value))
            {
                return value;
            }

            if (ZhCn.TryGetValue(key, out value))
            {
                return value;
            }

            return key;
        }
    }

    public string GetOrDefault(string key, string fallback)
    {
        var value = this[key];
        return string.Equals(value, key, StringComparison.Ordinal) ? fallback : value;
    }

    private static Dictionary<string, string> ResolveSource(string language)
    {
        if (string.Equals(language, "en-us", StringComparison.OrdinalIgnoreCase))
        {
            return EnUs;
        }

        if (string.Equals(language, "ja-jp", StringComparison.OrdinalIgnoreCase))
        {
            return JaJp;
        }

        if (string.Equals(language, "ko-kr", StringComparison.OrdinalIgnoreCase))
        {
            return KoKr;
        }

        if (string.Equals(language, "zh-tw", StringComparison.OrdinalIgnoreCase))
        {
            return ZhTw;
        }

        return ZhCn;
    }
}
