using MAAUnified.App.ViewModels.Infrastructure;
using MAAUnified.Application.Services.Localization;
using System.Text.RegularExpressions;

namespace MAAUnified.App.ViewModels.TaskQueue;

public sealed class LocalizedTextMap : ObservableObject
{
    private static readonly Regex InlineKeyPattern = new(@"\{key=([^}]+)\}", RegexOptions.Compiled);

    private static readonly Dictionary<string, string> ZhCn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "基建",
        ["Infrast.Mode"] = "基建模式",
        ["Infrast.Mode.Normal"] = "默认排班",
        ["Infrast.Mode.Custom"] = "自定义排班",
        ["Infrast.Mode.Rotation"] = "轮换排班",
        ["Infrast.ModeRotationTip"] = "使用队列轮换需提前在游戏中设置好队列",
        ["Infrast.ModeRotationToolTip"] = "轮换排班会按照游戏内预设队列执行。",
        ["Infrast.Drones"] = "无人机策略",
        ["Infrast.Drone.NotUse"] = "不使用无人机",
        ["Infrast.Drone.Money"] = "龙门币",
        ["Infrast.Drone.SyntheticJade"] = "合成玉",
        ["Infrast.Drone.CombatRecord"] = "作战记录",
        ["Infrast.Drone.PureGold"] = "赤金",
        ["Infrast.Drone.OriginStone"] = "源石碎片",
        ["Infrast.Drone.Chip"] = "芯片",
        ["Infrast.Threshold"] = "宿舍阈值(%)",
        ["Infrast.ThresholdTip"] = "若启用自定义换班，该字段仅针对 autofill 和使用干员编组的房间有效",
        ["Infrast.File"] = "自定义基建文件",
        ["Infrast.Select"] = "选择",
        ["Infrast.Plan"] = "计划索引",
        ["Infrast.Plan.Auto"] = "自动(按时间轮换)",
        ["Infrast.Plan.AutoCurrent"] = "时间轮换（当前：{0}）",
        ["Infrast.Plan.Refresh"] = "刷新计划",
        ["Infrast.Plan.DefaultName"] = "计划 {0}",
        ["Infrast.Plan.Display"] = "{0}（{1} 个时段）",
        ["Infrast.CustomPlanToolTip"] = "若存在时间段信息，可选择“时间轮换”自动按当前时刻切换。",
        ["Infrast.DefaultPreset"] = "默认基建预设",
        ["Infrast.Default.UserDefined"] = "用户自定义",
        ["Infrast.Default.153Time3"] = "153（一天三换）",
        ["Infrast.Default.153Time4"] = "153（一天四换）",
        ["Infrast.Default.243Time3"] = "243（一天三换）",
        ["Infrast.Default.243Time4"] = "243（一天四换）",
        ["Infrast.Default.333Time3"] = "333（搓玉，一天三换）",
        ["Infrast.Facility"] = "房间顺序",
        ["Infrast.SelectAll"] = "全选",
        ["Infrast.Clear"] = "清空",
        ["Infrast.Advanced"] = "高级选项",
        ["Infrast.Trust"] = "宿舍信赖收取",
        ["Infrast.NotStationed"] = "过滤未入驻干员",
        ["Infrast.NotStationedTip"] = "勾选则不会将训练室干员移除，但加工站干员也不会进宿舍。",
        ["Infrast.ContinueTraining"] = "保留训练进度",
        ["Infrast.Replenish"] = "搓玉补货",
        ["Infrast.ReceptionBoard"] = "会客室板子领取",
        ["Infrast.ReceptionExchange"] = "线索交换",
        ["Infrast.ReceptionSend"] = "赠送线索",
        ["Infrast.Error.CustomFileNotFound"] = "自定义文件不存在：{0}",
        ["Infrast.Error.PlanOutOfRange"] = "计划索引 {0} 超出 `{1}` 范围。",
        ["Infrast.Error.ParseFailed"] = "解析自定义基建文件失败。",
        ["Infrast.Status.LoadedPlans"] = "已加载 {0} 个计划。",
        ["Mall.Title"] = "商店",
        ["Mall.VisitFriends"] = "访问好友",
        ["Mall.VisitOnce"] = "好友访问每日一次",
        ["Mall.OnlyOnceADay"] = "一日只执行一次",
        ["Mall.CreditFight"] = "借助战打 OF-1 赚信用",
        ["Mall.CreditFightOnce"] = "信用作战每日一次",
        ["Mall.CreditFightTip"] = "访问好友后借助战打一把 OF-1 赚 30 信用。\n关卡选择为 ｢当前/上次｣ 时此功能无效。\n别传 ｢火蓝之心｣ 关卡OF-1未解锁时请勿勾选。",
        ["Mall.Formation"] = "编队",
        ["Mall.Formation.Current"] = "当前",
        ["Mall.UseFormation"] = "使用编队",
        ["Mall.Shopping"] = "信用交易所自动购物",
        ["Mall.BuyFirst"] = "优先购买 子串即可 分号分隔",
        ["Mall.Blacklist"] = "黑名单 子串即可 分号分隔",
        ["Mall.Drink"] = "要来一杯美酒吗🍷？博士",
        ["Mall.ForceShopping"] = "信用溢出时无视黑名单",
        ["Mall.OnlyDiscount"] = "只购买打折的信用商品",
        ["Mall.OnlyDiscountTip"] = "⚠ 注意：可能会导致信用点数溢出！仍然会购买未打折的白名单物品！",
        ["Mall.Reserve"] = "信用点低于 300 时停止购买商品",
        ["Mall.ReserveTip"] = "低于 300 信用点也仍然会购买白名单物品！",
        ["Mall.ReceptionOptionsRequireInfrast"] = "以下功能需在基建中设置并执行",
        ["Mall.InfrastReceptionMessageBoardReceive"] = "会客室信息板收取信用",
        ["Mall.InfrastReceptionClueExchange"] = "进行线索交流",
        ["Mall.InfrastReceptionSendClue"] = "赠送线索",
        ["Award.Title"] = "奖励",
        ["Award.Award"] = "领取每日/每周任务奖励",
        ["Award.Mail"] = "领取所有邮件奖励",
        ["Award.Recruit"] = "进行限定池赠送的每日免费单抽",
        ["Award.RecruitTip"] = "该功能属于危险功能，可能会造成误抽。",
        ["Award.FreeGachaTip"] = "若不存在免费单抽，则不会抽取",
        ["Award.GachaWarning"] = "该功能属于危险功能，可能会造成误抽\n按下 ｢确认｣ 键即视为你了解并愿意承担可能出现的风险",
        ["Award.Confirm"] = "确认",
        ["Award.Cancel"] = "取消",
        ["Award.Orundum"] = "领取幸运墙的每日合成玉奖励",
        ["Award.Mining"] = "领取限时开采许可的每日合成玉奖励",
        ["Award.Special"] = "领取周年赠送月卡奖励",
        ["PostAction.Title"] = "后置动作",
        ["PostAction.Once"] = "一次性(本轮生效)",
        ["PostAction.OnceTip"] = "勾选后将不保存选项变化，下次 MAA 启动或 {key=LinkStart} 后复原\n取消勾选本选项后，其他选项状态将会正常保存\n右键点击其他选项时，会同步勾选/取消勾选本选项",
        ["PostAction.BackToHome"] = "返回模拟器首页",
        ["PostAction.ExitArknights"] = "退出游戏",
        ["PostAction.ExitEmulator"] = "关闭模拟器",
        ["PostAction.ExitSelf"] = "关闭 MAA",
        ["PostAction.IfNoOther"] = "仅无其他 MAA 时执行",
        ["PostAction.Sleep"] = "睡眠",
        ["PostAction.Hibernate"] = "休眠",
        ["PostAction.HibernateTip"] = "需在 Windows 电源选项中启用休眠功能，否则该功能无效。",
        ["PostAction.Shutdown"] = "关机",
        ["PostAction.Clear"] = "清空动作",
        ["PostAction.Unsupported"] = "该动作当前平台不支持，将降级为日志记录。",
        ["PostAction.Cmd.ExitArknights"] = "退出游戏命令",
        ["PostAction.Cmd.BackToHome"] = "返回首页命令",
        ["PostAction.Cmd.ExitEmulator"] = "关闭模拟器命令",
        ["PostAction.Cmd.ExitSelf"] = "关闭 MAA 命令",
        ["PostAction.Cmd.Watermark"] = "留空则仅记录降级日志",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "“仅无其他 MAA 时执行”需要至少勾选一个系统动作（睡眠/休眠/关机）。",
        ["PostAction.Warn.UnsupportedDowngrade"] = "当前选择包含不可执行动作，将降级为日志记录。",
        ["StartUp.Title"] = "开始唤醒",
        ["StartUp.AccountName"] = "账号",
        ["StartUp.AccountSwitch"] = "账号切换",
        ["StartUp.AccountSwitchManualRun"] = "立即切换",
        ["StartUp.AccountSwitchTip"] = "需要切换至的账号，留空以禁用。\n输入登录界面显示的内容，如 ｢123****4567｣，可输入 ｢123****4567｣ 或 ｢4567｣ 或 ｢23****45｣\n仅支持官服、B服，不支持登录账号。",
        ["StartUp.ClientType"] = "客户端",
        ["StartUp.StartGameEnabled"] = "是否启动客户端",
        ["StartUp.ConnectConfig"] = "连接预设",
        ["StartUp.ConnectAddress"] = "连接地址",
        ["StartUp.ConnectionAddressTip"] = "若遇到问题可尝试手动修改",
        ["StartUp.AdbPath"] = "ADB 路径",
        ["StartUp.Select"] = "选择",
        ["StartUp.TouchMode"] = "触控模式",
        ["StartUp.AutoDetect"] = "自动检测连接",
        ["StartUp.AutoDetectConnectionTip"] = "每次检测完成后会自动取消勾选，若需要重新检测可再次勾选，若反复连接失败可勾选始终自动检测连接",
        ["StartUp.AttachScreencap"] = "AttachWindow-截图",
        ["StartUp.AttachMouse"] = "AttachWindow-触控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-键盘",
        ["StartUp.Option.ClientType.Official"] = "官服",
        ["StartUp.Option.ClientType.Bilibili"] = "Bilibili服",
        ["StartUp.Option.ClientType.YoStarEN"] = "国际服 (YostarEN)",
        ["StartUp.Option.ClientType.YoStarJP"] = "日服 (YostarJP)",
        ["StartUp.Option.ClientType.YoStarKR"] = "韩服 (YostarKR)",
        ["StartUp.Option.ClientType.Txwy"] = "繁中服 (txwy)",
        ["StartUp.Option.ConnectConfig.General"] = "通用模式",
        ["StartUp.Option.ConnectConfig.BlueStacks"] = "蓝叠模拟器",
        ["StartUp.Option.ConnectConfig.MuMuEmulator12"] = "MuMu 模拟器",
        ["StartUp.Option.ConnectConfig.LDPlayer"] = "雷电模拟器",
        ["StartUp.Option.ConnectConfig.Nox"] = "夜神模拟器",
        ["StartUp.Option.ConnectConfig.XYAZ"] = "逍遥模拟器",
        ["StartUp.Option.ConnectConfig.PC"] = "PC 端",
        ["StartUp.Option.ConnectConfig.WSA"] = "WSA 旧版本",
        ["StartUp.Option.ConnectConfig.Compatible"] = "兼容模式",
        ["StartUp.Option.ConnectConfig.SecondResolution"] = "第二分辨率",
        ["StartUp.Option.ConnectConfig.GeneralWithoutScreencapErr"] = "通用模式（屏蔽异常输出）",
        ["StartUp.Option.TouchMode.MiniTouch"] = "Minitouch（默认）",
        ["StartUp.Option.TouchMode.MaaTouch"] = "MaaTouch",
        ["StartUp.Option.TouchMode.AdbTouch"] = "ADB Input（不推荐使用）",
        ["StartUp.Option.AttachScreencap.FramePool"] = "FramePool（默认，后台）",
        ["StartUp.Option.AttachScreencap.PrintWindow"] = "PrintWindow（后台，备用1）",
        ["StartUp.Option.AttachScreencap.ScreenDC"] = "ScreenDC（后台，备用2）",
        ["StartUp.Option.AttachScreencap.DesktopWindow"] = "DesktopWindow（前台，更稳定）",
        ["StartUp.Option.AttachInput.Seize"] = "Seize（前台，更稳定）",
        ["StartUp.Option.AttachInput.PostWithCursor"] = "PostMessageWithCursor（半后台）",
        ["StartUp.Option.AttachInput.SendWithCursor"] = "SendMessageWithCursor（半后台，备用）",
        ["StartUp.Option.AttachInput.PostWithWindowPos"] = "PostMessageWithWindowPos（后台窗口）",
        ["StartUp.Option.AttachInput.SendWithWindowPos"] = "SendMessageWithWindowPos（后台窗口，备用）",
        ["Fight.Title"] = "理智作战",
        ["Fight.Stage"] = "关卡",
        ["Fight.StageSelect"] = "关卡指定",
        ["Fight.UseMedicine"] = "使用药剂",
        ["Fight.UseStoneDisplay"] = "使用源石",
        ["Fight.Medicine"] = "理智药数量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石数量",
        ["Fight.EnableTimesLimit"] = "限制次数",
        ["Fight.PerformBattles"] = "指定次数",
        ["Fight.Times"] = "次数",
        ["Fight.Series"] = "代理倍率",
        ["Fight.SeriesTip"] = "• AUTO:\n自动识别关卡最大代理倍率, 保持最大代理倍率且使用理智药后理智不溢出\n\n• 数值 (1~6):\n按设定倍率执行代理\n若当前理智不足完成设定倍率 (如仅够 5 次但设为 6 倍), 则无法进入战斗\n或者\n战斗次数不足完成设定倍率 (如仅够 5 次但设为 6 倍), 也将无法进入战斗\n\n• 不切换:\n不调整游戏内代理倍率设定",
        ["Fight.UseExpiringMedicine"] = "无限吃 48 小时内过期的理智药",
        ["Fight.DrGrandet"] = "博朗台模式",
        ["Fight.DrGrandetTip"] = "在恢复理智确认界面等待，直到当前的 1 点理智恢复完成再立即确认。",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.AssignedMaterial"] = "指定材料",
        ["Fight.SpecifiedDropsTip"] = "该选项不会自动计算最优关卡",
        ["Fight.Drop.NotSelected"] = "不选择",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目标数量",
        ["Fight.UseAlternateStage"] = "使用备选关卡",
        ["Fight.HideUnavailableStage"] = "下拉框中隐藏当日不开放关卡",
        ["Fight.StageResetMode"] = "未开放关卡重置为",
        ["Fight.StageReset.Current"] = "当前/上次",
        ["Fight.StageReset.Ignore"] = "不切换",
        ["Fight.NotSwitch"] = "不切换",
        ["Fight.DefaultStage"] = "当前/上次",
        ["Fight.UseCustomAnnihilation"] = "自定义剿灭",
        ["Fight.AnnihilationStage"] = "剿灭关卡",
        ["Fight.Annihilation.Current"] = "当期剿灭",
        ["Fight.Annihilation.Chernobog"] = "切尔诺伯格",
        ["Fight.Annihilation.LungmenOutskirts"] = "龙门外环",
        ["Fight.Annihilation.LungmenDowntown"] = "龙门市区",
        ["Fight.HideSeries"] = "隐藏代理倍率",
        ["Fight.AllowUseStoneSave"] = "允许使用源石保存状态",
        ["Fight.AllowUseStoneSaveWarning"] = "该功能属于危险功能。按下 ｢确认｣ 键即视为你了解并愿意承担可能出现的风险。",
        ["Recruit.Title"] = "公开招募",
        ["Recruit.Times"] = "招募次数",
        ["Recruit.SelectStrategy"] = "额外标签策略",
        ["Recruit.Option.ExtraTags.Default"] = "默认不选择额外 Tag",
        ["Recruit.Option.ExtraTags.SelectAll"] = "选择高星时总是选择三个 Tag",
        ["Recruit.Option.ExtraTags.RareOnly"] = "尽可能多地选且只选高星 Tag",
        ["Recruit.Refresh"] = "自动刷新",
        ["Recruit.ForceRefresh"] = "强制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.UseExpeditedTip"] = "该开关与 WPF 保持一致：勾选后会优先消耗加急许可。",
        ["Recruit.SkipRobot"] = "跳过支援机械",
        ["Recruit.NotChooseLevel1"] = "不手动选择一星",
        ["Recruit.NotChooseLevel1Tip"] = "若识别出支援机械标签，将不会自动确认一星标签组合。",
        ["Recruit.ChooseLevel3"] = "选择 3 星",
        ["Recruit.ChooseLevel4"] = "选择 4 星",
        ["Recruit.ChooseLevel5"] = "选择 5 星",
        ["Recruit.AutoSelectLevel6"] = "自动选择 6 星",
        ["Recruit.SetTime"] = "设置时长",
        ["Recruit.Level3Time"] = "3 星时长",
        ["Recruit.Level4Time"] = "4 星时长",
        ["Recruit.Level5Time"] = "5 星时长",
        ["Recruit.ExtraTagsMode"] = "额外标签策略",
        ["Recruit.FirstTags"] = "优先标签",
        ["Recruit.HighPriorityTip"] = "优先标签按顺序尝试，和 WPF 一致使用游戏端标签内容。",
        ["Roguelike.Title"] = "肉鸽",
        ["Roguelike.Theme"] = "肉鸽主题",
        ["Roguelike.Mode"] = "策略",
        ["Roguelike.Difficulty"] = "难度",
        ["Roguelike.StartsCount"] = "开始探索 N 次后停止任务",
        ["Roguelike.Squad"] = "开局分队",
        ["Roguelike.Roles"] = "开局职业组",
        ["Roguelike.CoreChar"] = "开局干员",
        ["Roguelike.InvestmentEnabled"] = "投资源石锭",
        ["Roguelike.InvestmentWithMoreScore"] = "投资时招募、购物刷分",
        ["Roguelike.InvestmentsCount"] = "投资 N 个源石锭后停止任务",
        ["Roguelike.StopWhenInvestmentFull"] = "储备源石锭达到上限时停止",
        ["Roguelike.UseSupport"] = "｢{key=StartingCoreChar}｣ 使用助战",
        ["Roguelike.UseNonfriendSupport"] = "可以使用非好友助战",
        ["Roguelike.RefreshTraderWithDice"] = "使用骰子刷新商人",
        ["Roguelike.StopAtFinalBoss"] = "在第五层 BOSS 前暂停",
        ["Roguelike.StopAtMaxLevel"] = "满级后自动停止",
        ["Roguelike.CollectibleModeShopping"] = "刷开局模式启用购物",
        ["Roguelike.CollectibleModeSquad"] = "烧水使用分队",
        ["Roguelike.StartWithEliteTwo"] = "凹 ｢{key=StartingCoreChar}｣ 直升精二",
        ["Roguelike.OnlyStartWithEliteTwo"] = "只凹 ｢{key=StartingCoreChar}｣ 直升精二，不进行作战",
        ["Roguelike.Collectible.HotWater"] = "热水壶",
        ["Roguelike.Collectible.Shield"] = "盾",
        ["Roguelike.Collectible.Ingot"] = "锭",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "随机奖励",
        ["Roguelike.Collectible.Key"] = "钥匙",
        ["Roguelike.Collectible.Dice"] = "骰子",
        ["Roguelike.Collectible.Ideas"] = "构想",
        ["Roguelike.Collectible.Ticket"] = "票券",
        ["Roguelike.MonthlySquadAutoIterate"] = "月度小队自动切换",
        ["Roguelike.MonthlySquadCheckComms"] = "月度小队通讯",
        ["Roguelike.DeepExplorationAutoIterate"] = "深入调查自动切换",
        ["Roguelike.FindPlayTimeTarget"] = "目标常乐节点",
        ["Roguelike.FirstFloorFoldartal"] = "凹第一层远见密文板，不进行作战",
        ["Roguelike.StartFoldartalList"] = "生活队凹开局密文板",
        ["Roguelike.StartFoldartalTip"] = "最多写三个，并用英文分号 ｢;｣ 隔开",
        ["Roguelike.ExpectedCollapsalParadigms"] = "坍缩范式列表",
        ["Roguelike.ExpectedCollapsalParadigmsTip"] = "用英文分号 ｢;｣ 隔开，留空将使用默认列表。",
        ["Roguelike.StartWithSeed"] = "使用指定种子开局",
        ["Roguelike.JieGardenDifficultyTip"] = "解锁 ｢界园｣ 相关科技后，指挥分队在进行 N3 及以上难度探索时可利用 ｢一战一跳｣ 策略存钱。\n若尚未解锁该科技，请不要选择 N3 及以上难度（包括 MAX）。",
        ["Roguelike.CoreCharTip"] = "不填写则使用默认策略。",
        ["Roguelike.UseSupportTip"] = "需先填写 ｢{key=StartingCoreChar}｣",
        ["Roguelike.StartWithSelectList"] = "刷开局期望奖励",
        ["Roguelike.MultiTaskSharedTip"] = "以下选项为多任务共用",
        ["Roguelike.DelayAbortUntilCombatComplete"] = "自动肉鸽在战斗结束前延迟 ｢{key=Stop}｣ 动作",
        ["RoguelikeThemePhantom"] = "傀影",
        ["RoguelikeThemeMizuki"] = "水月",
        ["RoguelikeThemeSami"] = "萨米",
        ["RoguelikeThemeSarkaz"] = "萨卡兹",
        ["RoguelikeThemeJieGarden"] = "界园",
        ["RoguelikeStrategyExp"] = "刷等级，尽可能稳定地打更多层数",
        ["RoguelikeStrategyGold"] = "刷源石锭，投资完成后自动退出",
        ["RoguelikeStrategyLastReward"] = "刷开局，刷取热水壶或精二{key=Operator}开局",
        ["RoguelikeStrategyMonthlySquad"] = "刷月度小队，尽可能稳定地打更多层数",
        ["RoguelikeStrategyDeepExploration"] = "刷深入调查，尽可能稳定地打更多层数",
        ["RoguelikeStrategyFindPlaytime"] = "刷常乐节点，第一层进洞，找不到需要的节点就重开",
        ["RoguelikeStrategyCollapse"] = "刷坍缩范式，遇到非稀有坍缩范式后直接重开",
        ["RoguelikeCollectibleModeSquad"] = "烧水使用分队",
        ["RoguelikeFindPlaytimeTarget"] = "目标常乐节点",
        ["RoguelikePlaytimeLing"] = "令 - 掷地有声",
        ["RoguelikePlaytimeShu"] = "黍 - 种因得果",
        ["RoguelikePlaytimeNian"] = "年 - 三缺一",
        ["StartingSquad"] = "开局分队",
        ["StartingRoles"] = "开局职业组",
        ["StartingCoreChar"] = "开局{key=Operator}",
        ["StartingCoreCharTip"] = "不填写则使用默认策略。",
        ["FirstMoveAdvantage"] = "先手必胜（先锋、狙击、特种）",
        ["SlowAndSteadyWinsTheRace"] = "稳扎稳打（重装、术师、狙击）",
        ["OvercomingYourWeaknesses"] = "取长补短（近卫、辅助、医疗）",
        ["FlexibleDeployment"] = "灵活部署（先锋、辅助、特种）",
        ["Unbreakable"] = "坚不可摧（重装、术师、医疗）",
        ["AsYourHeartDesires"] = "随心所欲（三张随机）",
        ["GatheringSquad"] = "集群分队",
        ["SpearheadSquad"] = "矛头分队",
        ["ResearchSquad"] = "研究分队",
        ["IS2NewSquad1"] = "心胜于物分队",
        ["IS2NewSquad2"] = "物尽其用分队",
        ["IS2NewSquad3"] = "以人为本分队",
        ["IS3NewSquad1"] = "永恒狩猎分队",
        ["IS3NewSquad2"] = "生活至上分队",
        ["IS3NewSquad3"] = "科学主义分队",
        ["IS3NewSquad4"] = "特训分队",
        ["IS4NewSquad1"] = "魂灵护送分队",
        ["IS4NewSquad2"] = "博闻广记分队",
        ["IS4NewSquad3"] = "蓝图测绘分队",
        ["IS4NewSquad4"] = "因地制宜分队",
        ["IS4NewSquad5"] = "异想天开分队",
        ["IS4NewSquad6"] = "点刺成锭分队",
        ["IS4NewSquad7"] = "拟态学者分队",
        ["IS4NewSquad8"] = "专业人士分队",
        ["IS5NewSquad1"] = "高台突破分队",
        ["IS5NewSquad2"] = "地面突破分队",
        ["IS5NewSquad3"] = "游客分队",
        ["IS5NewSquad4"] = "司岁台分队",
        ["IS5NewSquad5"] = "天师府分队",
        ["IS5NewSquad6"] = "花团锦簇分队",
        ["IS5NewSquad7"] = "棋行险着分队",
        ["IS5NewSquad8"] = "岁影回音分队",
        ["IS5NewSquad9"] = "代理人分队",
        ["IS5NewSquad10"] = "知学分队",
        ["IS5NewSquad11"] = "商贾分队",
        ["SpecialForceSquad"] = "特勤分队",
        ["LeaderSquad"] = "指挥分队",
        ["SupportSquad"] = "后勤分队",
        ["TacticalAssaultOperative"] = "突击战术分队",
        ["TacticalFortificationOperative"] = "堡垒战术分队",
        ["TacticalRangedOperative"] = "远程战术分队",
        ["TacticalDestructionOperative"] = "破坏战术分队",
        ["First-ClassSquad"] = "高规格分队",
        ["NotSwitch"] = "不切换",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "生息演算主题",
        ["Reclamation.Mode"] = "策略",
        ["Reclamation.IncrementMode"] = "增加方式",
        ["Reclamation.NumCraftBatches"] = "单次最大组装轮数",
        ["Reclamation.ToolsToCraft"] = "支援道具名称列表",
        ["Reclamation.ClearStore"] = "任务完成后购买商店",
        ["Reclamation.EarlyTip"] = "目前生息演算的支持仍处于中期阶段，使用时请注意以下几点：\n\n通过开局刷点数：(小心已有存档被删除)\n1. 点数刷满后会输出 ｢任务完成｣，自动停止任务\n2. 不要在生息演算的编队中有干员的情况下使用\n3. 手动确认存档情况并删除，以免 MAA 删除你的珍贵存档\n4. 导航还没写，不能从生息演算以外的位置开始任务\n5. 如果任务过程中报错、点数没刷满就任务完成，请前往 GitHub 提交 issue\n\n有存档通过制造刷点数（高级设置）：\n1. 要求是结算后的第一天，且后续三天没有敌袭进入驻扎地\n2. 必须在进入大地图后的界面开始（能看到驻扎地的界面）\n3. 如果能制造的数量刚好是 99 的倍数会卡住，在存档前可以先用掉一点，这个之后再修",
        ["Reclamation.ToolToCraftTip"] = "支援道具名称",
        ["Reclamation.ToolToCraftPlaceholder"] = "荧光棒",
        ["Reclamation.Option.Theme.FireClosed"] = "沙中之火 (活动未开放)",
        ["Reclamation.Option.Theme.Tales"] = "沙洲遗闻",
        ["Reclamation.Option.Mode.NoArchive"] = "无存档，通过进出关卡刷生息点数",
        ["Reclamation.Option.Mode.Archive"] = "有存档，通过组装支援道具刷生息点数",
        ["Reclamation.Option.IncrementMode.Click"] = "连点",
        ["Reclamation.Option.IncrementMode.Hold"] = "长按",
        ["Custom.Title"] = "自定义任务",
        ["Custom.TaskNames"] = "任务名列表",
        ["Custom.TaskNamesPreview"] = "格式化预览",
        ["Common.LoadingTaskHint"] = "请先在左侧任务列表中选择对应任务。",
        ["Common.ValidationIssues"] = "校验信息",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "错误",
        ["TaskQueue.DailyStageHintDefault"] = "今日关卡信息将在资源加载后展示。",
        ["TaskQueue.OverlayDisconnected"] = "Overlay 未连接",
        ["TaskQueue.Error.SelectTaskToRemove"] = "请先选择要删除的任务。",
        ["TaskQueue.Error.SelectTaskToRename"] = "请先选择要重命名的任务。",
        ["TaskQueue.Error.SelectTaskToMove"] = "请先选择要移动的任务。",
        ["TaskQueue.Error.EditBlockedWhileRunning"] = "运行中禁止编辑任务队列。",
        ["TaskQueue.Validation.Clean"] = "校验通过。",
        ["TaskQueue.Validation.WarningCount"] = "存在 {0} 条预警。",
        ["TaskQueue.Validation.BlockingCount"] = "存在 {0} 条阻断错误。",
        ["TaskQueue.Validation.LoadFailed"] = "读取校验报告失败。",
        ["TaskQueue.Error.BlockingValidation"] = "任务 `{0}` 存在阻断校验项：{1}",
        ["Issue.ClientTypeMissing"] = "请选择客户端类型。",
        ["Issue.FightStageMissing"] = "请填写关卡名称。",
        ["Issue.FightSeriesOutOfRange"] = "连战次数只能填 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "战斗次数不能小于 0。",
        ["Issue.FightDropMissing"] = "开启指定掉落后，请填写掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "当前次数与连战设置可能无法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次数不能小于 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募时长只能填 60 到 540，且必须是 10 的倍数。",
        ["Issue.TaskFieldMissing"] = "有必填项没填完整，请检查当前设置。",
        ["Issue.TaskFieldTypeInvalid"] = "当前设置里有无效内容，请检查刚填写的选项。",
        ["Issue.DelimitedInputParseFailed"] = "输入格式不对，请用逗号、分号或换行分隔。",
        ["Issue.RoguelikeModeInvalid"] = "当前肉鸽模式暂不支持，请重新选择。",
        ["Issue.RoguelikeThemeUnknown"] = "未知主题，已降级为 JieGarden。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "难度不能小于 -1，已自动修正。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "开局次数不能小于 0，已自动修正。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投资次数不能小于 0，已自动修正。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "仅 Mizuki 主题支持骰子刷新商人，已自动关闭。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime 仅支持 JieGarden 主题，已自动降级。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目标范围应为 1..3，已自动修正。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "当前模式/主题/分队不支持开局精二，已自动关闭。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "仅开局精二依赖开局精二开关，已自动关闭。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "助战与开局精二冲突，已自动关闭开局精二。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "种子格式不对，请按 `<字母数字>,rogue_<id>,<step>` 填写。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "起始折纸列表超过 3 项，已截断。",
        ["Issue.ReclamationThemeUnknown"] = "生息主题未知，已降级为 Tales。",
        ["Issue.ReclamationModeInvalid"] = "当前生息模式暂不支持，请重新选择。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "增量模式仅支持 0/1，已自动修正。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "单次组装轮数应在 0..99999，已自动修正。",
        ["Issue.ReclamationToolNameInvalid"] = "支援道具列表格式不对，请按纯文本逐项填写。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "无存档模式会忽略工具列表，已清空。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存档模式会忽略清仓，已关闭。",
        ["Issue.CustomTaskNamesEmpty"] = "自定义任务名列表为空。",
        ["Issue.CustomTaskNameInvalid"] = "自定义任务名格式不对，请按纯文本逐项填写。",
        ["Issue.CustomTaskNameUnknown"] = "自定义任务名未识别，请确认拼写。",
        ["Issue.CustomTaskNamesNormalized"] = "自定义任务名已完成标准化和去重。",
    };

    private static readonly Dictionary<string, string> EnUs = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Infrast.Title"] = "Infrast",
        ["Infrast.Mode"] = "Mode",
        ["Infrast.Mode.Normal"] = "Default",
        ["Infrast.Mode.Custom"] = "Custom",
        ["Infrast.Mode.Rotation"] = "Rotation",
        ["Infrast.ModeRotationTip"] = "Please configure in-game preset queues before using rotation mode.",
        ["Infrast.ModeRotationToolTip"] = "Rotation mode follows queue presets configured in game.",
        ["Infrast.Drones"] = "Drones",
        ["Infrast.Drone.NotUse"] = "Do not use drones",
        ["Infrast.Drone.Money"] = "LMD",
        ["Infrast.Drone.SyntheticJade"] = "Originium shard",
        ["Infrast.Drone.CombatRecord"] = "Battle record",
        ["Infrast.Drone.PureGold"] = "Pure gold",
        ["Infrast.Drone.OriginStone"] = "Originium",
        ["Infrast.Drone.Chip"] = "Chip",
        ["Infrast.Threshold"] = "Dorm Threshold(%)",
        ["Infrast.ThresholdTip"] = "When custom shift is enabled, this field only affects autofill or grouped-operator rooms.",
        ["Infrast.File"] = "Custom Infrast File",
        ["Infrast.Select"] = "Select",
        ["Infrast.Plan"] = "Plan Index",
        ["Infrast.Plan.Auto"] = "Auto by time",
        ["Infrast.Plan.AutoCurrent"] = "Auto by time ({0})",
        ["Infrast.Plan.Refresh"] = "Reload Plans",
        ["Infrast.Plan.DefaultName"] = "Plan {0}",
        ["Infrast.Plan.Display"] = "{0} ({1} period)",
        ["Infrast.CustomPlanToolTip"] = "If periods exist in plan config, time-rotation can auto pick by current time.",
        ["Infrast.DefaultPreset"] = "Default Infrast Preset",
        ["Infrast.Default.UserDefined"] = "User defined",
        ["Infrast.Default.153Time3"] = "153 (3 shifts/day)",
        ["Infrast.Default.153Time4"] = "153 (4 shifts/day)",
        ["Infrast.Default.243Time3"] = "243 (3 shifts/day)",
        ["Infrast.Default.243Time4"] = "243 (4 shifts/day)",
        ["Infrast.Default.333Time3"] = "333 (orundum, 3 shifts/day)",
        ["Infrast.Facility"] = "Facility Order",
        ["Infrast.SelectAll"] = "Select All",
        ["Infrast.Clear"] = "Clear",
        ["Infrast.Advanced"] = "Advanced",
        ["Infrast.Trust"] = "Dorm trust",
        ["Infrast.NotStationed"] = "Filter stationed operators",
        ["Infrast.NotStationedTip"] = "Enabled: keep training-room operators, but workshop operators also will not enter dorms.",
        ["Infrast.ContinueTraining"] = "Continue training",
        ["Infrast.Replenish"] = "Originium replenish",
        ["Infrast.ReceptionBoard"] = "Reception board",
        ["Infrast.ReceptionExchange"] = "Clue exchange",
        ["Infrast.ReceptionSend"] = "Send clue",
        ["Infrast.Error.CustomFileNotFound"] = "Custom file not found: {0}",
        ["Infrast.Error.PlanOutOfRange"] = "Plan index {0} is out of range for `{1}`.",
        ["Infrast.Error.ParseFailed"] = "Failed to parse custom infrast file.",
        ["Infrast.Status.LoadedPlans"] = "Loaded {0} plans.",
        ["Mall.Title"] = "Mall",
        ["Mall.VisitFriends"] = "Visit friends",
        ["Mall.VisitOnce"] = "Visit friends once a day",
        ["Mall.OnlyOnceADay"] = "Only once a day",
        ["Mall.CreditFight"] = "Combat with Support to earn Credits",
        ["Mall.CreditFightOnce"] = "Credit fight once a day",
        ["Mall.CreditFightTip"] = "Combat with Support Unit in OF-1 after Visit Friends to earn 30 credits.\nThis function is invalid when stage is Cur/Last.\nDo not enable this when OF-1 is locked.",
        ["Mall.Formation"] = "Formation",
        ["Mall.Formation.Current"] = "Current",
        ["Mall.UseFormation"] = "Use formation",
        ["Mall.Shopping"] = "Credit shopping",
        ["Mall.BuyFirst"] = "Whitelist (split by semicolon)",
        ["Mall.Blacklist"] = "Blacklist (semicolon separated)",
        ["Mall.Drink"] = "Would you like a drink🍷? doctor",
        ["Mall.ForceShopping"] = "Ignore blacklist if credits overflow",
        ["Mall.OnlyDiscount"] = "Only purchase discounted credit items",
        ["Mall.OnlyDiscountTip"] = "⚠ Caution: Risk of credit overflow! Whitelisted non-discount items can still be purchased.",
        ["Mall.Reserve"] = "Stop purchasing items when credits below 300",
        ["Mall.ReserveTip"] = "Whitelisted items can still be purchased even when credit is below 300.",
        ["Mall.ReceptionOptionsRequireInfrast"] = "The following functions require configuration and execution in Infrast.",
        ["Mall.InfrastReceptionMessageBoardReceive"] = "Credit collection from message board in Reception Room",
        ["Mall.InfrastReceptionClueExchange"] = "Conduct Clue Exchange",
        ["Mall.InfrastReceptionSendClue"] = "Send Clues",
        ["Award.Title"] = "Award",
        ["Award.Award"] = "Collect daily/weekly mission rewards",
        ["Award.Mail"] = "Collect all mail rewards",
        ["Award.Recruit"] = "Conduct daily free single pull from the limited banner",
        ["Award.RecruitTip"] = "This is a high-risk option and may cause mis-pulls.",
        ["Award.FreeGachaTip"] = "If there is no free single pull, it will not be used.",
        ["Award.GachaWarning"] = "It's a dangerous feature and may result in a mis-pull.\nBy pressing ｢Confirm｣, you understand and accept the possible risks.",
        ["Award.Confirm"] = "Confirm",
        ["Award.Cancel"] = "Cancel",
        ["Award.Orundum"] = "Collect daily Orundum reward from Lucky Wall",
        ["Award.Mining"] = "Collect daily Orundum reward from mining permit",
        ["Award.Special"] = "Collect Special Access rewards",
        ["PostAction.Title"] = "Post Action",
        ["PostAction.Once"] = "Once for current run",
        ["PostAction.OnceTip"] = "When checked, option changes will not be saved and will revert the next time MAA starts or after {key=LinkStart}\nAfter unchecking this option, other option states will be saved normally\nRight-clicking other options will check/uncheck this option simultaneously",
        ["PostAction.BackToHome"] = "Back to emulator home",
        ["PostAction.ExitArknights"] = "Exit Arknights",
        ["PostAction.ExitEmulator"] = "Exit emulator",
        ["PostAction.ExitSelf"] = "Exit MAA",
        ["PostAction.IfNoOther"] = "Only if no other MAA",
        ["PostAction.Sleep"] = "Sleep",
        ["PostAction.Hibernate"] = "Hibernate",
        ["PostAction.HibernateTip"] = "You need to enable the hibernate feature in Windows power options, otherwise this feature will be invalid.",
        ["PostAction.Shutdown"] = "Shutdown",
        ["PostAction.Clear"] = "Clear",
        ["PostAction.Unsupported"] = "This action is unsupported on current platform and will be downgraded to logging.",
        ["PostAction.Cmd.ExitArknights"] = "Exit Arknights command",
        ["PostAction.Cmd.BackToHome"] = "Back to home command",
        ["PostAction.Cmd.ExitEmulator"] = "Exit emulator command",
        ["PostAction.Cmd.ExitSelf"] = "Exit MAA command",
        ["PostAction.Cmd.Watermark"] = "Leave empty to downgrade to logging only",
        ["PostAction.Warn.IfNoOtherNeedsSystemAction"] = "`IfNoOtherMaa` requires at least one system action (Sleep/Hibernate/Shutdown).",
        ["PostAction.Warn.UnsupportedDowngrade"] = "Some selected post actions are not executable and will be downgraded to logging.",
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "Account",
        ["StartUp.AccountSwitch"] = "Account Switch",
        ["StartUp.AccountSwitchManualRun"] = "Switch now",
        ["StartUp.AccountSwitchTip"] = "Fill in the account that needs to be switched to, leave blank to close the account switching.\nEnter the content displayed on the login interface, such as ｢123****4567｣, you can enter ｢123****4567｣ or ｢4567｣ or ｢23****45｣\nOnly supports Official(CN) and Bilibili server. Login account is not supported.",
        ["StartUp.ClientType"] = "Client Type",
        ["StartUp.StartGameEnabled"] = "Launch Client on Start",
        ["StartUp.ConnectConfig"] = "Connect preset",
        ["StartUp.ConnectAddress"] = "Connect address",
        ["StartUp.ConnectionAddressTip"] = "It will be filled in automatically when you use it for the first time. If you encounter any problems, you can try to manually modify it",
        ["StartUp.AdbPath"] = "ADB path",
        ["StartUp.Select"] = "Select",
        ["StartUp.TouchMode"] = "Touch mode",
        ["StartUp.AutoDetect"] = "Auto detect",
        ["StartUp.AutoDetectConnectionTip"] = "This checkbox will be automatically unchecked after each detect is completed, and can be checked again if you need to re-detect",
        ["StartUp.AttachScreencap"] = "AttachWindow - Screenshot",
        ["StartUp.AttachMouse"] = "AttachWindow - Touch",
        ["StartUp.AttachKeyboard"] = "AttachWindow - Keyboard",
        ["StartUp.Option.ClientType.Official"] = "Official (CN)",
        ["StartUp.Option.ClientType.Bilibili"] = "Bilibili",
        ["StartUp.Option.ClientType.YoStarEN"] = "YostarEN",
        ["StartUp.Option.ClientType.YoStarJP"] = "YostarJP",
        ["StartUp.Option.ClientType.YoStarKR"] = "YostarKR",
        ["StartUp.Option.ClientType.Txwy"] = "txwy",
        ["StartUp.Option.ConnectConfig.General"] = "General Mode",
        ["StartUp.Option.ConnectConfig.BlueStacks"] = "BlueStacks",
        ["StartUp.Option.ConnectConfig.MuMuEmulator12"] = "MuMu Emulator 12",
        ["StartUp.Option.ConnectConfig.LDPlayer"] = "LD Player",
        ["StartUp.Option.ConnectConfig.Nox"] = "Nox",
        ["StartUp.Option.ConnectConfig.XYAZ"] = "MEmu",
        ["StartUp.Option.ConnectConfig.PC"] = "PC Client",
        ["StartUp.Option.ConnectConfig.WSA"] = "Old version of WSA",
        ["StartUp.Option.ConnectConfig.Compatible"] = "Compatible Mode",
        ["StartUp.Option.ConnectConfig.SecondResolution"] = "2nd Resolution",
        ["StartUp.Option.ConnectConfig.GeneralWithoutScreencapErr"] = "General Mode (Blocked exception output)",
        ["StartUp.Option.TouchMode.MiniTouch"] = "Minitouch (Default)",
        ["StartUp.Option.TouchMode.MaaTouch"] = "MaaTouch",
        ["StartUp.Option.TouchMode.AdbTouch"] = "ADB Input (Deprecated)",
        ["StartUp.Option.AttachScreencap.FramePool"] = "FramePool (Default, Background)",
        ["StartUp.Option.AttachScreencap.PrintWindow"] = "PrintWindow (Background, Backup 1)",
        ["StartUp.Option.AttachScreencap.ScreenDC"] = "ScreenDC (Background, Backup 2)",
        ["StartUp.Option.AttachScreencap.DesktopWindow"] = "DesktopWindow (Foreground, More Stable)",
        ["StartUp.Option.AttachInput.Seize"] = "Seize (Foreground, More Stable)",
        ["StartUp.Option.AttachInput.PostWithCursor"] = "PostMessageWithCursor (Semi-background)",
        ["StartUp.Option.AttachInput.SendWithCursor"] = "SendMessageWithCursor (Semi-background, Backup)",
        ["StartUp.Option.AttachInput.PostWithWindowPos"] = "PostMessageWithWindowPos (Background Window)",
        ["StartUp.Option.AttachInput.SendWithWindowPos"] = "SendMessageWithWindowPos (Background Window, Backup)",
        ["Fight.Title"] = "Combat",
        ["Fight.Stage"] = "Stage",
        ["Fight.StageSelect"] = "Stage",
        ["Fight.UseMedicine"] = "Use Sanity Potion",
        ["Fight.UseStoneDisplay"] = "Use Originium",
        ["Fight.Medicine"] = "Medicine",
        ["Fight.UseStone"] = "Use stone",
        ["Fight.Stone"] = "Stone",
        ["Fight.EnableTimesLimit"] = "Enable times limit",
        ["Fight.PerformBattles"] = "Perform battles",
        ["Fight.Times"] = "Times",
        ["Fight.Series"] = "Series",
        ["Fight.SeriesTip"] = "• AUTO:\nAutomatically identify the maximum proxy multiplier of the level, maintain the maximum proxy multiplier and do not overflow sanity after using sanity potion\n\n• Value (1~6):\nExecute proxy according to the set multiplier\nIf the current sanity is not enough to complete the set multiplier (such as only enough for 5 times but set to 6 times), you cannot enter the battle\nOr\nIf the number of battles is not enough to complete the set multiplier (such as only enough for 5 times but set to 6 times), you will not be able to enter the battle\n\n• Don't Switch:\nDo not adjust the proxy multiplier setting in the game",
        ["Fight.UseExpiringMedicine"] = "Unlimited use of expiring (<48h) sanity potion",
        ["Fight.DrGrandet"] = "Dr. Grandet Mode",
        ["Fight.DrGrandetTip"] = "Wait on the sanity confirmation screen until the current sanity recovers to 1 point, then confirm immediately.",
        ["Fight.EnableTargetDrop"] = "Target drop",
        ["Fight.AssignedMaterial"] = "Material",
        ["Fight.SpecifiedDropsTip"] = "This feature does not auto-calculate optimal stage.",
        ["Fight.Drop.NotSelected"] = "Not selected",
        ["Fight.DropId"] = "Drop ID",
        ["Fight.DropCount"] = "Drop count",
        ["Fight.UseAlternateStage"] = "Use alternative stage",
        ["Fight.HideUnavailableStage"] = "Hide today's not open stages",
        ["Fight.StageResetMode"] = "Unopened stage is reset to",
        ["Fight.StageReset.Current"] = "Cur/Last",
        ["Fight.StageReset.Ignore"] = "Don't Switch",
        ["Fight.NotSwitch"] = "Don't Switch",
        ["Fight.DefaultStage"] = "Cur/Last",
        ["Fight.UseCustomAnnihilation"] = "Custom annihilation",
        ["Fight.AnnihilationStage"] = "Annihilation stage",
        ["Fight.Annihilation.Current"] = "Current Annihilation",
        ["Fight.Annihilation.Chernobog"] = "Chernobog",
        ["Fight.Annihilation.LungmenOutskirts"] = "Lungmen Outskirts",
        ["Fight.Annihilation.LungmenDowntown"] = "Lungmen Downtown",
        ["Fight.HideSeries"] = "Hide series",
        ["Fight.AllowUseStoneSave"] = "Save ｢Use Originium｣",
        ["Fight.AllowUseStoneSaveWarning"] = "This function is considered dangerous. Pressing the ｢Confirm｣ button indicates that you understand and are willing to accept the potential risks.",
        ["Recruit.Title"] = "Recruit",
        ["Recruit.Times"] = "Times",
        ["Recruit.SelectStrategy"] = "Extra tag strategy",
        ["Recruit.Option.ExtraTags.Default"] = "Additional Tags are not selected by default",
        ["Recruit.Option.ExtraTags.SelectAll"] = "If higher ★ tags appear, always select 3 tags",
        ["Recruit.Option.ExtraTags.RareOnly"] = "Pick as many high-star Tags as possible",
        ["Recruit.Refresh"] = "Refresh",
        ["Recruit.ForceRefresh"] = "Force refresh",
        ["Recruit.UseExpedited"] = "Use expedited",
        ["Recruit.UseExpeditedTip"] = "Same behavior as WPF: expedited permit is preferred when enabled.",
        ["Recruit.SkipRobot"] = "Skip robot",
        ["Recruit.NotChooseLevel1"] = "Do not manually pick 1-star",
        ["Recruit.NotChooseLevel1Tip"] = "When robot tag is detected, 1-star combinations will not be auto-confirmed.",
        ["Recruit.ChooseLevel3"] = "Choose 3-star",
        ["Recruit.ChooseLevel4"] = "Choose 4-star",
        ["Recruit.ChooseLevel5"] = "Choose 5-star",
        ["Recruit.AutoSelectLevel6"] = "Auto select 6-star",
        ["Recruit.SetTime"] = "Set time",
        ["Recruit.Level3Time"] = "3-star time",
        ["Recruit.Level4Time"] = "4-star time",
        ["Recruit.Level5Time"] = "5-star time",
        ["Recruit.ExtraTagsMode"] = "Extra tags mode",
        ["Recruit.FirstTags"] = "First tags",
        ["Recruit.HighPriorityTip"] = "High-priority tags follow WPF logic and use client-side recruit tags.",
        ["Roguelike.Title"] = "Roguelike",
        ["Roguelike.Theme"] = "I.S. Theme",
        ["Roguelike.Mode"] = "Strategy",
        ["Roguelike.Difficulty"] = "Difficulty",
        ["Roguelike.StartsCount"] = "Stops after starting N times",
        ["Roguelike.Squad"] = "Starting squad",
        ["Roguelike.Roles"] = "Starting roles",
        ["Roguelike.CoreChar"] = "Starting operator",
        ["Roguelike.InvestmentEnabled"] = "Invest coins",
        ["Roguelike.InvestmentWithMoreScore"] = "Investment with more score",
        ["Roguelike.InvestmentsCount"] = "Stops after investing N times",
        ["Roguelike.StopWhenInvestmentFull"] = "Stops when invested coins reach limit",
        ["Roguelike.UseSupport"] = "Select ｢{key=StartingCoreChar}｣ from support unit list",
        ["Roguelike.UseNonfriendSupport"] = "Enable non-friend support",
        ["Roguelike.RefreshTraderWithDice"] = "Refresh trader with dice",
        ["Roguelike.StopAtFinalBoss"] = "Stop before final boss",
        ["Roguelike.StopAtMaxLevel"] = "Stop when max level is achieved",
        ["Roguelike.CollectibleModeShopping"] = "Enable shopping in the grinding mode",
        ["Roguelike.CollectibleModeSquad"] = "Squad to get collectibles",
        ["Roguelike.StartWithEliteTwo"] = "Repeat for ｢{key=StartingCoreChar}｣ Elite 2",
        ["Roguelike.OnlyStartWithEliteTwo"] = "Only Repeat for ｢{key=StartingCoreChar}｣ Elite 2, No Battle",
        ["Roguelike.Collectible.HotWater"] = "Hot Water Kettle",
        ["Roguelike.Collectible.Shield"] = "Shield",
        ["Roguelike.Collectible.Ingot"] = "Ingot",
        ["Roguelike.Collectible.Hope"] = "Hope",
        ["Roguelike.Collectible.Random"] = "Random Reward",
        ["Roguelike.Collectible.Key"] = "Key",
        ["Roguelike.Collectible.Dice"] = "Dice",
        ["Roguelike.Collectible.Ideas"] = "Thought",
        ["Roguelike.Collectible.Ticket"] = "Coupon",
        ["Roguelike.MonthlySquadAutoIterate"] = "Monthly Squad Auto-Switch",
        ["Roguelike.MonthlySquadCheckComms"] = "Monthly Squad Communication",
        ["Roguelike.DeepExplorationAutoIterate"] = "Deep Investigation Auto-Switch",
        ["Roguelike.FindPlayTimeTarget"] = "Target playtime node",
        ["Roguelike.FirstFloorFoldartal"] = "Repeat for foldartal foreseed first floor, No Battle",
        ["Roguelike.StartFoldartalList"] = "Start with ｢Life Prioritizing Squad｣ and acquire the cypherboard",
        ["Roguelike.StartFoldartalTip"] = "Write up to three and separate with ｢;｣",
        ["Roguelike.ExpectedCollapsalParadigms"] = "Collapse Paradigm List",
        ["Roguelike.ExpectedCollapsalParadigmsTip"] = "Separate with ｢;｣. Leave blank to use the default list.",
        ["Roguelike.StartWithSeed"] = "Start with seed",
        ["Roguelike.JieGardenDifficultyTip"] = "For JieGarden, command-skip routing requires related tech unlock. Do not choose N3+ before unlocking.",
        ["Roguelike.CoreCharTip"] = "If not filled out, the default policy will be used.",
        ["Roguelike.UseSupportTip"] = "Please enter ｢{key=StartingCoreChar}｣ first",
        ["Roguelike.StartWithSelectList"] = "Grinding mode expected rewards",
        ["Roguelike.MultiTaskSharedTip"] = "The following options are for multiple tasks.",
        ["Roguelike.DelayAbortUntilCombatComplete"] = "Don't abort Auto IS until the end of battle",
        ["RoguelikeThemePhantom"] = "Phantom",
        ["RoguelikeThemeMizuki"] = "Mizuki",
        ["RoguelikeThemeSami"] = "Sami",
        ["RoguelikeThemeSarkaz"] = "Sarkaz",
        ["RoguelikeThemeJieGarden"] = "Sui's Garden",
        ["RoguelikeStrategyExp"] = "Gain Experience Points, clear as many nodes as possible",
        ["RoguelikeStrategyGold"] = "Invests coins, exits automatically after investment completes",
        ["RoguelikeStrategyLastReward"] = "Grind to obtain Hot Water Kettle or Elite 2 {key=Operator}s",
        ["RoguelikeStrategyMonthlySquad"] = "Grind Monthly Squad, clear as far as possible",
        ["RoguelikeStrategyDeepExploration"] = "Grind Deep Investigation, clear as far as possible",
        ["RoguelikeStrategyFindPlaytime"] = "Farm playtime nodes, enter the cave on the first floor, restart if target node not found",
        ["RoguelikeStrategyCollapse"] = "Farm collapse paradigms, restart immediately after encountering a non-rare collapse paradigm",
        ["RoguelikeCollectibleModeSquad"] = "Squad to get collectibles",
        ["RoguelikeFindPlaytimeTarget"] = "Target playtime node",
        ["RoguelikePlaytimeLing"] = "Ling - Resounding Words",
        ["RoguelikePlaytimeShu"] = "Shu - Reap What You Sow",
        ["RoguelikePlaytimeNian"] = "Nian - Mahjong Trio",
        ["StartingSquad"] = "Starting Squad",
        ["StartingRoles"] = "Starting Roles",
        ["StartingCoreChar"] = "Starting {key=Operator}",
        ["StartingCoreCharTip"] = "If not filled out, the default policy will be used.",
        ["FirstMoveAdvantage"] = "First Move Advantage (Vanguard, Sniper, Specialist)",
        ["SlowAndSteadyWinsTheRace"] = "Slow and Steady Wins the Race (Defender, Caster, Sniper)",
        ["OvercomingYourWeaknesses"] = "Overcoming Your Weaknesses (Guard, Supporter, Medic)",
        ["FlexibleDeployment"] = "Flexible Deployment (Vanguard, Supporter, Specialist)",
        ["Unbreakable"] = "Indestructible (Defender, Caster, Medic)",
        ["AsYourHeartDesires"] = "As Your Heart Desires (Random)",
        ["GatheringSquad"] = "Gathering Squad",
        ["SpearheadSquad"] = "Spearhead Squad",
        ["ResearchSquad"] = "Research Squad",
        ["IS2NewSquad1"] = "Mind Over Matter Squad",
        ["IS2NewSquad2"] = "Resourceful Squad",
        ["IS2NewSquad3"] = "People-Oriented Squad",
        ["IS3NewSquad1"] = "Eternal Hunting Squad",
        ["IS3NewSquad2"] = "Life Prioritizing Squad",
        ["IS3NewSquad3"] = "Scientific Thinking",
        ["IS3NewSquad4"] = "Special Training Squad",
        ["IS4NewSquad1"] = "Soul Escort Squad",
        ["IS4NewSquad2"] = "Erudite Squad",
        ["IS4NewSquad3"] = "Blueprint Squad",
        ["IS4NewSquad4"] = "Improvisation Squad",
        ["IS4NewSquad5"] = "Mimic Squad",
        ["IS4NewSquad6"] = "Ingots Squad",
        ["IS4NewSquad7"] = "Collection Squad",
        ["IS4NewSquad8"] = "Top Gun Squad",
        ["IS5NewSquad1"] = "High Ground Breaching Squad",
        ["IS5NewSquad2"] = "Ground Breaching Squad",
        ["IS5NewSquad3"] = "Tourist Squad",
        ["IS5NewSquad4"] = "Sui Regulator Squad",
        ["IS5NewSquad5"] = "Tianshi Bureau Squad",
        ["IS5NewSquad6"] = "Cluster of Blooms Squad",
        ["IS5NewSquad7"] = "Daring Gambit Squad",
        ["IS5NewSquad8"] = "Echoes of Time Squad",
        ["IS5NewSquad9"] = "Agent Squad",
        ["IS5NewSquad10"] = "Knowledge Squad",
        ["IS5NewSquad11"] = "Merchant Squad",
        ["SpecialForceSquad"] = "Special Squad",
        ["LeaderSquad"] = "Leader Squad",
        ["SupportSquad"] = "Support Squad",
        ["TacticalAssaultOperative"] = "Tactical Assault Squad",
        ["TacticalFortificationOperative"] = "Tactical Fortification Squad",
        ["TacticalRangedOperative"] = "Tactical Ranged Squad",
        ["TacticalDestructionOperative"] = "Tactical Destruction Squad",
        ["First-ClassSquad"] = "First-Class Squad",
        ["NotSwitch"] = "Don't Switch",
        ["Reclamation.Title"] = "Reclamation",
        ["Reclamation.Theme"] = "Reclamation Algorithm Theme",
        ["Reclamation.Mode"] = "Strategy",
        ["Reclamation.IncrementMode"] = "Increment Mode",
        ["Reclamation.NumCraftBatches"] = "Max Craft Count Per Round",
        ["Reclamation.ToolsToCraft"] = "Support prop list",
        ["Reclamation.ClearStore"] = "Clear Store after finished",
        ["Reclamation.EarlyTip"] = "The support for reclamation algorithm is still under development at present. Please mind the following:\n\nFarm points through initial setup: (Be careful that existing save files might be deleted)\n1. After reaching the maximum points, it will output ｢Task Completed｣ and automatically stop the task.\n2. Cannot be used when squads are not empty (simply clear the current squad).\n3. Manually check and delete save files to prevent MAA from deleting your valuable saves.\n4. Navigation is not yet implemented, so the task cannot be started from locations outside the Reclamation mode.\n5. If an error occurs during the task or the task completes without reaching the maximum points, please submit an issue on GitHub.\n\nWith save file: farm points through crafting (advanced).\n1. It must be the first day after settlement, and there should be no enemy attacks entering the stationed area for the next three days.\n2. It must start after entering the interface of the large map. (stationed location needs to be visible)\n3. If the quantity that can be manufactured is exactly a multiple of 99, MAA can get confused (stuck). You can use up a little before saving. This might be repaired later.",
        ["Reclamation.ToolToCraftTip"] = "Support prop name",
        ["Reclamation.ToolToCraftPlaceholder"] = "Glow Stick",
        ["Reclamation.Option.Theme.FireClosed"] = "Fire Within the Sand (The event is not open)",
        ["Reclamation.Option.Theme.Tales"] = "Tales Within the Sand",
        ["Reclamation.Option.Mode.NoArchive"] = "I do not have a save, let's farm prosperity points by repeatedly entering and exiting stages.",
        ["Reclamation.Option.Mode.Archive"] = "I do have a save, let's farm prosperity points by crafting tools.",
        ["Reclamation.Option.IncrementMode.Click"] = "Click",
        ["Reclamation.Option.IncrementMode.Hold"] = "Hold",
        ["Custom.Title"] = "Custom",
        ["Custom.TaskNames"] = "Task names",
        ["Custom.TaskNamesPreview"] = "Preview",
        ["Common.LoadingTaskHint"] = "Select a task from the left list first.",
        ["Common.ValidationIssues"] = "Validation Issues",
        ["Common.WarningPrefix"] = "Warning",
        ["Common.ErrorPrefix"] = "Error",
        ["TaskQueue.DailyStageHintDefault"] = "Daily stage hints will be shown after resources are loaded.",
        ["TaskQueue.OverlayDisconnected"] = "Overlay disconnected",
        ["TaskQueue.Error.SelectTaskToRemove"] = "Select a task to remove first.",
        ["TaskQueue.Error.SelectTaskToRename"] = "Select a task to rename first.",
        ["TaskQueue.Error.SelectTaskToMove"] = "Select a task to move first.",
        ["TaskQueue.Error.EditBlockedWhileRunning"] = "Task queue editing is blocked while running.",
        ["TaskQueue.Validation.Clean"] = "Validation passed.",
        ["TaskQueue.Validation.WarningCount"] = "{0} warning issue(s).",
        ["TaskQueue.Validation.BlockingCount"] = "{0} blocking issue(s).",
        ["TaskQueue.Validation.LoadFailed"] = "Failed to load validation report.",
        ["TaskQueue.Error.BlockingValidation"] = "Task `{0}` blocked by validation: {1}",
        ["Issue.ClientTypeMissing"] = "Choose a client type.",
        ["Issue.FightStageMissing"] = "Enter a stage name.",
        ["Issue.FightSeriesOutOfRange"] = "Fight series must be between -1 and 6.",
        ["Issue.FightTimesOutOfRange"] = "Fight times cannot be less than 0.",
        ["Issue.FightDropMissing"] = "Enter a drop id when target drop is enabled.",
        ["Issue.FightTimesMayNotExhausted"] = "Times may not be fully exhausted under current series.",
        ["Issue.RecruitTimesOutOfRange"] = "Recruit times cannot be less than 0.",
        ["Issue.RecruitTimeOutOfRange"] = "Recruit time must be between 60 and 540, in 10-minute steps.",
        ["Issue.TaskFieldMissing"] = "Some required settings are missing. Please check this task.",
        ["Issue.TaskFieldTypeInvalid"] = "Some settings use an invalid value. Please check the options you just edited.",
        ["Issue.DelimitedInputParseFailed"] = "Input format is invalid. Use commas, semicolons, or line breaks to separate items.",
        ["Issue.RoguelikeModeInvalid"] = "This roguelike mode is not supported. Choose another mode.",
        ["Issue.RoguelikeThemeUnknown"] = "Unknown roguelike theme, fallback to JieGarden.",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "Difficulty must be >= -1 and was normalized.",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "Starts count must be >= 0 and was normalized.",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "Investments count must be >= 0 and was normalized.",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "Refresh trader with dice only works on Mizuki; auto-disabled.",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime requires JieGarden; fallback applied.",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime target must be in 1..3 and was normalized.",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "StartWithEliteTwo is invalid for current mode/theme/squad and was disabled.",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "OnlyStartWithEliteTwo requires StartWithEliteTwo; auto-disabled.",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "UseSupport conflicts with StartWithEliteTwo; elite-two start was disabled.",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "Seed format is invalid. Use `<alnum>,rogue_<id>,<step>`.",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "Start foldartal list exceeded 3 items and was trimmed.",
        ["Issue.ReclamationThemeUnknown"] = "Unknown reclamation theme, fallback to Tales.",
        ["Issue.ReclamationModeInvalid"] = "This reclamation mode is not supported. Choose another mode.",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "Increment mode must be 0 or 1 and was normalized.",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "NumCraftBatches must be in 0..99999 and was normalized.",
        ["Issue.ReclamationToolNameInvalid"] = "Tool list format is invalid. Enter one tool name per item in plain text.",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "ToolsToCraft is ignored in no-archive mode and was cleared.",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "ClearStore is ignored in archive mode and was disabled.",
        ["Issue.CustomTaskNamesEmpty"] = "Custom task names list is empty.",
        ["Issue.CustomTaskNameInvalid"] = "Custom task name format is invalid. Enter plain text task names only.",
        ["Issue.CustomTaskNameUnknown"] = "Custom task name is not recognized.",
        ["Issue.CustomTaskNamesNormalized"] = "Custom task names were normalized and deduplicated.",
    };

    private static readonly Dictionary<string, string> JaJp = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "アカウント",
        ["StartUp.AccountSwitch"] = "アカウントの切り替え",
        ["StartUp.AccountSwitchManualRun"] = "今すぐ切り替える",
        ["StartUp.AccountSwitchTip"] = "切り替える必要があるアカウントを入力し、空白のままにしてアカウントの切り替えを完了します。\nログインインターフェイスに表示される内容を入力します（「123****4567」など）。「123****4567」または「4567」または「23****45」を入力できます。\n公式(CN)とBilibiliサーバーのみをサポートします。 ログインアカウントはサポートされていません。",
        ["StartUp.ClientType"] = "クライアント",
        ["StartUp.StartGameEnabled"] = "起動時にクライアントを開始する",
        ["StartUp.ConnectConfig"] = "接続プリセット",
        ["StartUp.ConnectAddress"] = "接続アドレス",
        ["StartUp.ConnectionAddressTip"] = "問題があれば手動で修正してください",
        ["StartUp.AdbPath"] = "ADB パス",
        ["StartUp.Select"] = "選択",
        ["StartUp.TouchMode"] = "タッチモード",
        ["StartUp.AutoDetect"] = "自動検出",
        ["StartUp.AutoDetectConnectionTip"] = "このチェックボックスは、検出が完了するたびに自動的にチェックが外れますが、再検出が必要な場合は再度チェックを入れることができます",
        ["StartUp.AttachScreencap"] = "AttachWindow-スクショ",
        ["StartUp.AttachMouse"] = "AttachWindow-タッチ",
        ["StartUp.AttachKeyboard"] = "AttachWindow-キーボード",
        ["Fight.Title"] = "作戦",
        ["Fight.Stage"] = "ステージ",
        ["Fight.UseMedicine"] = "理性剤を使う",
        ["Fight.Medicine"] = "理性剤数",
        ["Fight.UseStone"] = "源石を使う",
        ["Fight.Stone"] = "源石数",
        ["Fight.EnableTimesLimit"] = "回数制限",
        ["Fight.Times"] = "回数",
        ["Fight.Series"] = "連戦",
        ["Fight.UseExpiringMedicine"] = "期限切れ間近理性剤",
        ["Fight.DrGrandet"] = "DrGrandet モード",
        ["Fight.EnableTargetDrop"] = "目標ドロップ",
        ["Fight.DropId"] = "ドロップ ID",
        ["Fight.DropCount"] = "目標数",
        ["Fight.UseAlternateStage"] = "代替ステージ",
        ["Fight.HideUnavailableStage"] = "未開放ステージを非表示",
        ["Fight.StageResetMode"] = "日替わりリセット",
        ["Fight.UseCustomAnnihilation"] = "殲滅カスタム",
        ["Fight.AnnihilationStage"] = "殲滅ステージ",
        ["Recruit.Title"] = "公開求人",
        ["Recruit.Times"] = "回数",
        ["Recruit.Refresh"] = "自動更新",
        ["Recruit.ForceRefresh"] = "強制更新",
        ["Recruit.UseExpedited"] = "即時完了を使用",
        ["Recruit.SkipRobot"] = "ロボタグをスキップ",
        ["Recruit.ChooseLevel3"] = "3★を選択",
        ["Recruit.ChooseLevel4"] = "4★を選択",
        ["Recruit.ChooseLevel5"] = "5★を選択",
        ["Recruit.SetTime"] = "時間を設定",
        ["Recruit.Level3Time"] = "3★時間",
        ["Recruit.Level4Time"] = "4★時間",
        ["Recruit.Level5Time"] = "5★時間",
        ["Recruit.ExtraTagsMode"] = "追加タグモード",
        ["Recruit.FirstTags"] = "優先タグ",
        ["Roguelike.Title"] = "ローグライク",
        ["Roguelike.Theme"] = "テーマ",
        ["Roguelike.Mode"] = "モード",
        ["Roguelike.Difficulty"] = "難易度",
        ["Roguelike.StartsCount"] = "開始回数",
        ["Roguelike.Squad"] = "分隊",
        ["Roguelike.Roles"] = "職分",
        ["Roguelike.CoreChar"] = "中核オペ",
        ["Roguelike.InvestmentEnabled"] = "投資を有効化",
        ["Roguelike.InvestmentWithMoreScore"] = "投資で得点優先",
        ["Roguelike.InvestmentsCount"] = "投資回数",
        ["Roguelike.StopWhenInvestmentFull"] = "投資満了で停止",
        ["Roguelike.UseSupport"] = "「{key=StartingCoreChar}」をサポートから選択",
        ["Roguelike.UseNonfriendSupport"] = "非フレサポート使用",
        ["Roguelike.RefreshTraderWithDice"] = "サイコロで商人更新",
        ["Roguelike.StopAtFinalBoss"] = "第5階層のボスの手前で一時停止する",
        ["Roguelike.StopAtMaxLevel"] = "最大レベル達成時に停止",
        ["Roguelike.CollectibleModeShopping"] = "支援選択を得るモードで、ショッピング有効化",
        ["Roguelike.CollectibleModeSquad"] = "支援選択を得るモードの分隊",
        ["Roguelike.StartWithEliteTwo"] = "「{key=StartingCoreChar}」直接昇進",
        ["Roguelike.OnlyStartWithEliteTwo"] = "「{key=StartingCoreChar}」の昇進招集までリセマラし、戦闘を行わない",
        ["Roguelike.Collectible.HotWater"] = "お湯",
        ["Roguelike.Collectible.Shield"] = "シールド",
        ["Roguelike.Collectible.Ingot"] = "インゴット",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "ランダム",
        ["Roguelike.Collectible.Key"] = "鍵",
        ["Roguelike.Collectible.Dice"] = "サイコロ",
        ["Roguelike.Collectible.Ideas"] = "発想",
        ["Roguelike.Collectible.Ticket"] = "チケット",
        ["Roguelike.MonthlySquadAutoIterate"] = "月次小隊自動切替",
        ["Roguelike.MonthlySquadCheckComms"] = "月次小隊通信",
        ["Roguelike.DeepExplorationAutoIterate"] = "多面調査自動切替",
        ["Roguelike.FindPlayTimeTarget"] = "目標プレイ時間",
        ["Roguelike.FirstFloorFoldartal"] = "第一層遠見で指定された啓示板を取得し、戦闘を行わない",
        ["Roguelike.StartFoldartalList"] = "生活重視分隊で開始、指定された啓示板を取得する",
        ["Roguelike.ExpectedCollapsalParadigms"] = "崩壊パラダイムリスト",
        ["Roguelike.StartWithSeed"] = "シードから始める",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "テーマ",
        ["Reclamation.Mode"] = "モード",
        ["Reclamation.IncrementMode"] = "増分モード",
        ["Reclamation.NumCraftBatches"] = "クラフト回数",
        ["Reclamation.ToolsToCraft"] = "クラフト対象",
        ["Reclamation.ClearStore"] = "倉庫整理",
        ["Custom.Title"] = "カスタム",
        ["Custom.TaskNames"] = "タスク名リスト",
        ["Custom.TaskNamesPreview"] = "プレビュー",
        ["Common.LoadingTaskHint"] = "左側のタスクリストから対象タスクを選択してください。",
        ["Common.ValidationIssues"] = "検証メッセージ",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "エラー",
        ["TaskQueue.Validation.Clean"] = "検証に合格しました。",
        ["TaskQueue.Validation.WarningCount"] = "警告が {0} 件あります。",
        ["TaskQueue.Validation.BlockingCount"] = "ブロッキングエラーが {0} 件あります。",
        ["TaskQueue.Validation.LoadFailed"] = "検証レポートの読み込みに失敗しました。",
        ["TaskQueue.Error.BlockingValidation"] = "タスク `{0}` は検証でブロックされました: {1}",
        ["Issue.ClientTypeMissing"] = "クライアント種別は必須です。",
        ["Issue.FightStageMissing"] = "戦闘ステージは必須です。",
        ["Issue.FightSeriesOutOfRange"] = "連戦は -1 から 6 の範囲で指定してください。",
        ["Issue.FightTimesOutOfRange"] = "戦闘回数は 0 以上である必要があります。",
        ["Issue.FightDropMissing"] = "目標ドロップを有効にした場合はドロップ ID が必要です。",
        ["Issue.FightTimesMayNotExhausted"] = "現在の回数と連戦設定では回数を使い切れない可能性があります。",
        ["Issue.RecruitTimesOutOfRange"] = "公開求人回数は 0 以上である必要があります。",
        ["Issue.RecruitTimeOutOfRange"] = "公開求人時間は 60..540 かつ 10 分刻みで指定してください。",
        ["Issue.TaskFieldMissing"] = "設定に必須フィールドが不足しています。",
        ["Issue.TaskFieldTypeInvalid"] = "フィールド型が不正で解析できません。",
        ["Issue.DelimitedInputParseFailed"] = "構造化データ風の入力です。区切り文字付きテキストで入力してください。",
        ["Issue.RoguelikeModeInvalid"] = "ローグライクモードが未対応です。",
        ["Issue.RoguelikeThemeUnknown"] = "テーマが不明のため JieGarden にフォールバックしました。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "難易度は -1 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "開始回数は 0 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投資回数は 0 以上である必要があり、自動補正されました。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "サイコロ更新は Mizuki のみ対応のため無効化しました。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime は JieGarden 必須のためフォールバックしました。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目標は 1..3 の範囲で自動補正されました。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "現在のモード/テーマ/分隊では初手昇進2を無効化しました。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "初手昇進2のみは初手昇進2有効時のみ有効です。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "サポート使用と初手昇進2が競合したため昇進2を無効化しました。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "シード形式が不正です。`<英数字>,rogue_<id>,<step>` を使用してください。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "開始フォルダータルは 3 件までのため切り詰めました。",
        ["Issue.ReclamationThemeUnknown"] = "生息演算テーマが不明のため Tales にフォールバックしました。",
        ["Issue.ReclamationModeInvalid"] = "生息演算モードが未対応です。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "増分モードは 0/1 のみ対応で自動補正されました。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "クラフト回数は 0..99999 に自動補正されました。",
        ["Issue.ReclamationToolNameInvalid"] = "クラフト対象に解析不能な構造化トークンが含まれています。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "無存档モードではクラフト対象を無視するため削除しました。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存档モードでは清倉が無効のためオフにしました。",
        ["Issue.CustomTaskNamesEmpty"] = "カスタムタスク名リストが空です。",
        ["Issue.CustomTaskNameInvalid"] = "カスタムタスク名に解析不能な構造化トークンがあります。",
        ["Issue.CustomTaskNameUnknown"] = "カスタムタスク名が未認識です。",
        ["Issue.CustomTaskNamesNormalized"] = "カスタムタスク名を正規化・重複排除しました。",
    };

    private static readonly Dictionary<string, string> KoKr = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "StartUp",
        ["StartUp.AccountName"] = "계정",
        ["StartUp.AccountSwitch"] = "계정 전환",
        ["StartUp.AccountSwitchManualRun"] = "수동 스위치",
        ["StartUp.AccountSwitchTip"] = "전환할 계정을 입력하고, 계정 전환을 종료하려면 공백으로 남겨두세요.\n｢123****4567｣ 과 같이 로그인 인터페이스에 표시된 내용을 입력하세요. ｢123****4567｣, ｢4567｣ 또는 ｢23****45｣ 를 입력할 수 있습니다.\n공식(CN) 및 Bilibili 서버만 지원합니다. 로그인 계정은 지원되지 않습니다.",
        ["StartUp.ClientType"] = "클라이언트",
        ["StartUp.StartGameEnabled"] = "시작 시 클라이언트 실행",
        ["StartUp.ConnectConfig"] = "연결 프리셋",
        ["StartUp.ConnectAddress"] = "연결 주소",
        ["StartUp.ConnectionAddressTip"] = "문제 발생 시 직접 수정해 주세요",
        ["StartUp.AdbPath"] = "ADB 경로",
        ["StartUp.Select"] = "선택",
        ["StartUp.TouchMode"] = "터치 모드",
        ["StartUp.AutoDetect"] = "자동 감지",
        ["StartUp.AutoDetectConnectionTip"] = "이 체크박스는 감지가 끝나면 자동으로 체크가 해제됩니다. 다시 감지하려면 다시 체크해주세요",
        ["StartUp.AttachScreencap"] = "AttachWindow-스크린샷",
        ["StartUp.AttachMouse"] = "AttachWindow-터치",
        ["StartUp.AttachKeyboard"] = "AttachWindow-키보드",
        ["Fight.Title"] = "이성 사용",
        ["Fight.Stage"] = "스테이지",
        ["Fight.UseMedicine"] = "이성약 사용",
        ["Fight.Medicine"] = "이성약 수",
        ["Fight.UseStone"] = "원석 사용",
        ["Fight.Stone"] = "원석 수",
        ["Fight.EnableTimesLimit"] = "횟수 제한",
        ["Fight.Times"] = "횟수",
        ["Fight.Series"] = "연전",
        ["Fight.UseExpiringMedicine"] = "만료 임박 이성약 사용",
        ["Fight.DrGrandet"] = "DrGrandet 모드",
        ["Fight.EnableTargetDrop"] = "목표 드랍",
        ["Fight.DropId"] = "드랍 ID",
        ["Fight.DropCount"] = "목표 수량",
        ["Fight.UseAlternateStage"] = "대체 스테이지",
        ["Fight.HideUnavailableStage"] = "미해금 스테이지 숨김",
        ["Fight.StageResetMode"] = "초기화 모드",
        ["Fight.UseCustomAnnihilation"] = "섬멸 커스텀",
        ["Fight.AnnihilationStage"] = "섬멸 스테이지",
        ["Recruit.Title"] = "공개채용",
        ["Recruit.Times"] = "횟수",
        ["Recruit.Refresh"] = "자동 새로고침",
        ["Recruit.ForceRefresh"] = "강제 새로고침",
        ["Recruit.UseExpedited"] = "가속권 사용",
        ["Recruit.SkipRobot"] = "로봇 태그 건너뛰기",
        ["Recruit.ChooseLevel3"] = "3성 선택",
        ["Recruit.ChooseLevel4"] = "4성 선택",
        ["Recruit.ChooseLevel5"] = "5성 선택",
        ["Recruit.SetTime"] = "시간 설정",
        ["Recruit.Level3Time"] = "3성 시간",
        ["Recruit.Level4Time"] = "4성 시간",
        ["Recruit.Level5Time"] = "5성 시간",
        ["Recruit.ExtraTagsMode"] = "추가 태그 모드",
        ["Recruit.FirstTags"] = "우선 태그",
        ["Roguelike.Title"] = "로그라이크",
        ["Roguelike.Theme"] = "테마",
        ["Roguelike.Mode"] = "모드",
        ["Roguelike.Difficulty"] = "난이도",
        ["Roguelike.StartsCount"] = "시작 횟수",
        ["Roguelike.Squad"] = "분대",
        ["Roguelike.Roles"] = "직군",
        ["Roguelike.CoreChar"] = "핵심 오퍼레이터",
        ["Roguelike.InvestmentEnabled"] = "투자 사용",
        ["Roguelike.InvestmentWithMoreScore"] = "점수 우선 투자",
        ["Roguelike.InvestmentsCount"] = "투자 횟수",
        ["Roguelike.StopWhenInvestmentFull"] = "투자 가득 차면 중지",
        ["Roguelike.UseSupport"] = "｢{key=StartingCoreChar}｣ 지원유닛 사용",
        ["Roguelike.UseNonfriendSupport"] = "비친구 지원 사용",
        ["Roguelike.RefreshTraderWithDice"] = "주사위로 상인 갱신",
        ["Roguelike.StopAtFinalBoss"] = "5스테이지 보스 앞에서 일시정지",
        ["Roguelike.StopAtMaxLevel"] = "최대 레벨 달성 시 중지",
        ["Roguelike.CollectibleModeShopping"] = "작전 지원 선택 모드 쇼핑 활성화",
        ["Roguelike.CollectibleModeSquad"] = "전기주전자 획득 분대",
        ["Roguelike.StartWithEliteTwo"] = "｢{key=StartingCoreChar}｣ 2차 정예화까지 반복",
        ["Roguelike.OnlyStartWithEliteTwo"] = "｢{key=StartingCoreChar}｣ 2차 정예화까지 반복, 전투 X",
        ["Roguelike.Collectible.HotWater"] = "뜨거운 물",
        ["Roguelike.Collectible.Shield"] = "방패",
        ["Roguelike.Collectible.Ingot"] = "주괴",
        ["Roguelike.Collectible.Hope"] = "희망",
        ["Roguelike.Collectible.Random"] = "랜덤",
        ["Roguelike.Collectible.Key"] = "열쇠",
        ["Roguelike.Collectible.Dice"] = "주사위",
        ["Roguelike.Collectible.Ideas"] = "아이디어",
        ["Roguelike.Collectible.Ticket"] = "티켓",
        ["Roguelike.MonthlySquadAutoIterate"] = "월간 분대 자동 전환",
        ["Roguelike.MonthlySquadCheckComms"] = "월간 분대 통신",
        ["Roguelike.DeepExplorationAutoIterate"] = "심층 조사 자동 전환",
        ["Roguelike.FindPlayTimeTarget"] = "목표 플레이 시간",
        ["Roguelike.FirstFloorFoldartal"] = "1층 암호판 획득 반복, 전투 X",
        ["Roguelike.StartFoldartalList"] = "생존지상 분대 목표 암호판 설정",
        ["Roguelike.ExpectedCollapsalParadigms"] = "붕괴 패러다임 목록",
        ["Roguelike.StartWithSeed"] = "지정 시드로 시작",
        ["Reclamation.Title"] = "생식연산",
        ["Reclamation.Theme"] = "테마",
        ["Reclamation.Mode"] = "모드",
        ["Reclamation.IncrementMode"] = "증분 모드",
        ["Reclamation.NumCraftBatches"] = "제작 배치 수",
        ["Reclamation.ToolsToCraft"] = "제작 도구 목록",
        ["Reclamation.ClearStore"] = "창고 비우기",
        ["Custom.Title"] = "커스텀",
        ["Custom.TaskNames"] = "작업 이름 목록",
        ["Custom.TaskNamesPreview"] = "미리보기",
        ["Common.LoadingTaskHint"] = "왼쪽 작업 목록에서 작업을 먼저 선택하세요.",
        ["Common.ValidationIssues"] = "검증 메시지",
        ["Common.WarningPrefix"] = "경고",
        ["Common.ErrorPrefix"] = "오류",
        ["TaskQueue.Validation.Clean"] = "검증을 통과했습니다.",
        ["TaskQueue.Validation.WarningCount"] = "경고 항목 {0}개가 있습니다.",
        ["TaskQueue.Validation.BlockingCount"] = "차단 오류 {0}개가 있습니다.",
        ["TaskQueue.Validation.LoadFailed"] = "검증 보고서를 불러오지 못했습니다.",
        ["TaskQueue.Error.BlockingValidation"] = "작업 `{0}` 이(가) 검증에 의해 차단되었습니다: {1}",
        ["Issue.ClientTypeMissing"] = "클라이언트 유형은 비워둘 수 없습니다.",
        ["Issue.FightStageMissing"] = "전투 스테이지는 비워둘 수 없습니다.",
        ["Issue.FightSeriesOutOfRange"] = "연전 값은 -1 에서 6 사이여야 합니다.",
        ["Issue.FightTimesOutOfRange"] = "전투 횟수는 0 이상이어야 합니다.",
        ["Issue.FightDropMissing"] = "목표 드랍 사용 시 드랍 ID가 필요합니다.",
        ["Issue.FightTimesMayNotExhausted"] = "현재 연전 설정에서 횟수가 남을 수 있습니다.",
        ["Issue.RecruitTimesOutOfRange"] = "공개채용 횟수는 0 이상이어야 합니다.",
        ["Issue.RecruitTimeOutOfRange"] = "공개채용 시간은 60..540 범위의 10분 단위여야 합니다.",
        ["Issue.TaskFieldMissing"] = "설정에 필수 필드가 누락되었습니다.",
        ["Issue.TaskFieldTypeInvalid"] = "필드 형식이 잘못되어 파싱할 수 없습니다.",
        ["Issue.DelimitedInputParseFailed"] = "구조화된 입력으로 보입니다. 구분자 기반 평문으로 입력하세요.",
        ["Issue.RoguelikeModeInvalid"] = "로그라이크 모드가 지원되지 않습니다.",
        ["Issue.RoguelikeThemeUnknown"] = "알 수 없는 테마로 인해 JieGarden으로 대체되었습니다.",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "난이도는 -1 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "시작 횟수는 0 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "투자 횟수는 0 이상이어야 하며 자동 보정되었습니다.",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "상인 주사위 갱신은 Mizuki에서만 지원되어 비활성화되었습니다.",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime은 JieGarden이 필요하여 자동 대체되었습니다.",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 대상은 1..3 범위로 자동 보정되었습니다.",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "현재 모드/테마/분대에서는 엘리트2 시작이 비활성화되었습니다.",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "엘리트2만 시작은 엘리트2 시작이 필요합니다.",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "지원 사용과 엘리트2 시작이 충돌하여 엘리트2 시작을 비활성화했습니다.",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "시드 형식이 잘못되었습니다. `<영숫자>,rogue_<id>,<step>` 형식을 사용하세요.",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "시작 폴더탈 목록은 3개로 잘렸습니다.",
        ["Issue.ReclamationThemeUnknown"] = "생식연산 테마가 알 수 없어 Tales로 대체되었습니다.",
        ["Issue.ReclamationModeInvalid"] = "생식연산 모드가 지원되지 않습니다.",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "증분 모드는 0/1만 지원되어 자동 보정되었습니다.",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "제작 배치 수는 0..99999 범위로 자동 보정되었습니다.",
        ["Issue.ReclamationToolNameInvalid"] = "제작 도구 목록에 파싱할 수 없는 구조화 토큰이 있습니다.",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "무저장 모드에서는 제작 도구 목록이 무시되어 비워졌습니다.",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "저장 모드에서는 창고 비우기가 무시되어 비활성화되었습니다.",
        ["Issue.CustomTaskNamesEmpty"] = "커스텀 작업 이름 목록이 비어 있습니다.",
        ["Issue.CustomTaskNameInvalid"] = "커스텀 작업 이름에 파싱할 수 없는 구조화 토큰이 있습니다.",
        ["Issue.CustomTaskNameUnknown"] = "커스텀 작업 이름을 인식할 수 없습니다.",
        ["Issue.CustomTaskNamesNormalized"] = "커스텀 작업 이름이 정규화 및 중복 제거되었습니다.",
    };

    private static readonly Dictionary<string, string> ZhTw = new(StringComparer.OrdinalIgnoreCase)
    {
        ["StartUp.Title"] = "開始喚醒",
        ["StartUp.AccountName"] = "帳號",
        ["StartUp.AccountSwitch"] = "帳號切換",
        ["StartUp.AccountSwitchManualRun"] = "立即切換",
        ["StartUp.AccountSwitchTip"] = "需要切換到的帳號，留空以停用。\n輸入登入介面顯示的內容，如 ｢123****4567｣，可輸入 ｢123****4567｣ 或 ｢4567｣ 或 ｢23****45｣\n僅支援官服、B服，不支援登入帳號。",
        ["StartUp.ClientType"] = "客戶端",
        ["StartUp.StartGameEnabled"] = "是否啟動用戶端",
        ["StartUp.ConnectConfig"] = "連線預設",
        ["StartUp.ConnectAddress"] = "連線位址",
        ["StartUp.ConnectionAddressTip"] = "若遇到問題可嘗試手動修改",
        ["StartUp.AdbPath"] = "ADB 路徑",
        ["StartUp.Select"] = "選擇",
        ["StartUp.TouchMode"] = "觸控模式",
        ["StartUp.AutoDetect"] = "自動偵測連線",
        ["StartUp.AutoDetectConnectionTip"] = "每次偵測完成後會自動取消勾選，若需要重新偵測可再次勾選",
        ["StartUp.AttachScreencap"] = "AttachWindow-截圖",
        ["StartUp.AttachMouse"] = "AttachWindow-觸控",
        ["StartUp.AttachKeyboard"] = "AttachWindow-鍵盤",
        ["Fight.Title"] = "刷理智",
        ["Fight.Stage"] = "關卡",
        ["Fight.UseMedicine"] = "使用理智藥",
        ["Fight.Medicine"] = "理智藥數量",
        ["Fight.UseStone"] = "使用源石",
        ["Fight.Stone"] = "源石數量",
        ["Fight.EnableTimesLimit"] = "限制次數",
        ["Fight.Times"] = "次數",
        ["Fight.Series"] = "連戰",
        ["Fight.UseExpiringMedicine"] = "使用即將過期理智藥",
        ["Fight.DrGrandet"] = "理智策略 DrGrandet",
        ["Fight.EnableTargetDrop"] = "指定掉落",
        ["Fight.DropId"] = "掉落物 ID",
        ["Fight.DropCount"] = "目標數量",
        ["Fight.UseAlternateStage"] = "啟用換圖",
        ["Fight.HideUnavailableStage"] = "隱藏不可用關卡",
        ["Fight.StageResetMode"] = "重置模式",
        ["Fight.UseCustomAnnihilation"] = "自訂剿滅",
        ["Fight.AnnihilationStage"] = "剿滅關卡",
        ["Recruit.Title"] = "公開招募",
        ["Recruit.Times"] = "招募次數",
        ["Recruit.Refresh"] = "自動刷新",
        ["Recruit.ForceRefresh"] = "強制刷新",
        ["Recruit.UseExpedited"] = "使用加急",
        ["Recruit.SkipRobot"] = "跳過支援機械",
        ["Recruit.ChooseLevel3"] = "選擇 3 星",
        ["Recruit.ChooseLevel4"] = "選擇 4 星",
        ["Recruit.ChooseLevel5"] = "選擇 5 星",
        ["Recruit.SetTime"] = "設定時長",
        ["Recruit.Level3Time"] = "3 星時長",
        ["Recruit.Level4Time"] = "4 星時長",
        ["Recruit.Level5Time"] = "5 星時長",
        ["Recruit.ExtraTagsMode"] = "額外標籤策略",
        ["Recruit.FirstTags"] = "優先標籤",
        ["Roguelike.Title"] = "肉鴿",
        ["Roguelike.Theme"] = "主題",
        ["Roguelike.Mode"] = "模式",
        ["Roguelike.Difficulty"] = "難度",
        ["Roguelike.StartsCount"] = "開局次數",
        ["Roguelike.Squad"] = "開局分隊",
        ["Roguelike.Roles"] = "開局職業",
        ["Roguelike.CoreChar"] = "核心幹員",
        ["Roguelike.InvestmentEnabled"] = "啟用投資",
        ["Roguelike.InvestmentWithMoreScore"] = "投資優先分數",
        ["Roguelike.InvestmentsCount"] = "投資次數上限",
        ["Roguelike.StopWhenInvestmentFull"] = "投資滿時停止",
        ["Roguelike.UseSupport"] = "｢{key=StartingCoreChar}｣ 使用助戰",
        ["Roguelike.UseNonfriendSupport"] = "使用非好友助戰",
        ["Roguelike.RefreshTraderWithDice"] = "使用骰子刷新商人",
        ["Roguelike.StopAtFinalBoss"] = "在第五層 BOSS 前暫停",
        ["Roguelike.StopAtMaxLevel"] = "滿級後自動停止",
        ["Roguelike.CollectibleModeShopping"] = "刷開局模式啟用購物",
        ["Roguelike.CollectibleModeSquad"] = "燒水分隊",
        ["Roguelike.StartWithEliteTwo"] = "凹 ｢{key=StartingCoreChar}｣ 直升精二",
        ["Roguelike.OnlyStartWithEliteTwo"] = "只凹 ｢{key=StartingCoreChar}｣ 直升精二，不進行作戰",
        ["Roguelike.Collectible.HotWater"] = "熱水壺",
        ["Roguelike.Collectible.Shield"] = "護盾",
        ["Roguelike.Collectible.Ingot"] = "源石錠",
        ["Roguelike.Collectible.Hope"] = "希望",
        ["Roguelike.Collectible.Random"] = "隨機",
        ["Roguelike.Collectible.Key"] = "鑰匙",
        ["Roguelike.Collectible.Dice"] = "骰子",
        ["Roguelike.Collectible.Ideas"] = "構想",
        ["Roguelike.Collectible.Ticket"] = "票券",
        ["Roguelike.MonthlySquadAutoIterate"] = "月度小隊自動切換",
        ["Roguelike.MonthlySquadCheckComms"] = "月度小隊通訊",
        ["Roguelike.DeepExplorationAutoIterate"] = "深入調查自動切換",
        ["Roguelike.FindPlayTimeTarget"] = "定向遊玩目標",
        ["Roguelike.FirstFloorFoldartal"] = "凹第一層遠見密文板，不進行作戰",
        ["Roguelike.StartFoldartalList"] = "生活隊凹開局密文板",
        ["Roguelike.ExpectedCollapsalParadigms"] = "坍縮範式列表",
        ["Roguelike.StartWithSeed"] = "使用指定種子開局",
        ["Reclamation.Title"] = "生息演算",
        ["Reclamation.Theme"] = "主題",
        ["Reclamation.Mode"] = "模式",
        ["Reclamation.IncrementMode"] = "增量模式",
        ["Reclamation.NumCraftBatches"] = "回合合成批次",
        ["Reclamation.ToolsToCraft"] = "合成工具列表",
        ["Reclamation.ClearStore"] = "清倉",
        ["Custom.Title"] = "自訂任務",
        ["Custom.TaskNames"] = "任務名列表",
        ["Custom.TaskNamesPreview"] = "格式化預覽",
        ["Common.LoadingTaskHint"] = "請先在左側任務列表中選擇對應任務。",
        ["Common.ValidationIssues"] = "校驗資訊",
        ["Common.WarningPrefix"] = "警告",
        ["Common.ErrorPrefix"] = "錯誤",
        ["TaskQueue.Validation.Clean"] = "校驗通過。",
        ["TaskQueue.Validation.WarningCount"] = "存在 {0} 條預警。",
        ["TaskQueue.Validation.BlockingCount"] = "存在 {0} 條阻斷錯誤。",
        ["TaskQueue.Validation.LoadFailed"] = "讀取校驗報告失敗。",
        ["TaskQueue.Error.BlockingValidation"] = "任務 `{0}` 存在阻斷校驗項：{1}",
        ["Issue.ClientTypeMissing"] = "客戶端類型不能為空。",
        ["Issue.FightStageMissing"] = "戰鬥關卡不能為空。",
        ["Issue.FightSeriesOutOfRange"] = "連戰範圍需在 -1 到 6。",
        ["Issue.FightTimesOutOfRange"] = "戰鬥次數不能小於 0。",
        ["Issue.FightDropMissing"] = "指定掉落時必須填寫掉落物 ID。",
        ["Issue.FightTimesMayNotExhausted"] = "當前次數與連戰設定可能無法整除。",
        ["Issue.RecruitTimesOutOfRange"] = "招募次數不能小於 0。",
        ["Issue.RecruitTimeOutOfRange"] = "招募時長需在 60..540 且步長為 10。",
        ["Issue.TaskFieldMissing"] = "配置缺少必填欄位。",
        ["Issue.TaskFieldTypeInvalid"] = "欄位型別不正確，無法解析。",
        ["Issue.DelimitedInputParseFailed"] = "輸入看起來像結構化資料，請改用分隔字元純文字。",
        ["Issue.RoguelikeModeInvalid"] = "肉鴿模式不受支援。",
        ["Issue.RoguelikeThemeUnknown"] = "主題未知，已降級為 JieGarden。",
        ["Issue.RoguelikeDifficultyOutOfRange"] = "難度不能小於 -1，已自動修正。",
        ["Issue.RoguelikeStartsCountOutOfRange"] = "開局次數不能小於 0，已自動修正。",
        ["Issue.RoguelikeInvestmentsCountOutOfRange"] = "投資次數不能小於 0，已自動修正。",
        ["Issue.RoguelikeRefreshTraderThemeMismatch"] = "僅 Mizuki 主題支援骰子刷新商人，已自動關閉。",
        ["Issue.RoguelikeFindPlaytimeThemeMismatch"] = "FindPlaytime 僅支援 JieGarden 主題，已自動降級。",
        ["Issue.RoguelikeFindPlaytimeTargetOutOfRange"] = "FindPlaytime 目標應在 1..3，已自動修正。",
        ["Issue.RoguelikeEliteTwoModeMismatch"] = "目前模式/主題/分隊不支援開局精二，已自動關閉。",
        ["Issue.RoguelikeOnlyEliteTwoRequiresEliteTwo"] = "僅開局精二依賴開局精二開關，已自動關閉。",
        ["Issue.RoguelikeEliteTwoSupportConflict"] = "助戰與開局精二衝突，已自動關閉開局精二。",
        ["Issue.RoguelikeStartWithSeedInvalid"] = "種子格式不合法，應為 `<英數字>,rogue_<id>,<step>`。",
        ["Issue.RoguelikeStartFoldartalListTrimmed"] = "起始折紙列表超過 3 項，已截斷。",
        ["Issue.ReclamationThemeUnknown"] = "生息主題未知，已降級為 Tales。",
        ["Issue.ReclamationModeInvalid"] = "生息模式不受支援。",
        ["Issue.ReclamationIncrementModeOutOfRange"] = "增量模式僅支援 0/1，已自動修正。",
        ["Issue.ReclamationNumCraftBatchesOutOfRange"] = "單次組裝輪數應在 0..99999，已自動修正。",
        ["Issue.ReclamationToolNameInvalid"] = "工具列表包含無法解析的結構化內容。",
        ["Issue.ReclamationToolsIgnoredInNoArchive"] = "無存檔模式會忽略工具列表，已清空。",
        ["Issue.ReclamationClearStoreIgnoredInArchive"] = "有存檔模式會忽略清倉，已關閉。",
        ["Issue.CustomTaskNamesEmpty"] = "自訂任務名稱列表為空。",
        ["Issue.CustomTaskNameInvalid"] = "自訂任務名稱包含無法解析的結構化內容。",
        ["Issue.CustomTaskNameUnknown"] = "自訂任務名稱未識別。",
        ["Issue.CustomTaskNamesNormalized"] = "自訂任務名稱已標準化並去重。",
    };

    private static readonly Dictionary<string, string> Pallas = new(EnUs, StringComparer.OrdinalIgnoreCase);

    private string _language = UiLanguageCatalog.DefaultLanguage;

    public event Action<LocalizationFallbackInfo>? FallbackReported;

    public string Language
    {
        get => _language;
        set
        {
            var normalized = UiLanguageCatalog.Normalize(value);
            if (!SetProperty(ref _language, normalized))
            {
                return;
            }

            OnPropertyChanged("Item[]");
        }
    }

    public string this[string key]
    {
        get
        {
            var normalizedLanguage = UiLanguageCatalog.Normalize(Language);
            var source = ResolveSource(normalizedLanguage);
            if (source.TryGetValue(key, out var value))
            {
                return ResolveInlineKeys(value, normalizedLanguage, [key]);
            }

            if (EnUs.TryGetValue(key, out value))
            {
                ReportFallback(normalizedLanguage, key, UiLanguageCatalog.FallbackLanguage);
                return ResolveInlineKeys(value, normalizedLanguage, [key]);
            }

            if (ZhCn.TryGetValue(key, out value))
            {
                ReportFallback(normalizedLanguage, key, UiLanguageCatalog.DefaultLanguage);
                return ResolveInlineKeys(value, normalizedLanguage, [key]);
            }

            ReportFallback(normalizedLanguage, key, "key");
            return key;
        }
    }

    public string GetOrDefault(string key, string fallback)
    {
        var value = this[key];
        return string.Equals(value, key, StringComparison.Ordinal) ? fallback : value;
    }

    public string GetOrDefaultForLanguage(string language, string key, string fallback)
    {
        var normalizedLanguage = UiLanguageCatalog.Normalize(language);
        var source = ResolveSource(normalizedLanguage);
        if (source.TryGetValue(key, out var value))
        {
            return ResolveInlineKeys(value, normalizedLanguage, [key]);
        }

        if (EnUs.TryGetValue(key, out value))
        {
            return ResolveInlineKeys(value, normalizedLanguage, [key]);
        }

        if (ZhCn.TryGetValue(key, out value))
        {
            return ResolveInlineKeys(value, normalizedLanguage, [key]);
        }

        return fallback;
    }

    private static Dictionary<string, string> ResolveSource(string language)
    {
        if (string.Equals(language, "en-us", StringComparison.OrdinalIgnoreCase))
        {
            return EnUs;
        }

        if (string.Equals(language, "ja-jp", StringComparison.OrdinalIgnoreCase))
        {
            return JaJp;
        }

        if (string.Equals(language, "ko-kr", StringComparison.OrdinalIgnoreCase))
        {
            return KoKr;
        }

        if (string.Equals(language, "zh-tw", StringComparison.OrdinalIgnoreCase))
        {
            return ZhTw;
        }

        if (string.Equals(language, "pallas", StringComparison.OrdinalIgnoreCase))
        {
            return Pallas;
        }

        return ZhCn;
    }

    private void ReportFallback(string language, string key, string fallbackSource)
    {
        FallbackReported?.Invoke(
            new LocalizationFallbackInfo(
                Scope: "TaskQueue.Localization",
                Language: language,
                Key: key,
                FallbackSource: fallbackSource));
    }

    private string ResolveInlineKeys(string value, string language, HashSet<string> resolvingKeys)
    {
        if (string.IsNullOrEmpty(value) || !value.Contains("{key=", StringComparison.Ordinal))
        {
            return value;
        }

        return InlineKeyPattern.Replace(
            value,
            match =>
            {
                var referencedKey = match.Groups[1].Value.Trim();
                if (string.IsNullOrWhiteSpace(referencedKey) || !resolvingKeys.Add(referencedKey))
                {
                    return match.Value;
                }

                try
                {
                    var referencedValue = LookupWithoutFallbackReport(language, referencedKey);
                    if (string.Equals(referencedValue, referencedKey, StringComparison.Ordinal))
                    {
                        return referencedKey;
                    }

                    return ResolveInlineKeys(referencedValue, language, resolvingKeys);
                }
                finally
                {
                    resolvingKeys.Remove(referencedKey);
                }
            });
    }

    private static string LookupWithoutFallbackReport(string language, string key)
    {
        var source = ResolveSource(language);
        if (source.TryGetValue(key, out var value))
        {
            return value;
        }

        if (EnUs.TryGetValue(key, out value))
        {
            return value;
        }

        if (ZhCn.TryGetValue(key, out value))
        {
            return value;
        }

        return key;
    }
}
