repo_url: "https://github.com/BLGchara/MaaAssistantArknights.git"  # 改成你的 fork
workdir: "./_work"
branch_prefix: "agent/fix"
default_base_branch: "master"  # MAA 主分支名可能是 master 或 main，请按实际修改

build:
  # 第一次先空着（只跑扫描+补丁）。确定依赖后再开启编译/测试。
  prepare: []
  commands: []
  test_commands: []

scan:
  enable_clang_tidy: false       # 需要 compile_commands.json，先关闭
  enable_cppcheck: true
  enable_semgrep: true
  semgrep_config: "./semgrep.yml"
  paths: ["."]
  exclude: ["build", "third_party", "3rdparty", "vendor", ".git", "_work"]

llm:
  provider: "openai"
  model: "gpt-4o-mini"
  api_key_env: "OPENAI_API_KEY"
  max_patch_attempts: 2
  max_changed_lines: 120

git:
  author_name: "AI Agent Bot"
  author_email: "bot@example.com"
  push_remote: "origin"   # 在 Actions 里我们会配置 token，让 nested clone 也能 push
  open_pr: false          # 首次先手动发 PR，后续再自动化
