name: Release Version Tagging

on:
  pull_request:
    branches:
      - master-v2
    types:
      - closed
  workflow_dispatch:
    inputs:
      tag:
        description: "Name of the tag to create for the release"
        type: string
        required: true

jobs:
  auto_tag_release:
    name: Tag Release
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.title, 'Release v') || startsWith(github.event.pull_request.title, 'release v')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.MAARELEASE_RELEASE }}

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Determine tag name
        id: extract_tag
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          INPUT_TAG: ${{ inputs.tag }}
        run: |
          if [ "$EVENT_NAME" != "workflow_dispatch" ]; then
            tag_name=$(printf '%s' "$PR_TITLE" | sed -E 's/(Release|release)//' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          else
            echo "tag_name=$INPUT_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Create and push release tag
        env:
          TAG_NAME: ${{ steps.extract_tag.outputs.tag_name }}
        run: |
          git tag -a "$TAG_NAME" -m "$TAG_NAME" -f
          git push origin "$TAG_NAME"

      - name: Merge tag into dev-v2 and push
        env:
          TAG_NAME: ${{ steps.extract_tag.outputs.tag_name }}
        run: |
          git switch dev-v2
          git merge "$TAG_NAME"
          git push origin dev-v2
