name: release-maa-linux

on:
  release:
    types: [published]

jobs:
  linux-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tag info
        run: |
          GIT_TAG=${GITHUB_REF#refs/*/}
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false
      - name: Bootstrap MaaDeps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 maadeps-download.py
      - name: Build MAA
        env:
          CC: ccache gcc-12
          CXX: ccache g++-12
        run: |
          mkdir -p build
          cmake -B build \
            -DINSTALL_THIRD_LIBS=ON \
            -DINSTALL_RESOURCE=ON \
            -DINSTALL_PYTHON=ON
          # -DFASTDEPLOY_DIRECTORY=~/fastdeploy \
          # -DOPENCV_DIRECTORY=~/opencv/lib/cmake/opencv4 \
          cmake --build build --parallel $(nproc --all)
          
          mkdir -p install
          cmake --install build --prefix install

      - name: tar files
        run: |
          mkdir -p release
          cd install
          tar czvf $GITHUB_WORKSPACE/release/MAA-${{ env.GIT_TAG }}-linux.tar.gz .

      - name: Upload image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'release/*.tar.gz'
          file_glob: true
          tag: ${{ env.GIT_TAG }}
          overwrite: true
