name: Build Test for website

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "docs/**"
      - "website/**"
  pull_request:
    branches:
      - "dev"
    paths:
      - "docs/**"
      - "website/**"
  workflow_dispatch:

jobs:
  build-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install
        working-directory: "./website"

      - name: Build
        run: pnpm run build
        working-directory: "./website"

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "./website/dist"
